### ISSUE TITLE
Failed at the @ start script 'babel-node tools/run start'.

### ISSUE THREAD

**Issue by edwardleoni** [kriasoft/react-starter-kit#1001]
Hey, I'm running Node 6.9.1.

After cloning the repo and trying to run npm start I get:
> babel-node tools/run start

[19:15:24] Starting 'start'...
[19:15:24] Starting 'clean'...
[19:15:24] Finished 'clean' after 59 ms
[19:15:24] Starting 'copy'...
Error: watch /home/eduardo/projects/newhome.co.nz/react-starter-kit/src/content/ ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at Gaze._watchDir (/home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/gaze.js:304:30)
    at /home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/gaze.js:377:10
    at iterate (/home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/helper.js:83:3)
    at Gaze._initWatched (/home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/gaze.js:373:10)
    at Gaze.add (/home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/gaze.js:192:8)
    at new Gaze (/home/eduardo/projects/newhome.co.nz/react-starter-kit/node_modules/gaze/lib/gaze.js:74:10)

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

**Comment by bschatz12** [comment]
I think you are already running a process on that port.
Assuming this is on local machine - for local testing...
try opening a command line session with Administrator permission and kill all the node processes with the following command: taskkill /F /IM node.exe

**Comment by ulani** [comment]
@edwardleoni   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
