### ISSUE TITLE
Babel plugin unknown error on fresh install

### ISSUE THREAD

**Issue by zoltan-molnar** [kriasoft/react-starter-kit#1003]
I tried to test different branches: master, feature/redux
When I hit npm run I got the following:

```
C:\Users\mzol1\projects\speed5online\redux_app>npm start

> @ start C:\Users\mzol1\projects\speed5online\redux_app
> babel-node tools/run start

C:\Users\x\projects\y\redux_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "syntax-trailing-function-commas" specified in "C:\\Users\\mzol1\\projects\\speed5online\\redux_app\\package.json" at 0, attempted to resolve relative to "C:\\Users\\mzol1\\projects\\speed5online\\redux_app"
    at C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:154:20)
    at OptionManager.mergeOptions (C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:36)
    at OptionManager.init (C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at compile (C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\mzol1\projects\speed5online\redux_app\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mzol1\projects\speed5online\redux_app\npm-debug.log
```

Does anybody have an idea why this is happening?

**Comment by tomasfrancisco** [comment]
When I run babel-node:

```
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.

Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.
```

**Comment by Michal-sk** [comment]
you have to change package.json and add a babel-cli dependencie "babel-cli": "6.18.0",

**Comment by tomasfrancisco** [comment]
I follow the instructions to install the environment... but seems that babel is not capable of reading a plugin `syntax-trailing-function-commas`, or even to install it.

**Comment by gbersani** [comment]
Ran into the same issue this morning, caused by an outdated install of Node on Win10.

This seems to have taken care of the problem for me.
- Update Node to latest stable version.
- Delete node_modules folder.
- npm install
- npm start

**Comment by mklemme** [comment]
@gbersani can you let us know which versions you got this working on? currently experiencing the same problem on **npm** 4.0.5 **node** (tried both v6.9.4, v7.4.0). Tried with just `npm` and again with `yarn`. No luck. It seems installing the plugin through `npm install --save-dev babel-plugin-syntax-trailing-function-commas` works. It's now throwing the error:

```bash
module.js:472
    throw err;
    ^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myk/sprk/apps/frontend/internals/webpack/webpack.dev.babel.js:8:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Fresh install. Any ideas?

**Comment by ulani** [comment]
@zoltan-molnar   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
