### ISSUE TITLE
running npm start throws error in webpack config

### ISSUE THREAD

**Issue by Mykybo** [kriasoft/react-starter-kit#1014]
Steps to reproduce:
1. clone the repo
2. run 'npm install'
3. run 'npm start'

The error:
```
myApp/tools/webpack.config.js:76
        'react', ...(isDebug ? [] : [
                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/home/novak/Documents/myProjects/myApp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/novak/Documents/myProjects/myApp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/novak/Documents/myProjects/myApp/tools/runServer.js:12:1)
    at Module._compile (module.js:410:26)
```

**Comment by jonirrings** [comment]
maybe you should check if your package.json contains a `babel` field which has presets `stage-0` or `latest` or `es2015`

**Comment by Mykybo** [comment]
@jonirrings well, since I cloned the project without changing anything, there already is:

```
"babel": {
    "presets": [
      "react",
      "stage-0"
    ],
```

**Comment by frenzzy** [comment]
[Requirements](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#requirements): Node.js v6.5 or newer

**Comment by Mykybo** [comment]
@frenzzy thanks, I can't read, works now
