### ISSUE TITLE
Can't start node server with react-starter-kit

### ISSUE THREAD

**Issue by tuanhm93** [kriasoft/react-starter-kit#1035]
I have found a bug so I can't run and start Node Server
```
/Users/thudo/tuanhm/api/build/webpack:/data ^\.\/.*$:25
        return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
                                                                                        ^
Error: Cannot find module './.DS_Store'.
    at /Users/thudo/tuanhm/api/build/webpack:/data ^\.\/.*$:25:34
    at webpackContextResolve (/Users/thudo/tuanhm/api/build/webpack:/data ^\.\/.*$:25:89)
    at webpackContext (/Users/thudo/tuanhm/api/build/webpack:/data ^\.\/.*$:22:1)
    at /Users/thudo/tuanhm/api/build/webpack:/server.js:51:66
    at Array.forEach (native)
    at Object.<anonymous> (/Users/thudo/tuanhm/api/build/webpack:/server.js:50:37)
    at __webpack_require__ (/Users/thudo/tuanhm/api/build/webpack:/webpack/bootstrap 83a9ad11659a128c1fea:19:1)
    at /Users/thudo/tuanhm/api/build/webpack:/webpack/bootstrap 83a9ad11659a128c1fea:39:1
    at Object.<anonymous> (/Users/thudo/tuanhm/api/build/webpack:/webpack/bootstrap 83a9ad11659a128c1fea:39:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
1 null
/Users/thudo/tuanhm/api/tools/runServer.js:79
        throw new Error('Server terminated unexpectedly with code: ' + code + ' signal: ' + signal);
        ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.<anonymous> (/Users/thudo/tuanhm/api/tools/runServer.js:54:15)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Can you please tell me how to fix that bug?
Thanks!

**Comment by dabrowski-adam** [comment]
Have you download the server dependencies? (`npm install` inside the `build` folder)

**Comment by ulani** [comment]
@tuanhm93   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
