### ISSUE TITLE
Trying this out... Fresh install not working

### ISSUE THREAD

**Issue by TylerL-uxai** [kriasoft/react-starter-kit#1039]
updated npm, node, and install -g node-gyp

git clone, npm install, npm start

I get this

```
Tylers-MacBook-Pro:react-starter-december tdiddy$ npm start

> @ start /Users/tdiddy/react-starter-december
> babel-node tools/run start

[19:33:42] Starting 'start'...
[19:33:42] Starting 'clean'...
[19:33:44] Finished 'clean' after 1482 ms
[19:33:44] Starting 'copy'...
[19:33:44] Finished 'copy' after 32 ms
webpack built 293175dbeed0ffbe1761 in 5706ms
Child
    Time: 5706ms
                                           Asset     Size  Chunks             Chunk Names
       components/Header/logo-small.png?2f751285  2.83 kB          [emitted]  
    components/Header/logo-small@2x.png?8844262b  6.81 kB          [emitted]  
                                       client.js   202 kB       0  [emitted]  client
                                  admin.chunk.js   8.7 kB       1  [emitted]  admin
                                       vendor.js  1.47 MB       2  [emitted]  vendor
                                   client.js.map   153 kB       0  [emitted]  client
                              admin.chunk.js.map  7.49 kB       1  [emitted]  admin
                                   vendor.js.map  1.75 MB       2  [emitted]  vendor
Child
    Time: 5897ms
                                           Asset     Size  Chunks             Chunk Names
       components/Header/logo-small.png?2f751285  2.83 kB          [emitted]  
    components/Header/logo-small@2x.png?8844262b  6.81 kB          [emitted]  
                                 ../../server.js   262 kB       0  [emitted]  server
                             ../../server.js.map   208 kB       0  [emitted]  server
webpack: bundle is now VALID.
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/tdiddy/react-starter-december/build/webpack:/external "universal-router":1:1)
    at __webpack_require__ (/Users/tdiddy/react-starter-december/build/webpack:/webpack/bootstrap 06efbab1cea6eafb5e34:19:1)
    at Object.<anonymous> (/Users/tdiddy/react-starter-december/build/webpack:/src/server.js:20:1)
/Users/tdiddy/react-starter-december/tools/runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.<anonymous> (/Users/tdiddy/react-starter-december/tools/runServer.js:54:17)
    at ChildProcess.g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/tdiddy/.nvm/versions/node/v5.6.0/bin/node" "/Users/tdiddy/.nvm/versions/node/v5.6.0/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tdiddy/react-starter-december/npm-debug.log
```

**Comment by buildbreakdo** [comment]
@TylerL-uxai Wrong version of node is installed. If you look in the package.json you will see:
```
    "node": ">=6.5",
    "npm": ">=3.10"
```

Error output shows `npm ERR! node v5.6.0`. Need to upgrade.

**Comment by TylerL-uxai** [comment]
Doh! After updating node/npm it works :) Thank you. Is the user registration supposed to be blank?

**Comment by buildbreakdo** [comment]
@TylerL-uxai Yeah, believe the bones are there but not the full implementation.

**Comment by TylerL-uxai** [comment]
Are there any plans to implement user authentication or should I go for it myself, @buildbreakdo? Thanks! :)

**Comment by jonirrings** [comment]
@TylerL-uxai I think you should implement it to your own favour.

**Comment by buildbreakdo** [comment]
@TylerL-uxai Looks like there is something started here: https://github.com/kriasoft/react-starter-kit/pull/924 if you need an example.

**Comment by ClemensSahs** [comment]
@TylerL-uxai @buildbreakdo #924 is the first step yes (only view splitting)
I upload a other PR to make it easier import other passport strategies or some custom strategies.

I hope this will help you
#1053

**Comment by TylerL-uxai** [comment]
Thank you, @ClemensSahs ! I'm working on Passport local, and don't know what directory to put the server controller in. It would be nice if we had that feature! I'll try to help you with your PR, and offer additional documentation if you want. Let's do this together.

**Comment by ulani** [comment]
@TylerL-uxai   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
