### ISSUE TITLE
Fresh install - news feed error

### ISSUE THREAD

**Issue by jakub-astrahit** [kriasoft/react-starter-kit#1045]
Hi, when I run install, I get this warning:
```
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
```

Then when I run the app (I changed the port to 3030), I get this:
```
[15:29:00] The server is running at http://localhost:3030/
[BS] Proxying: http://localhost:3030
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3002
    External: http://10.254.8.121:3002
 -------------------------------------
          UI: http://localhost:3003
 UI External: http://10.254.8.121:3003
 -------------------------------------
[15:29:01] Finished 'start' after 13134 ms
```

http://localhost:3002/ shows this:
```
Error
Failed to load the news feed.
Error: Failed to load the news feed.
    at Object._callee$ (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\build\webpack:\src\routes\home\index.js:19:1)
    at tryCatch (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

And in CLI:

```
Error: Failed to load the news feed.

  - index.js:19 Object._callee$
    c:/web/BMonitor/webdev/src_nodejs/kpi-bridge-report/build/webpack:/src/route    s/home/index.js:19:1

  - runtime.js:64 tryCatch
    [kpi-bridge-report]/[regenerator-runtime]/runtime.js:64:40

  - runtime.js:355 GeneratorFunctionPrototype.invoke [as _invoke]
    [kpi-bridge-report]/[regenerator-runtime]/runtime.js:355:22

  - runtime.js:116 GeneratorFunctionPrototype.prototype.(anonymous function) [as     next]
    [kpi-bridge-report]/[regenerator-runtime]/runtime.js:116:21

  - asyncToGenerator.js:17 step
    [kpi-bridge-report]/[babel-runtime]/helpers/asyncToGenerator.js:17:30

  - asyncToGenerator.js:28
    [kpi-bridge-report]/[babel-runtime]/helpers/asyncToGenerator.js:28:13
```

Any ideas what to do, please? Is this News feed error related to the missing dependency?

**Comment by jonirrings** [comment]
maybe you should change the `port` in the `config.js`, and if you did, a proxy may be expected for the `news feed` fetch (in some areas in China, some sites are blocked).

**Comment by jakub2** [comment]
When I change the port from 3030 back to the initial value of 3000, then when I visit `http://localhost:3000/` I get the following error:

```
SyntaxError
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\node-fetch\lib\body.js:48:15
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Promise.then (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\sequelize\lib\promise.js:21:17)
    at Body.json (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\node-fetch\lib\body.js:47:24)
    at Object._callee$ (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\build\webpack:\src\routes\home\index.js:19:1)
    at tryCatch (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\regenerator-runtime\runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\regenerator-runtime\runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at c:\web\BMonitor\webdev\src_nodejs\kpi-bridge-report\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

What's the problem with the JSON, any ideas? I haven't modified anything, it's a fresh kit installation.

**Comment by hygkui** [comment]
Same issue

**Comment by georgezouq** [comment]
Same issue on mac,I get this error at first time.and I didn't change port. @jonirrings 

```
Error: Failed to load the news feed.

  - index.js:19 Object._callee$
    /Volumes/GeorgeZouQ/BF/Study/Github/react-starter-kit/build/webpack:/src/rou    tes/home/index.js:19:1

  - runtime.js:64 tryCatch
    [react-starter-kit]/[.0.10.1@regenerator-runtime]/runtime.js:64:40

  - runtime.js:355 Generator.invoke [as _invoke]
    [react-starter-kit]/[.0.10.1@regenerator-runtime]/runtime.js:355:22

  - runtime.js:116 Generator.prototype.(anonymous function) [as next]
    [react-starter-kit]/[.0.10.1@regenerator-runtime]/runtime.js:116:21


  - asyncToGenerator.js:17 step
    [react-starter-kit]/[.6.20.0@babel-runtime]/helpers/asyncToGenerator.js:17:3    0

  - asyncToGenerator.js:28
    [react-starter-kit]/[.
```

**Comment by hygkui** [comment]
if you just want it to run without an async request,  you can try this:

```
    // const resp = await fetch('/graphql', {
    //   method: 'post',
    //   headers: {
    //     Accept: 'application/json',
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({
    //     query: '{news{title,link,contentSnippet}}',
    //   }),
    //   credentials: 'include',
    // });
    // const { data } = await resp.json();
    const data = {
      news: [
        {
          title: 'new title',
          link: '/about',
          contentSnippet: 'balba',
        }
      ]
    }
    // if (!data || !data.news) throw new Error('Failed to load the news feed.');
```

Get it go~

**Comment by ulani** [comment]
@jakub-astrahit   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
