### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by j306796405** [kriasoft/react-starter-kit#1051]
FetchError: request to http://localhost:3000/graphql failed, reason: getaddrinfo ENOTFOUND localhost localhost:3000
    at ClientRequest.<anonymous> (/Users/jeffery/myGit/react-starter-kit/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at new Fetch (/Users/jeffery/myGit/react-starter-kit/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/jeffery/myGit/react-starter-kit/node_modules/node-fetch/index.js:37:10)
    at localFetch (/Users/jeffery/myGit/react-starter-kit/build/webpack:/src/core/fetch/fetch.server.js:30:1)
    at Object._callee$ (/Users/jeffery/myGit/react-starter-kit/build/webpack:/src/routes/home/index.js:19:1)
    at tryCatch (/Users/jeffery/myGit/react-starter-kit/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jeffery/myGit/react-starter-kit/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jeffery/myGit/react-starter-kit/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/jeffery/myGit/react-starter-kit/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/jeffery/myGit/react-starter-kit/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/jeffery/myGit/react-starter-kit/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/jeffery/myGit/react-starter-kit/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at Object.action (/Users/jeffery/myGit/react-starter-kit/build/webpack:/src/routes/home/index.js:19:1)
    at /Users/jeffery/myGit/react-starter-kit/node_modules/src/resolve.js:32:34
    at next (native)
    at step (/Users/jeffery/myGit/react-starter-kit/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/jeffery/myGit/react-starter-kit/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/jeffery/myGit/react-starter-kit/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/jeffery/myGit/react-starter-kit/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at next (/Users/jeffery/myGit/react-starter-kit/node_modules/universal-router/main.js:133:22)

How to fix this problem, thanks and merry christmas

**Comment by buildbreakdo** [comment]
@j306796405 Think you typed the address in wrong, wouldn't it be localhost:3001?

**Comment by stefancrain** [comment]
I'm also having this issue. I've cloned the repo and ran through the instructions in the getting started guide. 
```
$ node -v
v6.9.4
$ python --version
Python 2.7.13
$ node-gyp -v
v3.5.0
$ git branch
* master
$ sw_vers -productVersion
10.12.2
```
I haven't modified any of the code, here is the startup message I see: 
```
[10:28:38] The server is running at http://localhost:3000/
[BS] Proxying: http://localhost:3000
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3001
    External: http://192.168.1.2:3001
 ---------------------------------------
          UI: http://localhost:3002
 UI External: http://192.168.1.2:3002
 ---------------------------------------
[10:28:38] Finished 'start' after 5641 ms
```
When the browser opens with http://localhost:3001/ it spins and never connects. When I navigate to http://localhost:3000/ I get the error above mentioned in this issue. I have success when I get to a subpage like http://localhost:3000/login or http://localhost:3000/about. 

Could there be a problem with routing?

**Comment by langpavel** [comment]
Many possible reasons leads to this behavior. Check if `/graphql` endpoint works — it should display Graph*i*QL interface
