### ISSUE TITLE
[feature/react-intl] ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by mika75** [kriasoft/react-starter-kit#1068]
Hello,

When I launch feature/react-intl branch I get the following error.

```
webpack: bundle is now VALID.
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\PERSO\bit\temp\rsk-lint\react-starter-kit\build\webpack:\external "universal-router":1:1)
    at __webpack_require__ (C:\PERSO\bit\temp\rsk-lint\react-starter-kit\build\webpack:\webpack\bootstrap 00e030c55b1d337f9a1a:19:1)
    at Object.<anonymous> (C:\PERSO\bit\temp\rsk-lint\react-starter-kit\build\webpack:\src\server.js:21:1)
C:\PERSO\bit\temp\rsk-lint\react-starter-kit\tools\runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

```

Any idea ?

node v5.6.0
windows 7/64b
git bash

**Comment by mika75** [comment]
problem seem to be solved by reverting to 

"universal-router": "1.2.2",

**Comment by frenzzy** [comment]
[Requirements:](https://github.com/kriasoft/react-starter-kit/blob/ebd5faa1f04b5e1f98bdda844d35658c1190160e/docs/getting-started.md#requirements) [Node.js v6.5](https://nodejs.org/) or newer

**Comment by mika75** [comment]
Thanks work fine
