### ISSUE TITLE
URGENT: REACT STARTER KIT ON HEROKU

### ISSUE THREAD

**Issue by gmaijoe** [kriasoft/react-starter-kit#1071]
Hey everyone, I'm launching a web app in 2 days using this react starter kit but I'm not understanding how to host this on heroku. Every time I upload it says it's successful but ends up getting an application error. 

I'm uploading the entire package right now (and tried doing the npm build --release) but both don't work.

When I do the entire package, the site loads but is missing assets/vendor.js and assets/client.js.

Super  confused. Anybody who knows or know of resources, let me know - thanks in advance.

**Comment by gmaijoe** [comment]
<img width="1280" alt="screen shot 2017-01-06 at 11 32 34 am" src="https://cloud.githubusercontent.com/assets/7184919/21726833/00759764-d404-11e6-85bc-8dfc5d80ee8d.png">

**Comment by koistya** [comment]
The app must be compiled with `--release` flag, e.g. `npm run build -- --release` and the contents of the `build` folder must be pushed to Heroku. This can be automated under a single command, e.g. `npm run deploy` (see `tools/deployToHeroku.js` and `package.json/scripts/deploy`)

**Comment by gmaijoe** [comment]
Awesome so I did exactly as you said with the npm run build -- --release and CD-ing into the build folder. Then I manually pushed it to heroku. When I check out the heroku URL, I get an application error with this error log:

`2017-01-06T17:55:38.636005+00:00 app[web.1]: 
2017-01-06T17:55:42.878724+00:00 app[web.1]: Error: Cannot find module 'underscore'
2017-01-06T17:55:42.878736+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-01-06T17:55:42.878737+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-01-06T17:55:42.878738+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-01-06T17:55:42.878738+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-06T17:55:42.878740+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/webpack:/external "underscore":1:1)
2017-01-06T17:55:42.878743+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap 57c623214bb458dda5bb:19:1)
2017-01-06T17:55:42.878745+00:00 app[web.1]:     at Object.<anonymous> (/app/webpack:/routes/register/Register.js:6:1)
2017-01-06T17:55:42.878746+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap 57c623214bb458dda5bb:19:1)
2017-01-06T17:55:42.878747+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/webpack:/routes/register/index.js:3:1)
2017-01-06T17:55:42.878747+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap 57c623214bb458dda5bb:19:1)
2017-01-06T17:55:42.878748+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/webpack:/routes/index.js:12:5)
2017-01-06T17:55:42.878749+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap 57c623214bb458dda5bb:19:1)
2017-01-06T17:55:42.878749+00:00 app[web.1]:     at Object.<anonymous> (/app/webpack:/server.js:20:1)
2017-01-06T17:55:42.878750+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap 57c623214bb458dda5bb:19:1)
2017-01-06T17:55:42.878751+00:00 app[web.1]:     at /app/webpack:/webpack/bootstrap 57c623214bb458dda5bb:39:1
2017-01-06T17:55:42.878751+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:45:10)
2017-01-06T17:55:42.935491+00:00 app[web.1]: 
2017-01-06T17:55:42.958093+00:00 app[web.1]: npm ERR! Linux 3.13.0-105-generic
2017-01-06T17:55:42.962452+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-01-06T17:55:42.962780+00:00 app[web.1]: npm ERR! node v6.9.1
2017-01-06T17:55:42.963064+00:00 app[web.1]: npm ERR! npm  v4.0.5
2017-01-06T17:55:42.963336+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-01-06T17:55:42.963580+00:00 app[web.1]: npm ERR! @ start: `node server.js`
2017-01-06T17:55:42.963780+00:00 app[web.1]: npm ERR! Exit status 1
2017-01-06T17:55:42.964811+00:00 app[web.1]: npm ERR! 
2017-01-06T17:55:42.965000+00:00 app[web.1]: npm ERR! Failed at the @ start script 'node server.js'.
2017-01-06T17:55:42.965204+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-01-06T17:55:42.965584+00:00 app[web.1]: npm ERR! not with npm itself.
2017-01-06T17:55:42.965399+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the  package,
2017-01-06T17:55:42.966179+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-01-06T17:55:42.966375+00:00 app[web.1]: npm ERR!     node server.js
2017-01-06T17:55:42.966570+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-01-06T17:55:42.966761+00:00 app[web.1]: npm ERR!     npm bugs 
2017-01-06T17:55:42.966955+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-01-06T17:55:42.967339+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-01-06T17:55:42.967145+00:00 app[web.1]: npm ERR!     npm owner ls 
2017-01-06T17:55:42.973100+00:00 app[web.1]: 
2017-01-06T17:55:42.973658+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-01-06T17:55:42.973475+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-01-06T17:55:43.119340+00:00 heroku[web.1]: Process exited with status 1
2017-01-06T17:55:43.136012+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-06T17:55:43.225802+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shorerelease.herokuapp.com request_id=73532699-d2da-4bb3-bb2f-616fb7274e9c fwd="97.86.245.33" dyno= connect= service= status=503 bytes=
2017-01-06T17:55:43.917008+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shorerelease.herokuapp.com request_id=f30db3c3-7d3b-4277-9f1f-d1b322d81911 fwd="97.86.245.33" dyno= connect= service= status=503 bytes=
2017-01-06T17:58:58.549534+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-06T17:58:58.549543+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-06T17:58:58.411196+00:00 app[api]: Deploy 706d088 by user shoredevelop@gmail.com
2017-01-06T17:58:58.411196+00:00 app[api]: Release v7 created by user shoredevelop@gmail.com
2017-01-06T17:58:58.599085+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-06T17:59:03.718531+00:00 heroku[web.1]: Starting process with command `npm start`
2017-01-06T17:59:07.096037+00:00 app[web.1]: 
2017-01-06T17:59:07.096052+00:00 app[web.1]: > @ start /app
2017-01-06T17:59:07.096053+00:00 app[web.1]: > node server.js
2017-01-06T17:59:07.096054+00:00 app[web.1]: 
2017-01-06T17:59:09.420480+00:00 app[web.1]: Error: Cannot find module 'underscore'
2017-01-06T17:59:09.420522+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-01-06T17:59:09.420523+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-01-06T17:59:09.420524+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-01-06T17:59:09.420524+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-06T17:59:09.420526+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/webpack:/external "underscore":1:1)
2017-01-06T17:59:09.420527+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap dd06f2298e2e55ac6b71:19:1)
2017-01-06T17:59:09.420528+00:00 app[web.1]:     at Object.<anonymous> (/app/webpack:/routes/register/Register.js:6:1)
2017-01-06T17:59:09.420529+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/webpack:/routes/register/index.js:3:1)
2017-01-06T17:59:09.420529+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap dd06f2298e2e55ac6b71:19:1)
2017-01-06T17:59:09.420530+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap dd06f2298e2e55ac6b71:19:1)
2017-01-06T17:59:09.420531+00:00 app[web.1]:     at Object.module.exports.Object.defineProperty.value (/app/webpack:/routes/index.js:12:5)
2017-01-06T17:59:09.420531+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap dd06f2298e2e55ac6b71:19:1)
2017-01-06T17:59:09.420533+00:00 app[web.1]:     at __webpack_require__ (/app/webpack:/webpack/bootstrap dd06f2298e2e55ac6b71:19:1)
2017-01-06T17:59:09.420532+00:00 app[web.1]:     at Object.<anonymous> (/app/webpack:/server.js:20:1)
2017-01-06T17:59:09.420533+00:00 app[web.1]:     at /app/webpack:/webpack/bootstrap dd06f2298e2e55ac6b71:39:1
2017-01-06T17:59:09.420534+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:45:10)
2017-01-06T17:59:09.435846+00:00 app[web.1]: 
2017-01-06T17:59:09.443542+00:00 app[web.1]: npm ERR! Linux 3.13.0-105-generic
2017-01-06T17:59:09.443731+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-01-06T17:59:09.443876+00:00 app[web.1]: npm ERR! node v6.9.1
2017-01-06T17:59:09.444120+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-01-06T17:59:09.443997+00:00 app[web.1]: npm ERR! npm  v4.0.5
2017-01-06T17:59:09.444228+00:00 app[web.1]: npm ERR! @ start: `node server.js`
2017-01-06T17:59:09.444638+00:00 app[web.1]: npm ERR! 
2017-01-06T17:59:09.444349+00:00 app[web.1]: npm ERR! Exit status 1
2017-01-06T17:59:09.444762+00:00 app[web.1]: npm ERR! Failed at the @ start script 'node server.js'.
2017-01-06T17:59:09.444934+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-01-06T17:59:09.444997+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the  package,
2017-01-06T17:59:09.445070+00:00 app[web.1]: npm ERR! not with npm itself.
2017-01-06T17:59:09.445358+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-01-06T17:59:09.445426+00:00 app[web.1]: npm ERR!     node server.js
2017-01-06T17:59:09.445561+00:00 app[web.1]: npm ERR!     npm bugs 
2017-01-06T17:59:09.445497+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-01-06T17:59:09.445622+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-01-06T17:59:09.445675+00:00 app[web.1]: npm ERR!     npm owner ls 
2017-01-06T17:59:09.445744+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-01-06T17:59:09.449173+00:00 app[web.1]: 
2017-01-06T17:59:09.449337+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-01-06T17:59:09.449399+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-01-06T17:59:09.541610+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-06T17:59:09.531370+00:00 heroku[web.1]: Process exited with status 1
2017-01-06T17:59:47.017803+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shorerelease.herokuapp.com request_id=f62b495a-ad04-452b-8ed7-694021efa251 fwd="97.86.245.33" dyno= connect= service= status=503 bytes=
2017-01-06T17:59:47.642562+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shorerelease.herokuapp.com request_id=30cea83f-fe53-4134-bd9d-ee7c772d1283 fwd="97.86.245.33" dyno= connect= service= status=503 bytes=
2017-01-06T17:59:50.338562+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=shorerelease.herokuapp.com request_id=d4d1a4e8-0632-4d20-8526-f2b27be25910 fwd="97.86.245.33" dyno= connect= service= status=503 bytes=
2017-01-06T17:59:50.594932+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=shorerelease.herokuapp.com request_id=a79d5445-8057-498e-a740-3c8b0de235d8 fwd="97.86.245.33" dyno= connect= service= status=503 bytes=`

Also, I'm looking for the "tools/deployToHeroku.js" but I only see AzureWeb and GithubPages options...
