### ISSUE TITLE
yarn start doesn't work

### ISSUE THREAD

**Issue by vidann1** [kriasoft/react-starter-kit#1091]
I get this error 
$ yarn start
yarn start v0.19.1
$ babel-node tools/run start 
/home/xanax/Desktop/MyApp/tools/webpack.config.js:76
        'react', ...(isDebug ? [] : [
                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/home/xanax/Desktop/MyApp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/xanax/Desktop/MyApp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/xanax/Desktop/MyApp/tools/runServer.js:12:1)
    at Module._compile (module.js:410:26)
error Command failed with exit code 1.

**Comment by peiris** [comment]
I'm also getting the same error.

**Comment by koistya** [comment]
Did you run `yarn install` first? Also make sure that you have Node.js v6 or higher.

**Comment by peiris** [comment]
@koistya Thank you very much. Updating Node to latest stable version, Fixed the issue.
