### ISSUE TITLE
Build or Start a release Failed

### ISSUE THREAD

**Issue by clovis818** [kriasoft/react-starter-kit#1100]
I am unable to generate a production build, and i do not know why.
Any ideas?

# Diff - tools/webpack.config.js
```
demo:~/projects/demo/repo/web$ diff tools/webpack.config.js tools/webpack.config.js.default
demo:~/projects/demo/repo/web$
```

# Diff - package.json
```
demo:~/projects/demo/repo/web$ diff -c package.json package.json.default
*** package.json	2017-01-23 02:49:50.000000000 -0800
--- package.json.default	2017-01-27 14:40:50.000000000 -0800
***************
*** 11,36 ****
      "babel-runtime": "^6.20.0",
      "bluebird": "^3.4.6",
      "body-parser": "^1.15.2",
-     "bootstrap": "^3.3.6",
      "classnames": "^2.2.5",
      "cookie-parser": "^1.4.3",
      "core-js": "^2.4.1",
      "express": "^4.14.0",
      "express-jwt": "^5.1.0",
      "fastclick": "^1.0.6",
      "fbjs": "^0.8.6",
      "history": "^4.5.0",
      "isomorphic-style-loader": "^1.1.0",
      "node-fetch": "^1.6.3",
      "normalize.css": "^5.0.0",
      "pretty-error": "^2.0.2",
      "query-string": "^4.2.3",
      "react": "^15.4.1",
-     "react-bootstrap": "^0.29.3",
-     "react-bootstrap-validation": "^0.1.11",
      "react-dom": "^15.4.1",
      "sequelize": "^3.28.0",
      "source-map-support": "^0.4.6",
      "universal-router": "^2.0.0",
      "whatwg-fetch": "^2.0.1"
    },
--- 11,39 ----
      "babel-runtime": "^6.20.0",
      "bluebird": "^3.4.6",
      "body-parser": "^1.15.2",
      "classnames": "^2.2.5",
      "cookie-parser": "^1.4.3",
      "core-js": "^2.4.1",
      "express": "^4.14.0",
+     "express-graphql": "^0.6.1",
      "express-jwt": "^5.1.0",
      "fastclick": "^1.0.6",
      "fbjs": "^0.8.6",
+     "graphql": "^0.8.2",
      "history": "^4.5.0",
      "isomorphic-style-loader": "^1.1.0",
+     "jsonwebtoken": "^7.2.1",
      "node-fetch": "^1.6.3",
      "normalize.css": "^5.0.0",
+     "passport": "^0.3.2",
+     "passport-facebook": "^2.1.1",
      "pretty-error": "^2.0.2",
      "query-string": "^4.2.3",
      "react": "^15.4.1",
      "react-dom": "^15.4.1",
      "sequelize": "^3.28.0",
      "source-map-support": "^0.4.6",
+     "sqlite3": "^3.1.8",
      "universal-router": "^2.0.0",
      "whatwg-fetch": "^2.0.1"
    },
demo:~/projects/demo/repo/web$
```

# Node - v7.4.0

node: v7.4.0
npm: 4.0.5
yarn: 0.19.1

# Install
```
demo:~/projects/demo/repo/web$ yarn install
yarn install v0.19.1
[1/5] Resolving packages...
success Already up-to-date.
Done in 2.01s.
demo:~/projects/demo/repo/web$
```

# Build - v7.4.0
```
demo@demo:~/projects/demo/repo/web$ yarn run build -- --release --trace-warnings --verbose
yarn run v0.19.1
$ babel-node tools/run build --release --trace-warnings --verbose
[23:51:17] Starting 'build'...
[23:51:17] Starting 'clean'...
[23:51:17] Finished 'clean' after 44 ms
[23:51:17] Starting 'copy'...
[23:51:17] Finished 'copy' after 46 ms
[23:51:17] Starting 'bundle'...
Error
    at NormalModule.onModuleBuildFailed (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/demo/projects/demo/repo/web/node_modules/postcss-loader/index.js:130:13
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
demo@demo:~/projects/demo/repo/web$
```

# Start - v7.4.0
```
demo@demo:~/projects/demo/repo/web$ yarn start -- --release --trace-warnings --verbose
yarn start v0.19.1
$ babel-node tools/run start --release --trace-warnings --verbose
[23:51:53] Starting 'start'...
[23:51:53] Starting 'clean'...
[23:51:53] Finished 'clean' after 93 ms
[23:51:53] Starting 'copy'...
[23:51:53] Finished 'copy' after 113 ms
(node:1461) Error: callback(): The callback was already called.
    at context.callback (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at /home/demo/projects/demo/repo/web/node_modules/postcss-loader/index.js:137:13
(node:1461) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
(node:1461) Error: callback(): The callback was already called.
    at context.callback (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at /home/demo/projects/demo/repo/web/node_modules/postcss-loader/index.js:137:13
^C
demo@demo:~/projects/demo/repo/web$
```

# Node - v6.9.4

node: v6.9.4
npm: 3.10.10
yarn: 0.19.1

# Build - v6.9.4
```
demo@demo:~/projects/demo/repo/web$ yarn run build -- --release --trace-warnings --verbose
yarn run v0.19.1
$ babel-node tools/run build --release --trace-warnings --verbose
[00:12:50] Starting 'build'...
[00:12:50] Starting 'clean'...
[00:12:50] Finished 'clean' after 52 ms
[00:12:50] Starting 'copy'...
[00:12:50] Finished 'copy' after 67 ms
[00:12:50] Starting 'bundle'...
ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, open '/home/demo/projects/demo/repo/web/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at module.exports (/home/demo/projects/demo/repo/web/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/home/demo/projects/demo/repo/web/node_modules/svgo/lib/svgo.js:21:19)
    at /home/demo/projects/demo/repo/web/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/home/demo/projects/demo/repo/web/node_modules/postcss/lib/postcss.es6:111:27)
    at /home/demo/projects/demo/repo/web/node_modules/cssnano/dist/index.js:286:40
    at Array.forEach (native)
    at /home/demo/projects/demo/repo/web/node_modules/cssnano/dist/index.js:273:29
    at DependenciesBlock.onModuleBuildFailed (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/demo/projects/demo/repo/web/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/demo/projects/demo/repo/web/node_modules/postcss-loader/index.js:130:13
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
demo@demo:~/projects/demo/repo/web$
```

# Start - v6.9.4
```
demo@demo:~/projects/demo/repo/web$ yarn start -- --release --trace-warnings --verbose
yarn start v0.19.1
$ babel-node tools/run start --release --trace-warnings --verbose
[00:17:45] Starting 'start'...
[00:17:45] Starting 'clean'...
[00:17:45] Finished 'clean' after 99 ms
[00:17:45] Starting 'copy'...
[00:17:46] Finished 'copy' after 170 ms
(node:4026) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: callback(): The callback was already called.
    at emitPendingUnhandledRejections (internal/process/promises.js:57:27)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
(node:4026) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: callback(): The callback was already called.
    at emitPendingUnhandledRejections (internal/process/promises.js:57:27)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
^C
demo@demo:~/projects/demo/repo/web$
```

**Comment by clovis818** [comment]
disabling svgo from cssnano is a temporary fix.
http://cssnano.co/optimisations/svgo/

```
{
        test: /\.css/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            // CSS Loader https://github.com/webpack/css-loader
            importLoaders: 1,
            sourceMap: isDebug,
            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]',
            // CSS Nano http://cssnano.co/options/
            minimize: !isDebug,
            discardComments: { removeAll: true },
            svgo: false,
          })}`,
          'postcss-loader?pack=default',
        ],
      }
```
