### ISSUE TITLE
npm start not running error code ELIFECYCLE

### ISSUE THREAD

**Issue by XumaTech** [kriasoft/react-starter-kit#1112]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\4_Other\SanShip\source\api\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Users\Kayson\AppData\Roaming\npm;C:\Users\Kayson\AppData\Roaming\npm\node_modules;C:\Users\Kayson\AppData\Roaming\npm\node_modules;C:\Users\Kayson\AppData\Roaming\npm;C:\Users\Kayson\AppData\Roaming\npm\node_modules;C:\Users\Kayson\AppData\Roaming\npm\node_modules
10 verbose lifecycle @~start: CWD: D:\4_Other\SanShip\source\api
11 silly lifecycle @~start: Args: [ '/d /s /c', 'DEBUG=*:* babel-node tools/run start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `DEBUG=*:* babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd D:\4_Other\SanShip\source\api
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ start: `DEBUG=*:* babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script 'DEBUG=*:* babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     DEBUG=*:* babel-node tools/run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by haisonfpt** [comment]
Windows 8.1

**Comment by crorodriguezro** [comment]
I'm having the same problem

**Comment by phpeek** [comment]
@haisonfpt @crorodriguezro Can You try running this command manually ?

```bash
DEBUG=*:* babel-node tools/run start
```bash

If it fails, then try
```bash
set DEBUG=*:*
babel-node tools/run start
```

**Comment by crorodriguezro** [comment]
I downgrade node 7 to 6 and that fixed my problem

**Comment by ulani** [comment]
@XumaTech   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
