### ISSUE TITLE
Error when importing React Components (from npm/node_modules)

### ISSUE THREAD

**Issue by mesrob-fender** [kriasoft/react-starter-kit#1129]
Seems like the webpack babel-loader is not parsing correctly when trying to import a React Component installed from npm (Example using [react-icons](https://www.npmjs.com/package/react-icons)).

- Tried it on a fresh clone of the RSK (master); 
- `yarn add react-icons`
- `import FaBeer from 'react-icons/fa/beer';`

```
yarn start v0.19.1
$ babel-node tools/run start
[23:18:53] Starting 'start'...
[23:18:53] Starting 'clean'...
[23:18:53] Finished 'clean' after 43 ms
[23:18:53] Starting 'copy'...
[23:18:53] Finished 'copy' after 15 ms
webpack built d8bf302427a78a8d8a29 in 4142ms
Child client:
    Time: 4142ms

    ERROR in ./~/react-icons/fa/beer.js
    Module parse failed: /private/tmp/react-starter-kit/node_modules/react-icons/fa/beer.js Unexpected token (6:4)
    You may need an appropriate loader to handle this file type.
    |
    | const FaBeer = props => (
    |     <Icon viewBox="0 0 40 40" {...props}>
    |         <g><path d="m14.8 20v-8.6h-5.7v5.7q0 1.2 0.8 2.1t2 0.8h2.9z m22.8 10v4.3h-25.7v-4.3l2.9-4.3h-2.9q-3.5 0-6-2.5t-2.5-6.1v-7.1l-1.5-1.4 0.7-2.9h10.8l0.7-2.8h21.4l0.7 4.2-1.4 0.8v17.8z"/></g>
    |     </Icon>
     @ ./src/components/Navigation/Navigation.js 30:12-42
     @ ./src/components/Header/Header.js
     @ ./src/components/Layout/Layout.js
     @ ./src/routes/home/index.js
     @ ./src/routes/index.js
     @ ./src/client.js
     @ multi babel-polyfill react-hot-loader/patch webpack-hot-middleware/client ./client.js
Child server:
    Time: 4422ms
                                           Asset     Size  Chunks             Chunk Names
       components/Header/logo-small.png?2f751285  2.83 kB          [emitted]
    components/Header/logo-small@2x.png?8844262b  6.81 kB          [emitted]
                                 ../../server.js   243 kB       0  [emitted]  server
                             ../../server.js.map   200 kB       0  [emitted]  server
webpack: Failed to compile.
/private/tmp/react-starter-kit/node_modules/react-icons/fa/beer.js:2
import React from 'react'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/react-starter-kit/build/webpack:/external "react-icons/fa/beer":1:1)
    at __webpack_require__ (/private/tmp/react-starter-kit/build/webpack:/webpack/bootstrap 4985210f45442ea9b0ae:19:1)
    at Object.module.exports.Object.defineProperty.value (/private/tmp/react-starter-kit/build/webpack:/src/components/Navigation/Navigation.js:15:1)
    at __webpack_require__ (/private/tmp/react-starter-kit/build/webpack:/webpack/bootstrap 4985210f45442ea9b0ae:19:1)
    at Object.module.exports.Object.defineProperty.value (/private/tmp/react-starter-kit/build/webpack:/src/components/Header/Header.js:14:1)
    at __webpack_require__ (/private/tmp/react-starter-kit/build/webpack:/webpack/bootstrap 4985210f45442ea9b0ae:19:1)
    at Object.module.exports.Object.defineProperty.value (/private/tmp/react-starter-kit/build/webpack:/src/components/Layout/Layout.js:13:1)
    at __webpack_require__ (/private/tmp/react-starter-kit/build/webpack:/webpack/bootstrap 4985210f45442ea9b0ae:19:1)
/private/tmp/react-starter-kit/tools/runServer.js:67
          throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (/private/tmp/react-starter-kit/tools/runServer.js:53:17)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
error Command failed with exit code 1.
```

**Comment by frenzzy** [comment]
babel-loader in RSK configuration compiles only content of `src/` folder and ignores `node_modules/` to speed up the build, because npm modules usually provide already compiled version of code.

So, just change your imports to use prepared version:
```js
import FaBeer from 'react-icons/lib/fa/beer';
```

**Comment by mesrob-fender** [comment]
Thanks @frenzzy, I was looking for the Webpack configuration (vendor) to make exceptions for certain npm modules, but in hindsight that wouldn't be optimal practice for performance.
