### ISSUE TITLE
error when run npm/yarn start

### ISSUE THREAD

**Issue by puterakahfi** [kriasoft/react-starter-kit#1148]
Hi,
I just use react starterkit, I got error when run yarn/npm start 

OS  : elementary loki
yarn version : 0.20.3
node version : v7.5.0

here the log from my npm-debug.log 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle web@0.0.0~prestart: web@0.0.0
6 silly lifecycle web@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle web@0.0.0~start: web@0.0.0
8 verbose lifecycle web@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle web@0.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/mnt/WEBSITE/puterakahfi/learn-react/starterkit/node_modules/.bin:/home/pkahfi/bin:/home/pkahfi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle web@0.0.0~start: CWD: /mnt/WEBSITE/puterakahfi/learn-react/starterkit
11 silly lifecycle web@0.0.0~start: Args: [ '-c', 'babel-node tools/run start' ]
12 silly lifecycle web@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle web@0.0.0~start: Failed to exec start script
14 verbose stack Error: web@0.0.0 start: `babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid web@0.0.0
16 verbose cwd /mnt/WEBSITE/puterakahfi/learn-react/starterkit
17 error Linux 4.4.0-64-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error web@0.0.0 start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the web@0.0.0 start script 'babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the web package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs web
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls web
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thanks.

**Comment by ucay** [comment]
Make sure port 3000 are available.

**Comment by langpavel** [comment]
Make sure you have ports 3000 and 3001 available and check console output. This log is useless.

**Comment by puterakahfi** [comment]
thanks for the reply, 
I am using reactboilerplate and  create-react-app, all are running well with port 3000 or 3001
I'll try it again

**Comment by puterakahfi** [comment]
I removed old starterkit project and redownload  same version(0.5.0) and run the project, it's working fine now, really weird. :(

I will close this issue, thanks for the help.
