### ISSUE TITLE
[branch feature/react-intl] Project does'nt start

### ISSUE THREAD

**Issue by mika75** [kriasoft/react-starter-kit#1165]
Hello,

Today I pull this branch : feature/react-intl

npm i + npm start --> error

node : v6.9.4

```
 ERROR in ./src/server.js
    Module build failed: Error: parseQuery should get a string as first argument
        at Object.parseQuery (\react-starter-kit\node_modules\loader-utils\index.js:68:9)
        at Object.module.exports (react-starter-kit\node_modules\babel-loader\lib\index.js:79:35)
     @ multi babel-polyfill ./server.js
webpack: Failed to compile.
module.js:471
    throw err;
    ^
```

**Comment by langpavel** [comment]
Testing feature/react-intl
- [x] node 7.4.0 + yarn 0.21.3
- [x] node 7.4.0 + npm 4.0.5
- [x] node 6.10.0 + npm 3.10.10
