### ISSUE TITLE
JS error report point to incorrect position with HMR

### ISSUE THREAD

**Issue by Nerv-Eva** [kriasoft/react-starter-kit#1176]
For example, server.js
```javascript
hello
import 'babel-polyfill';
import path from 'path';
import express from 'express';
...
```
**"hello" is at line 9.**
Run "yarn start", get error

```
/Users/xxx/react-starter-kit/build/webpack:/src/server.js:41
app.use(bodyParser.json());
^
ReferenceError: hello is not defined
    at Object.<anonymous> (/Users/xxx/react-starter-kit/build/webpack:/src/server.js:41:1)
    at __webpack_require__ (/Users/xxx/react-starter-kit/build/webpack:/webpack/bootstrap 2880cf43978214a42c68:19:1)
    at /Users/xxx/react-starter-kit/build/webpack:/webpack/bootstrap 2880cf43978214a42c68:65:1
    at Object.<anonymous> (/Users/xxx/react-starter-kit/build/server.js:71:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
/Users/xxx/react-starter-kit/tools/runServer.js:79
          throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);

```

**it points to line 41**

**Comment by ulani** [comment]
@Nerv-Eva   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
