### ISSUE TITLE
I had a DeprecationWarning.

### ISSUE THREAD

**Issue by phenrigomes** [kriasoft/react-starter-kit#1194]
yarn start v0.18.1
$ babel-node tools/run start
[21:11:17] Starting 'start'...
[21:11:17] Starting 'clean'...
[21:11:17] Finished 'clean' after 41 ms
[21:11:17] Starting 'copy'...
[21:11:17] Finished 'copy' after 29 ms
(node:17935) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack built 779f8cd58e35eecca355 in 5924ms

**Comment by langpavel** [comment]
I think this was fixed in 3rd party package very recently. Try remove `node_modules` and run `yarn` again. Give me :-1: if it does not work, :+1: if it helps. We can close this after few days I hope :-)

**Comment by langpavel** [comment]
I wiped out cache, node_modules and I see this on my private project too
```
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (.../node_modules/babel-loader/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (.../node_modules/babel-loader/lib/index.js:104:35)
    at LOADER_EXECUTION (.../node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (.../node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (.../node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (.../node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (.../node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at .../node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at .../node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

**Comment by phpeek** [comment]
@phenrigomes @langpavel Do You guys use any custom webpack loaders ?

**Comment by MinJieLiu** [comment]
I am also a new download, but also this error

**Comment by ulani** [comment]
@phenrigomes   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
