### ISSUE TITLE
component level scss integrations

### ISSUE THREAD

**Issue by pulkitnandan** [kriasoft/react-starter-kit#1222]
Hi,

I have used redux based boilerplate of this repo and used https://github.com/kriasoft/react-starter-kit/blob/fb36e0fb732da65351df5aa0cedf56d9ddaadc1c/docs/recipes/how-to-use-sass.md to add component level scss.

But it fails with a bus error.

rohitn@rohitn ~/react-starter-kit $ npm run start

> web@0.0.0 start /home/rohitn/react-starter-kit
> babel-node tools/run start

```
[17:50:10] Starting 'start'...
[17:50:10] Starting 'clean'...
[17:50:11] Finished 'clean' after 485 ms
[17:50:11] Starting 'copy'...
[17:50:11] Finished 'copy' after 25 ms
(node:26504) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Bus error
npm ERR! code ELIFECYCLE
npm ERR! errno 135
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the web@0.0.0 start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rohitn/.npm/_logs/2017-04-13T12_20_15_817Z-debug.log
rohitn@rohitn ~/react-starter-kit $ npm run start
```

If i do not use that particular component, sometimes after first npm install error thrown is 

```
> web@0.0.0 start /home/rohitn/react-starter-kit
> babel-node tools/run start

[17:53:59] Starting 'start'...
[17:53:59] Starting 'clean'...
[17:54:00] Finished 'clean' after 527 ms
[17:54:00] Starting 'copy'...
[17:54:00] Finished 'copy' after 23 ms
(node:26640) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack built c3eb144fba634210aaf0 in 5829ms
webpack building...
webpack built c3eb144fba634210aaf0 in 311ms
Child client:
    Time: 311ms
Child server:
    Time: 250ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  226 kB       0  [emitted]  server
    ../../server.js.map  192 kB       0  [emitted]  server
webpack: Compiled successfully.
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

/home/rohitn/react-starter-kit/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
            ^
Error: Please install sqlite3 package manually
    at new ConnectionManager (/home/rohitn/react-starter-kit/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/home/rohitn/react-starter-kit/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/home/rohitn/react-starter-kit/node_modules/sequelize/lib/sequelize.js:233:18)
    at Object.<anonymous> (/home/rohitn/react-starter-kit/build/webpack:/src/data/sequelize.js:15:1)
    at __webpack_require__ (/home/rohitn/react-starter-kit/build/webpack:/webpack/bootstrap 1caeca251472e7f626d5:19:1)
    at Object.<anonymous> (/home/rohitn/react-starter-kit/build/webpack:/src/data/models/index.js:5:1)
    at __webpack_require__ (/home/rohitn/react-starter-kit/build/webpack:/webpack/bootstrap 1caeca251472e7f626d5:19:1)
    at Object.<anonymous> (/home/rohitn/react-starter-kit/build/server.js:1630:71)
    at __webpack_require__ (/home/rohitn/react-starter-kit/build/webpack:/webpack/bootstrap 1caeca251472e7f626d5:19:1)
    at Object.<anonymous> (/home/rohitn/react-starter-kit/build/server.js:826:74)
    at __webpack_require__ (/home/rohitn/react-starter-kit/build/webpack:/webpack/bootstrap 1caeca251472e7f626d5:19:1)
    at Object.<anonymous> (/home/rohitn/react-starter-kit/build/server.js:4273:18)
    at __webpack_require__ (/home/rohitn/react-starter-kit/build/webpack:/webpack/bootstrap 1caeca251472e7f626d5:19:1)
    at /home/rohitn/react-starter-kit/build/webpack:/webpack/bootstrap 1caeca251472e7f626d5:65:1
    at Object.<anonymous> (/home/rohitn/react-starter-kit/build/server.js:71:10)
    at Module._compile (module.js:570:32)
/home/rohitn/react-starter-kit/tools/runServer.js:67
          throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (/home/rohitn/react-starter-kit/tools/runServer.js:53:17)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web@0.0.0 start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rohitn/.npm/_logs/2017-04-13T12_24_08_806Z-debug.log
```

While i have verified the presence of sqlit3 in local node modules, This sails away if I do npm install multiple times, this seems to be a temporary issue with node lts 6.9.10, but issue in scss load is pervasive across all platforms. Verified on windows too.
here goes the repo https://github.com/pulkitnandan/bug-react-starter-kit

Navigation component have scss file present there to check the bug in scss loading. Just include in navigation.js

**Comment by ulani** [comment]
@pulkitnandan   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
