### ISSUE TITLE
UniversalRouter not working on docker release build

### ISSUE THREAD

**Issue by Pomanks** [kriasoft/react-starter-kit#1233]
Hi everyone,

I'm having an issue making the new version of UniversalRouter implementation working with a docker build on release..

The issue is the following one :

```
/app/build/webpack:/src/core/router.js:13
const router = new Router(routes)
               ^
TypeError: __WEBPACK_IMPORTED_MODULE_0_universal_router___default.a is not a constructor
    at Object.<anonymous> (/app/build/webpack:/src/core/router.js:13:16)
    at __webpack_require__ (/app/build/webpack:/webpack/bootstrap 2017df5206f6ff8da90a:19:1)
    at Object.<anonymous> (/app/build/server.js:1335:72)
    at __webpack_require__ (/app/build/webpack:/webpack/bootstrap 2017df5206f6ff8da90a:19:1)
    at Object.<anonymous> (/app/build/server.js:9733:18)
    at __webpack_require__ (/app/build/webpack:/webpack/bootstrap 2017df5206f6ff8da90a:19:1)
    at /app/build/webpack:/webpack/bootstrap 2017df5206f6ff8da90a:65:1
    at Object.<anonymous> (/app/build/server.js:71:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
error Command failed with exit code 1.
```

It works completely fine in development and when building it with the same command found in my `docker-compose.yml` which is `yarn run build -- --release --docker && node build/server.js` but it makes the container to exit on my server..

I'm requiring my routes the same way the boilerplate does and I'm on the branch `feature/react-intl` (merged with Apollo client) just so you know.

If you new some code I'll post it right away. Meanwhile I'll try fixing this.. 😅

**Comment by frenzzy** [comment]
Can you try this import?
```js
import Router from 'universal-router/legacy';
```

**Comment by Ank49** [comment]
Same problem, still tells me it's not a constructor 😔

**Comment by mde17** [comment]
same with mine, __WEBPACK_IMPORTED_MODULE_0_universal_router___default.a is not a constructor

**Comment by frenzzy** [comment]
Is this error for client-side or server-side build?
React Starter Kit version? Node.js version? Universal Router version?
Have you tried this update? https://github.com/kriasoft/react-starter-kit/pull/1403
Also you can try to import this way:
```js
import UniversalRouter from 'universal-router/main.js';
```

**Comment by hxuanhung** [comment]
Fixed for me with: 
```
import UniversalRouter from 'universal-router/main';
```

**Comment by langpavel** [comment]
What is state of this? Looking for tag I can assign. Any suggestion? :-)

**Comment by ulani** [comment]
@Pomanks   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
