### ISSUE TITLE
Error when deploying to Azure app service (Error: Please install sqlite3 package manually)

### ISSUE THREAD

**Issue by jarebb** [kriasoft/react-starter-kit#1235]
Hi all, I had just downloaded this project and trying to deploy the boilerplate to my test app service in Azure using the "yarn deploy" command. I didn't update any file except for the deploy.js on my app service settings. While the deployment is successful, the website is not running, and my app service log stream indicates that there is an error "Please install sqlite3 package manually.". My local is ok and are running properly. Is there anything I could do?
```
2017-04-24T04:16:05  Welcome, you are now connected to log-streaming service.
Mon Apr 24 2017 04:16:20 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
Error: Please install sqlite3 package manually
    at new ConnectionManager (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:25:13)
    at new SqliteDialect (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\sqlite\index.js:12:28)
    at new Sequelize (D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js:233:18)
    at Object.<anonymous> (D:\home\site\wwwroot\webpack:\src\data\sequelize.js:13:19)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:644:69)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:1346:71)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:762:74)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:3456:18)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:65:1
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:71:10)
    at Module._compile (module.js:571:32)
Application has thrown an uncaught exception and is terminated:
Error: Please install sqlite3 package manually
    at new ConnectionManager (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:25:13)
    at new SqliteDialect (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\sqlite\index.js:12:28)
    at new Sequelize (D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js:233:18)
    at Object.<anonymous> (D:\home\site\wwwroot\webpack:\src\data\sequelize.js:13:19)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:644:69)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:1346:71)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:762:74)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:3456:18)
    at __webpack_require__ (D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:19:1)
    at D:\home\site\wwwroot\webpack:\webpack\bootstrap 8daf086329127547eebc:65:1
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:71:10)
    at Module._compile (module.js:571:32)

```

**Comment by seberik** [comment]
I had the same issue but with docker and it was because I mounted my local node_modules on to the container, so maybe make sure that npm/yarn install runs in the container and does not have your local node_modules.

**Comment by langpavel** [comment]
All this kind of dependency problems are around native modules. node-gyp is prerequisity here. If you really using some native module, ensure you have node-gyp otherwise throw away sqlite and potentially sequelize too

**Comment by BertrandGoddard** [comment]
I was facing the same issue and I found a quick fix: replace all 'sqlite' by 'mysql' and put "mysql": "^2.13.0" in your package.json instead of sqlite3. It deployed without any issue on Azure for me.

**Comment by jarebb** [comment]
Thanks @BertrandGoddard @langpavel think there are no work around for this. Will need to remove sqlite completely for azure to work. Thanks guys
