### ISSUE TITLE
Initial build/start failing

### ISSUE THREAD

**Issue by ardalis** [kriasoft/react-starter-kit#1248]
Going through the quickstart instructions on Windows, getting this:

ERROR in ./~/css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[name]-[local]-[hash:base64:5]","minim
ize":false,"discardComments":{"removeAll":true}}!./~/postcss-loader?{"config":"./tools/postcss.config.js"}!./src/components/Navigation/
Navigation.css
    Module build failed: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:387:25)
        at Module._extensions..js (module.js:422:10)
        at Object.require.extensions.(anonymous function) [as .js] (G:\Github\REactApp\node_modules\babel-register\lib\node.js:152:7)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at module.exports (G:\Github\REactApp\tools\postcss.config.js:18:5)
        at G:\Github\REactApp\node_modules\postcss-load-config\index.js:58:50
     @ ./src/components/Navigation/Navigation.css 2:18-155
     @ ./src/components/Navigation/Navigation.js
     @ ./src/components/Header/Header.js
     @ ./src/components/Layout/Layout.js
     @ ./src/routes/home/index.js
     @ ./src/routes/index.js
     @ ./src/router.js
     @ ./src/server.js
     @ multi babel-polyfill ./src/server.js
webpack: Failed to compile.
module.js:341
    throw err;
    ^

Error: Cannot find module 'G:\Github\REactApp\build\server.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
G:\Github\REactApp\tools\runServer.js:74
          throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);
          ^

So far no luck debugging it. Have tried bumping up version of node dependency based on some searching, but that didn't help. Ideas?
@switzer40

**Comment by frenzzy** [comment]
Which node.js version do you use?
```bash
$ node --version
```

**Comment by switzer40** [comment]
I think I am a step further with RSK. We should have read the docs more carefully. My version of node.js was ancient. I downloaded the LTS and now yarn start and yarn run build run OK.
