### ISSUE TITLE
Getting Minified React error on Production Build - RSK Master Branch

### ISSUE THREAD

**Issue by madsithlord** [kriasoft/react-starter-kit#1253]
Production build is running on AWS and we are using **forever** to keep it running. We are seeing this error on the home page when fully reload the page but rest of the pages are working awesome :+1: 

client.e13843d9.js:1 Error: Minified React error #34; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=34 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (http://34.210.33.245:3000/assets/vendor.97ebe2f6.js:1:3162)
    at l (http://34.210.33.245:3000/assets/vendor.97ebe2f6.js:1:5909)
    at h.getPublicInstance (http://34.210.33.245:3000/assets/vendor.97ebe2f6.js:1:219099)
    at getData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8642:44)
    at Object.mountComponent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8460:21)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8538:9)
    at f.performInitialMount (http://34.210.33.245:3000/assets/vendor.97ebe2f6.js:1:203942)
    at f.mountComponent (http://34.210.33.245:3000/assets/vendor.97ebe2f6.js:1:202828)
    at Object.mountComponent (http://34.210.33.245:3000/assets/vendor.97ebe2f6.js:1:33729)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8537:20)

**Comment by frenzzy** [comment]
Are you sure that third party libs don't touches your React DOM nodes?
Which third-party react components do you use, maybe problem there?

**Comment by madsithlord** [comment]
It's a fresh copy of RSK and we haven't installed any 3rd party modules. It happens only one home page when you fully reload the page. May be something to do with getting the information from API on home page?

**Comment by edmondcang** [comment]
@madsithlord Got the same error here too with exactly the same environment but we experience this error very occationally. For example, rendering a certain page can suddently result to this error but it goes back to normal after reloading.

**Comment by edmondcang** [comment]
Turns out our error message is

> t.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

and the problem is in that page we did something like 
````
render() {
  ...
  return a && (
    <b />
  )
}
````
Our solution is simply `return a ? <b /> : 'Loading...'`

**Comment by langpavel** [comment]
Yes, this can look as trouble with build but it's not.
You should be careful with `&&` operator because it can return `null` or `0` or `undefined`.. simple the first falsy value.
This should not happen with React 16 but it will look weird too..

**Comment by ulani** [comment]
@madsithlord   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
