### ISSUE TITLE
yarn test returns invariant violation browser history needs dom

### ISSUE THREAD

**Issue by Falieson** [kriasoft/react-starter-kit#1287]
with a fresh clone of `kriasoft/react-starter-kit` on branch master, after running `yarn` I run `yarn test` and get this error:

```
yarn test v0.24.5
$ mocha
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
/Users/florian/Code/Public/Opensource/Forks/react-starter-kit/kriasoft-rsk/node_modules/invariant/invariant.js:49
    throw error;
    ^

Invariant Violation: Browser history needs a DOM
    at invariant (/Users/florian/Code/Public/Opensource/Forks/react-starter-kit/kriasoft-rsk/node_modules/invariant/invariant.js:42:15)
    at createBrowserHistory (/Users/florian/Code/Public/Opensource/Forks/react-starter-kit/kriasoft-rsk/node_modules/history/createBrowserHistory.js:49:27)
    at Object.<anonymous> (/Users/florian/Code/Public/Opensource/Forks/react-starter-kit/kriasoft-rsk/src/history.js:14:39)
    at Module._compile (module.js:570:32)
```

**Comment by ulani** [comment]
@Falieson   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
