### ISSUE TITLE
Error: Cannot find module 'utf8'

### ISSUE THREAD

**Issue by cmnstmntmn** [kriasoft/react-starter-kit#132]
i cloned the repo with [these updates](https://github.com/kriasoft/react-starter-kit/commit/21e5e7eac92f99838f9a40da7bfeaf6cfeb3c7e9)

`npm install`

`gulp`

**ERROR**

`ctin@C-tins-MacBook-Pro node_modules (master) $ gulp
[11:21:08] Working directory changed to ~
module.js:338
    throw err;
          ^
Error: Cannot find module 'utf8'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ctin/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)`

even after mannualy install the **utf8** module, the error persists

* node: v0.12.4
* npm: 2.10.1

**Comment by koistya** [comment]
Do you use the latest Gulp version?

```
$ gulp -v
[12:12:54] Requiring external module babel/register
[12:12:54] CLI version 3.9.0
[12:12:54] Local version 3.9.0
```

**Comment by cmnstmntmn** [comment]
indeed, i had an older version (;

**Comment by koistya** [comment]
@cmnstmntmn does it work OK after you updated global Gulp package?

**Comment by cmnstmntmn** [comment]
yes, updating gulp fixed the issue, you can close it :+1:
