### ISSUE TITLE
TypeError: action.default is not a function

### ISSUE THREAD

**Issue by charyorde** [kriasoft/react-starter-kit#1323]
my new route
```
export default {
        path: '/vm',
        action() {
                return {
                        title: 'Virtual Server',
                        component: <Layout><Page title='Virtual Server' /></Layout>,
                };
        }
};
```
src/routes/index.js
```
{
      path: '/vm',
      load: () => import('./vm'),
    },
```
Browser navigation to `/vm` gives:
```
TypeError: action.default is not a function
    at context.route.load.then.action (reactapp/build/server.js:2224:68)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```
I'm working off the latest master code. Is it stable enough?

**Comment by frenzzy** [comment]
if you are using `load: () => import('./vm'),` then you should provide a function inside `./vm` file as a default export, in your case:
```js
// vm.js
function action() {
  return {
    title: 'Virtual Server',
    component: <Layout><Page title='Virtual Server' /></Layout>,
  };
}

export default action;
```

**Comment by charyorde** [comment]
With the new structure of `src/routes/index.js`, how do I make use of `action`? I tried this without much luck: 
```
action: () => require('./vm').default,
```
Also, how would you recommend I use `load` with nested path like so `https://github.com/kriasoft/universal-router#how-does-it-look-like`

**Comment by charyorde** [comment]
Literally, how do I achieve this with `load`:
```
function routes() {
  path: '/vm',
  children: [
    {
      path: '/',
      action() {
        const title = 'Virtual Machines'
        return {
          title,
          component: <Layout><Page title={title} /></Layout>,
        };
      }
    },
    {
      path: '/create',
      action() {
        const title = 'Create Virtual Server'
        return {
          title,
          component: <Layout><Page title={title} /></Layout>,
        }
      }
    }
  ]
}

export default action;
```

**Comment by charyorde** [comment]
Okay. This works
```
//my new route
export function create() {
  return {
    title: 'Launch new Virtual Service',
    component: <Layout><Page title='Launch a Virtual Server' /></Layout>,
  }
}

function action() {
  const title = 'Virtual Machines'
  return {
    title,
    component: <Layout><Page title={title} /></Layout>,
  }
}
```
```
// src/routes/index.js
{
      path: '/vm',
      load: () => import('./vm'),
    },
    {
      path: '/vm/create',
      action: require('./vm').create,
    },
```

**Comment by frenzzy** [comment]
If you do not need [code splitting](https://webpack.js.org/guides/code-splitting/) functionality you can specify routes as a simple array:
```js
// src/routes/index.js
const routes = [
  { path: '/', action() {
    return { title: 'Home', component: <HomePage /> };
  } },
  { path: '/about', action() {
    return { title: 'About', component: <AboutPage /> };
  } },
  { path: '/posts', children: [
    { path: '/', action() {
      return { title: 'Posts', component: <PostsPage /> };
    } },
    { path: '/:id', action(context, params) {
      return { title: `Post #${params.id}`, component: <PostPage /> };
    } },
  ] },
  { path: '/users', children: [
    { path: '/', action() {
      return { title: 'Users', component: <UsersPage /> };
    } },
    { path: '/:name', action(context, params) {
      return { title: `User ${params.name}`, component: <UserPage /> };
    } },
    { path: '/:name/edit', action(context, params) {
      return { title: `Edit User ${params.name}`, component: <EditUserPage /> };
    } },
  ] },
];
export default routes;
```
You also can split routes or batch of routes into separate files for convenience:
```js
// src/routes/index.js
const routes = [
  require('./home').default, // route object in a separate file
  { path: '/about', action: require('./about').default }, // only route action in a separate file
  require('./posts').default, // few routes in a separate file
  { path: '/users', children: [
    { path: '/', action() { // do not move anything to a separate file
      return { title: 'Users', component: <UsersPage /> };
    } },
    { path: '/:name', action: require('./user').default }, // move only action
    require('./editUser').default, // move full route
  ] },
];
export default routes;

// home.js
const route = {
  path: '/',
  action() {
    return { title: 'Home', component: <HomePage /> };
  },
};
export default action;

// about.js
function action() {
  return { title: 'About', component: <AboutPage /> };
}
export default action;

// posts.js
const routes = {
  path: '/posts',
  children: [
    { path: '/', action() {
      return { title: 'Posts', component: <PostsPage /> };
    } },
    { path: '/:id', action(context, params) {
      return { title: `Post #${params.id}`, component: <PostPage /> };
    } },
  ],
};
export default routes;

// user.js
function action(context, params) {
  return { title: `User ${params.name}`, component: <UserPage /> };
}
export default action;

// editUser.js
const route = {
  path: '/:name/edit',
  action(context, params) {
    return { title: `Edit User ${params.name}`, component: <EditUserPage /> };
  },
};
export default action;
```
And only if you want to split routes or batch of routes into separate chunks you can use `load`:
```js
const routes = [
  require('./home').default, // just regular require, no code splitting
  { path: '/about', load: () => import('./about') }, // load action of about route asynchronously
  require('./posts').default, // take a look at posts.js below
  { path: '/users', children: [
    { path: '/', action() { // inline route
      return { title: 'Users', component: <UsersPage /> };
    } },
    { path: '/:name', load() { // load action of user route asynchronously
      return import('./user');
    } },
    require('./editUser').default, // sync loading, no code splitting
  ] },
];
export default routes;

// posts.js
const routes = {
  path: '/posts',
  children: [
    { path: '/', action() {
      return { title: 'Posts', component: <PostsPage /> };
    } },
    { path: '/:id', load: () => import('./post') }, // async loading
  ],
};
export default routes;

// post.js
function action(context, params) {
  return { title: `Post #${params.id}`, component: <PostPage /> };
}
export default action;
```

**Comment by charyorde** [comment]
Thanks. Happy to know that I can declare routes in files other than `src/routes/vm/index.js`.
