### ISSUE TITLE
Unexpected token from UglifyJS in webpackHotDevClient.js

### ISSUE THREAD

**Issue by dphrag** [kriasoft/react-starter-kit#1423]
Cloned clean. Works fine in dev mode, run in release (yarn start -- --release), get the following error:

ERROR in client.a8c85054.js from UglifyJs
Unexpected token: punc (() [./tools/lib/webpackHotDevClient.js:21,0][client.a8c85054.js:619,14]
[09:34:24] Failed to compile 'client' after 13701 ms
Error: Compilation failed!
    at Compiler.<anonymous> (C:\CloudNine\Work\temp\tools\start.js:247:16)
    at Compiler.applyPlugins (C:\CloudNine\Work\temp\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (C:\CloudNine\Work\temp\node_modules\webpack\lib\Compiler.js:104:17)
    at onCompiled (C:\CloudNine\Work\temp\node_modules\webpack\lib\Compiler.js:54:18)
    at applyPluginsAsync.err (C:\CloudNine\Work\temp\node_modules\webpack\lib\Compiler.js:514:14)
    at Compiler.applyPluginsAsyncSeries (C:\CloudNine\Work\temp\node_modules\tapable\lib\Tapable.js:195:46)
    at compilation.seal.err (C:\CloudNine\Work\temp\node_modules\webpack\lib\Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (C:\CloudNine\Work\temp\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (C:\CloudNine\Work\temp\node_modules\webpack\lib\Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (C:\CloudNine\Work\temp\node_modules\tapable\lib\Tapable.js:195:46)
error Command failed with exit code 1.

**Comment by frenzzy** [comment]
Node.js version?

**Comment by dphrag** [comment]
Latest, 8.6.0.
Npm 5.4.2
Yarn 1.1.0

**Comment by frenzzy** [comment]
Thank you for bug report, fixed in 07b7da9d87dcc2a960978ae1908df5a2a7374f5c
