### ISSUE TITLE
problem "getting started"

### ISSUE THREAD

**Issue by rayzer42** [kriasoft/react-starter-kit#1435]
```RayzerMac:~ rayzer$ git clone -o react-starter-kit -b master --single-branch \
>       https://github.com/kriasoft/react-starter-kit.git MyApp
Cloning into 'MyApp'...
remote: Counting objects: 5565, done.
remote: Total 5565 (delta 0), reused 0 (delta 0), pack-reused 5565
Receiving objects: 100% (5565/5565), 1.85 MiB | 412.00 KiB/s, done.
Resolving deltas: 100% (3174/3174), done.
RayzerMac:~ rayzer$ cd MyApp
RayzerMac:MyApp rayzer$ yarn install
yarn install v1.2.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 25.79s.
RayzerMac:MyApp rayzer$ yarn start
yarn run v1.2.1
$ babel-node tools/run start
[16:46:58] Starting 'start'...
[16:46:58] Starting 'clean'...
[16:46:58] Finished 'clean' after 79 ms
[16:46:59] Compiling 'client'...
[16:46:59] Compiling 'server'...
Time: 314ms
 1 asset

ERROR in ./src/server.js
Module build failed: TypeError: [BABEL] /Users/rayzer/MyApp/src/server.js: Cannot read property 'allowMutablePropsOnTags' of undefined (While processing: "/Users/rayzer/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js")
    at transformReactConstantElement (/Users/rayzer/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:10:41)
    at loadDescriptor (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:250:14)
    at loadPluginDescriptor (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:284:32)
    at /Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:73:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:72:34)
    at OptionManager.init (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:131:14)
    at manageOptions (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:59:30)
    at loadConfig (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/index.js:20:38)
    at Object.transform (/Users/rayzer/MyApp/node_modules/babel-core/lib/transformation/pipeline.js:48:37)
 @ multi babel-polyfill ./src/server.js
[16:46:59] Failed to compile 'server' after 316 ms
(node:4110) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Compilation failed!
(node:4110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Time: 1034ms
 2 assets

ERROR in ./src/client.js
Module build failed: TypeError: [BABEL] /Users/rayzer/MyApp/src/client.js: Cannot read property 'allowMutablePropsOnTags' of undefined (While processing: "/Users/rayzer/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js")
    at transformReactConstantElement (/Users/rayzer/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:10:41)
    at loadDescriptor (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:250:14)
    at loadPluginDescriptor (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:284:32)
    at /Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:73:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:72:34)
    at OptionManager.init (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:131:14)
    at manageOptions (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:59:30)
    at loadConfig (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/index.js:20:38)
    at Object.transform (/Users/rayzer/MyApp/node_modules/babel-core/lib/transformation/pipeline.js:48:37)
 @ multi babel-polyfill ./tools/lib/webpackHotDevClient ./src/client.js

ERROR in ./tools/lib/webpackHotDevClient.js
Module build failed: TypeError: [BABEL] /Users/rayzer/MyApp/tools/lib/webpackHotDevClient.js: Cannot read property 'allowMutablePropsOnTags' of undefined (While processing: "/Users/rayzer/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js")
    at transformReactConstantElement (/Users/rayzer/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:10:41)
    at loadDescriptor (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:250:14)
    at loadPluginDescriptor (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:284:32)
    at /Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:73:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:72:34)
    at OptionManager.init (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:131:14)
    at manageOptions (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/option-manager.js:59:30)
    at loadConfig (/Users/rayzer/MyApp/node_modules/babel-core/lib/config/index.js:20:38)
    at Object.transform (/Users/rayzer/MyApp/node_modules/babel-core/lib/transformation/pipeline.js:48:37)
 @ multi babel-polyfill ./tools/lib/webpackHotDevClient ./src/client.js
[16:47:00] Failed to compile 'client' after 1032 ms
Error: Compilation failed!
    at Compiler.<anonymous> (/Users/rayzer/MyApp/tools/start.js:47:16)
    at Compiler.applyPlugins (/Users/rayzer/MyApp/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Users/rayzer/MyApp/node_modules/webpack/lib/Compiler.js:104:17)
    at onCompiled (/Users/rayzer/MyApp/node_modules/webpack/lib/Compiler.js:54:18)
    at applyPluginsAsync.err (/Users/rayzer/MyApp/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/Users/rayzer/MyApp/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/Users/rayzer/MyApp/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/Users/rayzer/MyApp/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/Users/rayzer/MyApp/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/Users/rayzer/MyApp/node_modules/tapable/lib/Tapable.js:195:46)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
RayzerMac:MyApp rayzer$ 
```

**Comment by ThomasLaforge** [comment]
Same here!

**Comment by Selectorrr** [comment]
try to use npm instead yarn

**Comment by guyiluz** [comment]
npm  doesn't fix it ..

**Comment by pranspach** [comment]
I had the same problem today with yarn. After removing node_modules, npm did work @Selectorrr . 

npm: 5.3.0
node: v8.5.0
yarn: 1.2.1
macOS: 10.13

I'm just going to proceed with npm for now, but I would like to see the starter pack work out of the box.

**Comment by frenzzy** [comment]
Could you please check is it still actual for the master branch? Thanks

**Comment by FlopiVG** [comment]
I just cloned the master and it works fine.

node:  v8.6.0
yarn: 1.2.1

**Comment by ulani** [comment]
@rayzer42   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
