### ISSUE TITLE
Question: why there is not a `findOne`

### ISSUE THREAD

**Issue by wmzy** [kriasoft/react-starter-kit#1460]
https://github.com/kriasoft/react-starter-kit/blob/e9838eee7f5862208918fe7ef5aa4cbab5b59b3e/src/passport.js#L81

I replace it with `findOne` and obtain an error.
Is it a bug of sequelize or anything I don't know?

**Comment by jorrit** [comment]
What is the error?

**Comment by wmzy** [comment]
The error:
```sh
SequelizeDatabaseError: SQLITE_ERROR: no such column: logins.name
    at Query.formatError (/home/xxx/node_modules/sequelize/lib/dialects/sqlite/query.js:418:16)
    at afterExecute (/home/xxx/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at replacement (/home/xxx/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/home/xxx/node_modules/sqlite3/lib/sqlite3.js:16:21)
From previous event:
    at executeSql (/home/xxx/node_modules/sequelize/lib/dialects/sqlite/query.js:107:21)
From previous event:
    at Database.database.serialize (/home/xxx/node_modules/sequelize/lib/dialects/sqlite/query.js:294:15)
    at resolve (/home/xxx/node_modules/sequelize/lib/dialects/sqlite/query.js:102:21)
From previous event:
    at Query.run (/home/xxx/node_modules/sequelize/lib/dialects/sqlite/query.js:100:12)
    at retry (/home/xxx/node_modules/sequelize/lib/sequelize.js:533:32)
    at /home/xxx/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/home/xxx/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/home/xxx/node_modules/sequelize/lib/sequelize.js:533:14)
From previous event:
    at Sequelize.query (/home/xxx/node_modules/sequelize/lib/sequelize.js:529:8)
    at QueryInterface.select (/home/xxx/node_modules/sequelize/lib/query-interface.js:671:27)
    at Promise.try.then.then.then (/home/xxx/node_modules/sequelize/lib/model.js:1540:34)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Function.findAll (/home/xxx/node_modules/sequelize/lib/model.js:1537:8)
    at Function.findOne (/home/xxx/node_modules/sequelize/lib/model.js:1693:17)
    at /home/xxx/src/passport.js:63:1
    at Generator.next (<anonymous>)
    at step (/home/xxx/build/server.js:2008:191)
    at /home/xxx/build/server.js:2008:437
    at new Promise (<anonymous>)
    at /home/xxx/build/server.js:2008:99
    at findOneOrCreateUser (/home/xxx/build/server.js:2004:18)
    at Strategy.module.exports../src/passport.js.__WEBPACK_IMPORTED_MODULE_1_passport___default.a.use.__WEBPACK_IMPORTED_MODULE_3_passport_cas__.Strategy [as _verify] (/home/xxx/src/passport.js:141:1)
    at /home/xxx/node_modules/passport-cas/index.js:117:42
    at Parser.<anonymous> (/home/xxx/node_modules/xml2js/lib/xml2js.js:384:20)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/home/xxx/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/home/xxx/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/xxx/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/home/xxx/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at SAXParser.write (/home/xxx/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (/home/xxx/node_modules/xml2js/lib/xml2js.js:403:31)
    at Parser.parseString (/home/xxx/node_modules/xml2js/lib/xml2js.js:6:61)
    at exports.parseString (/home/xxx/node_modules/xml2js/lib/xml2js.js:433:19)
    at Strategy._validate (/home/xxx/node_modules/passport-cas/index.js:106:21)
    at IncomingMessage.<anonymous> (/home/xxx/node_modules/passport-cas/index.js:195:25)
    at emitNone (events.js:111:20)
```

The sql sequelize generated:
```sql
SELECT `User`.*, `logins`.`name` AS `logins.name`, `logins`.`key` AS `logins.key` FROM (SELECT `User`.`id`, `User`.`email` FROM `User` AS `User` WHERE `logins`.`name` = 'cas' AND `logins`.`k
ey` = 'xxx' AND ( SELECT `userId` FROM `UserLogin` AS `logins` WHERE (`logins`.`userId` = `User`.`id`) LIMIT 1 ) IS NOT NULL LIMIT 1) AS `User` INNER JOIN `UserLogin` AS `logins` ON `User`.`id` = `logins`.
`userId`;
```

**Comment by ulani** [comment]
@wmzy   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
