### ISSUE TITLE
ERROR in ./src/routes/ui/index.js 

### ISSUE THREAD

**Issue by SPATAN18** [kriasoft/react-starter-kit#1467]
I did a fresh install of react-starter-kit but it keeps failing on npm/yarn start or run start and gives the following output.
I can't seem to understand. Please, help.
`
ERROR in ./src/routes/ui/index.js
Module not found: Error: Can't resolve './ui' in '/home/rossonero/Documents/Devs/Reactor/src/routes/ui'
 @ ./src/routes/ui/index.js 13:0-22
 @ ./src/routes/index.js
 @ ./src/router.js
 @ ./src/server.js
 @ multi @babel/polyfill ./src/server.js
[18:22:22] Failed to compile 'server' after 3954 ms
(node:9753) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Compilation failed!
(node:9753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Time: 4375ms
 15 assets

ERROR in ./src/routes/ui/index.js
Module not found: Error: Can't resolve './ui' in '/home/rossonero/Documents/Devs/Reactor/src/routes/ui'
 @ ./src/routes/ui/index.js 13:0-22
 @ ./src/routes/index.js
 @ ./src/router.js
 @ ./src/client.js
 @ multi @babel/polyfill ./tools/lib/webpackHotDevClient ./src/client.js
[18:22:22] Failed to compile 'client' after 4373 ms
Error: Compilation failed!
    at Compiler.<anonymous> (/home/rossonero/Documents/Devs/Reactor/tools/start.js:247:16)
    at Compiler.applyPlugins (/home/rossonero/Documents/Devs/Reactor/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/home/rossonero/Documents/Devs/Reactor/node_modules/webpack/lib/Compiler.js:104:17)
    at onCompiled (/home/rossonero/Documents/Devs/Reactor/node_modules/webpack/lib/Compiler.js:54:18)
    at applyPluginsAsync.err (/home/rossonero/Documents/Devs/Reactor/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/home/rossonero/Documents/Devs/Reactor/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/home/rossonero/Documents/Devs/Reactor/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/home/rossonero/Documents/Devs/Reactor/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/home/rossonero/Documents/Devs/Reactor/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/home/rossonero/Documents/Devs/Reactor/node_modules/tapable/lib/Tapable.js:195:46)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by frenzzy** [comment]
Open `./src/routes/ui/index.js`, find import/require of `./ui`, change it to correct one.
