### ISSUE TITLE
action.default is not a function

### ISSUE THREAD

**Issue by kaiwen1811** [kriasoft/react-starter-kit#1507]
when i first load the page with echarts, it's useful.when i refresh the page, it shows this error.

**Comment by langpavel** [comment]
Without more context this is useless issue.
Is this happening in router? or in external library?
Did you mix `import` with `require`? (Note, if you `require`, you should ask for `default` prop of import..)

**Comment by damiangreen** [comment]
Here's my stack trace

But it manifests itself as 
  TypeError: action.default is not a function
```
  - router.js:18
    code/src/router.js:18:1
```

which is line 

`  .then(action => action.default(context, params));`

```

ReferenceError: document is not defined
    at detect (code\node_modules\zrender\lib\core\env.js:129:24)
    at Object.<anonymous> (code\node_modules\zrender\lib\core\env.js:43:9)
    at Module._compile (module.js:649:30)
    at Module._compile (code\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:660:10)
    at Object.newLoader [as .js] (code\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (code\node_modules\zrender\lib\zrender.js:3:11)
    at Module._compile (module.js:649:30)
    at Module._compile (code\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:660:10)
    at Object.newLoader [as .js] (code\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (code\node_modules\echarts\lib\echarts.js:5:15)
```

Note i'm using echarts for react
```
const EchartsReact =
  typeof document !== 'undefined' && require('echarts-for-react').default; // eslint-disable-line

...
 {EchartsReact &&
            this.props.option && (
              <EchartsReact
                option={option}
                style={{
                  height: '100%',
                  width: '100%',
                }}
              />
            )}
```

**Comment by langpavel** [comment]
@damiangreen I'm pretty sure that this happens on server only?
Please, consider use of something like `<NoSSR>` component (PR welcome)
or fine tune code to work without need of client APIs (you can use browser APIs only in `componentDidMount`)

**Comment by damiangreen** [comment]
Thanks for that. How exactly could i tel lif the error happens on the server only?

I actually tracked the error down to this line in my code.. Just instantiating a gradient object from the lib, so not sure how to solve that one...
```
const dattoHorizontalGradient =  new echarts.graphic.LinearGradient(0, 0.5, 1, 0.5, [
      {
        offset: 0,
        color: '#578d8b',
      },
      {
        offset: 1,
        color: '#456e94',
      },
    ]);
```

**Comment by langpavel** [comment]
@damiangreen try add `try` / `catch` block and write error to console.
Also try dynamic (promise based) `import`. Error is not with `LinearGradient` but must be somewhere else..
