### ISSUE TITLE
Route Path Error

### ISSUE THREAD

**Issue by mzparulina** [kriasoft/react-starter-kit#159]
Clicked Login then ask question link near footer, clicked the back button then i got error

TypeError: Cannot read property 'path' of null
   at Object.ID_1 (/Users/poline/git/MyApp/build/webpack:/src/stores/AppStore.js:69:26)
   at Dispatcher.$Dispatcher_invokeCallback (/Users/poline/git/MyApp/node_modules/flux/lib/Dispatcher.js:220:35)
   at Dispatcher.dispatch (/Users/poline/git/MyApp/node_modules/flux/lib/Dispatcher.js:195:14)
   at /Users/poline/git/MyApp/build/webpack:/src/core/Database.js:45:18
   at run (/Users/poline/git/MyApp/build/webpack:/~/babel-core/~/core-js/modules/es6.promise.js:89:1)
   at /Users/poline/git/MyApp/build/webpack:/~/babel-core/~/core-js/modules/es6.promise.js:100:1
   at process._tickCallback (node.js:419:13)
![screen shot 2015-07-01 at 11 36 59](https://cloud.githubusercontent.com/assets/5786822/8447062/8744264a-1fe5-11e5-8957-9e4fdac8adb0.png)
##

**Comment by mychaelgo** [comment]
@mzparulina  change code to this https://github.com/kriasoft/react-starter-kit/pull/151

**Comment by ulani** [comment]
@mzparulina   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
