### ISSUE TITLE
Issue with babel preset-stage-2 

### ISSUE THREAD

**Issue by Bogdaan** [kriasoft/react-starter-kit#1607]
```
ERROR in ./tools/lib/webpackHotDgeevClient.js
Module build failed: Error: [BABEL] rsk/tools/lib/webpackHotDevClient.js: The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 (While processing: "rsk/node_modules/@babel/preset-stage-2/lib/index.js")
    at rsk/node_modules/@babel/preset-stage-2/lib/index.js:107:11
    at rsk/node_modules/@babel/helper-plugin-utils/lib/index.js:18:12
    at rsk/node_modules/@babel/core/lib/config/full.js:172:14
    at cachedFunction (rsk/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPresetDescriptor (rsk/node_modules/@babel/core/lib/config/full.js:243:63)
    at rsk/node_modules/@babel/core/lib/config/full.js:68:19
    at Array.map (<anonymous>)
    at recurseDescriptors (rsk/node_modules/@babel/core/lib/config/full.js:66:36)
    at loadFullConfig (rsk/node_modules/@babel/core/lib/config/full.js:112:6)
    at rsk/node_modules/@babel/core/lib/transform.js:28:33
 @ multi @babel/polyfill ./tools/lib/webpackHotDevClient ./src/client.js
```

Issue: https://github.com/babel/babel/issues/7786

**Comment by Bogdaan** [comment]
How to reproduce:
```bash
git clone -o react-starter-kit -b master --single-branch https://github.com/kriasoft/react-starter-kit.git MyApp && \
cd MyApp &&\ 
yarn install &&\ 
yarn start
```

**Comment by tim-soft** [comment]
roll back your babel libs to beta.44, so remove the `^`'s from `package.json` and reinstall packages
`"@babel/polyfill": "7.0.0-beta.44",` etc

**Comment by piglovesyou** [comment]
I believe https://github.com/kriasoft/react-starter-kit/pull/1673 solved this issue. Please reopen it if it didn't .
