### ISSUE TITLE
`npm start` loads tests files if routes are dynamic

### ISSUE THREAD

**Issue by goldylucks** [kriasoft/react-starter-kit#1618]
I have `component.test.js` file in my routes folder, and running `npm start` loads that file (and crashes)
I tried renaming the test file to `abc.test.js` to make sure no component is requiring it, still same error.

The test file resides in a route folder, that has a dynamic `:module` param:

```
    {
      path: '/savoring-your-child/:module',
      load: () => import(/* webpackChunkName: 'savoringYourChildModule' */ './savoringYourChildModule'),
    },
```

Commenting out that route fixes the error, but obviously it's not an option ;)

As you'll see in the error log below, the error comes from the `/savoring-your-child/index.js` files, which lazily loads module from that folder:

```
async function action({ params, path }) {
  const module = await import(`./${params.module}.js`)
```

So my guess is if webpack detects a dynamic import, it preloads the entire folder.

The expected behavior would be to skip the following cases:
1. `.spec.js` files
1. `.test.js` files
1. `__tests__` folder
1. `__mocks__` folder

is there a way to accomplish that?

<details>
<summary>
Log
</summary>

```
[./src/client.js] ./src/client.js 9.13 kB {23} [built]
[./src/router.js] ./src/router.js 494 bytes {23} [built]
[./tools/lib/webpackHotDevClient.js] ./tools/lib/webpackHotDevClient.js 1.14 kB {23} [built]
    + 1552 hidden modules

ERROR in ./test/TestWrapper.js
Module parse failed: Unexpected token (11:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       <App context={{}}>
|         <Layout path="/test">
|           {this.props.children}
 @ ./src/routes/savoringYourChildModule/SavoringYourChildModule.test.js 14:0-48
 @ ./src/routes/savoringYourChildModule lazy ^\.\/.*\.js$
 @ ./src/routes/savoringYourChildModule/index.js
 @ ./src/routes/routes.js
 @ ./src/routes/index.js
 @ ./src/router.js
 @ ./src/client.js
 @ multi @babel/polyfill ./tools/lib/webpackHotDevClient ./src/client.js
ℹ ｢wdm｣: Failed to compile.
Error: Compilation failed!
    at Compiler.<anonymous> (/home/goldy/apps/adamgoldman.me/tools/start.js:49:16)
    at Compiler.applyPlugins (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:105:17)
    at onCompiled (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:55:18)
    at applyPluginsAsync.err (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:195:46)
Error: Compilation failed!
    at Compiler.<anonymous> (/home/goldy/apps/adamgoldman.me/tools/start.js:49:16)
    at Compiler.applyPlugins (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:105:17)
    at onCompiled (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:55:18)
    at applyPluginsAsync.err (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/home/goldy/apps/adamgoldman.me/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/home/goldy/apps/adamgoldman.me/node_modules/tapable/lib/Tapable.js:195:46)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.

```
</details>

**Comment by frenzzy** [comment]
What about specific pattern for such files? For example
```js
import(`./${name}.dynamic.js`)
// or
import(`./dynamic/${name}.js`)
// etc.
```

**Comment by goldylucks** [comment]
Not sure I understand ..
what do you mean by "such files"?

All the dynamic lazy loaded routes?

To clarify:
1. I'm using the same code as this repo's source code
1. the problem is not with the dynamically imported files, but with test files that are stored in a folder that contains dynamically imported files.

Thank you for your help @frenzzy !

**Comment by ulani** [comment]
@goldylucks   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
