### ISSUE TITLE
`gulp deploy` fails

### ISSUE THREAD

**Issue by marclundgren** [kriasoft/react-starter-kit#163]
```
☁  build [master] gulp deploy
[09:08:26] Requiring external module babel-core/register
[09:08:26] Working directory changed to ~/Dev/MyApp
[09:08:27] Using gulpfile ~/Dev/MyApp/gulpfile.babel.js
[09:08:27] Starting 'deploy'...
[09:08:27] 'deploy' errored after 1.4 ms
[09:08:27] TypeError: Object [object Object] has no method 'isAbsolute'
    at push (/Users/marc/Dev/MyApp/node_modules/git-push/index.js:17:13)
    at Gulp.<anonymous> (/Users/marc/Dev/MyApp/gulpfile.babel.js:173:3)
    at module.exports (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/marc/.nvm/v0.10.38/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3
☁  build [master] gulp deploy --production
[09:08:33] Requiring external module babel-core/register
[09:08:33] Working directory changed to ~/Dev/MyApp
[09:08:33] Using gulpfile ~/Dev/MyApp/gulpfile.babel.js
[09:08:33] Starting 'deploy'...
[09:08:33] 'deploy' errored after 1.15 ms
[09:08:33] TypeError: Object [object Object] has no method 'isAbsolute'
    at push (/Users/marc/Dev/MyApp/node_modules/git-push/index.js:17:13)
    at Gulp.<anonymous> (/Users/marc/Dev/MyApp/gulpfile.babel.js:173:3)
    at module.exports (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/marc/Dev/MyApp/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/marc/.nvm/v0.10.38/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3
☁  build [master]
```

**Comment by marclundgren** [comment]
I was on an older version of node
```
v0.10.38
```
Updating to `0.12.6` solved my problem.
