### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by nsisodiya** [kriasoft/react-starter-kit#166]
npm start is not working, on my macbook air. I have done npm install and there is no problem with npm install. I am using nvm and io.js  !
```
$ npm start
> @ start /Users/narendrasisodiya/Desktop/play/react-starter-kit
> node server.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/narendrasisodiya/Desktop/play/react-starter-kit/server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:948:3

npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/narendrasisodiya/.nvm/versions/io.js/v2.3.3/bin/iojs" "/Users/narendrasisodiya/.nvm/versions/io.js/v2.3.3/bin/npm" "start"
npm ERR! node v2.3.3
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node server.js'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by nsisodiya** [comment]
sorry, its working, I forget to have gulp build..
Sorry !!
