### ISSUE TITLE
Can't run outside project folder when build at production mode

### ISSUE THREAD

**Issue by tk1cntt** [kriasoft/react-starter-kit#1667]
1. Clone project to my pc
2. Run `yarn run build -- --release`
3. Goto build folder run `node server.js`. It's OK
4. Copy build folder to /tmp
5. Run `node server.js`

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/m.tinvang.com.vn/server.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by mgazisalik** [comment]
I am having the same issue. Also, I tried to clone this repo from scratch but still got this issue. 

@adrienlo node_modules does not required in production mode.

**Comment by ulani** [comment]
@tk1cntt   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
