### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by kalmndo** [kriasoft/react-starter-kit#1688]
> TypeError: Object(...) is not a function
    at Module../src/routes/register/Register.js (/home/kalmndo/Project/nuo/src/routes/register/Register.js:67:1)
    at __webpack_require__ (/home/kalmndo/Project/nuo/webpack/bootstrap:685:1)
    at fn (/home/kalmndo/Project/nuo/webpack/bootstrap:56:1)
    at Module../src/routes/register/index.js (/home/kalmndo/Project/nuo/build/chunks/register.js:270:67)
    at __webpack_require__ (/home/kalmndo/Project/nuo/webpack/bootstrap:685:1)
    at fn (/home/kalmndo/Project/nuo/webpack/bootstrap:56:1)
    at <anonymous>

```javascript
import { Button, Form, Icon, Input } from 'antd';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import React from 'react';
import { compose, graphql } from 'react-apollo';
import { gql } from 'graphql-tag';
import s from './Register.scss';

const FormItem = Form.Item;

class Register extends React.Component {
  state = {
    email: '',
    password: '',
  };

  onSubmit = () => {
    console.log(this.setState);
  };

  onChange = e => {
    const { name, value } = e.target;
    this.setState({ [name]: value });
  };

  render() {
    const { email, password } = this.state;

    return (
      <div>
        <Form className="login-form">
          <FormItem>
            <Input
              name="email"
              onChange={this.onChange}
              value={email}
              prefix={<Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />}
              placeholder="Email"
            />
          </FormItem>
          <FormItem>
            <Input
              name="password"
              onChange={this.onChange}
              value={password}
              prefix={<Icon type="lock" style={{ color: 'rgba(0,0,0,.25)' }} />}
              type="password"
              placeholder="Password"
            />
          </FormItem>
          <FormItem>
            <Button
              onClick={this.onSubmit}
              type="primary"
              htmlType="submit"
              className="login-form-button"
            >
              Register
            </Button>
            Or <a href="">login now!</a>
          </FormItem>
        </Form>
      </div>
    );
  }
}

const registerMutation = gql`
  mutation($email: String!, $password: String!) {
    register(email: "$email", password: "$password")
  }
`;

export default compose(
  withStyles(s),
  graphql(registerMutation),
)(Register);
```
and after i reload the page it's getting error in the action.default is not a function

**Comment by ACPK** [comment]
@kalmndo - If I may ask, how did you about solving the issue?
