### ISSUE TITLE
Error on latest version (master), on npm start

### ISSUE THREAD

**Issue by Renaud009** [kriasoft/react-starter-kit#1689]
Cloned the repo today (master branch), installed dependencies then ran npm start

### System:
node v11.2.0
npm v6.4.1
Windows 10 WSL: Ubuntu 16

### Error:
/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/full.js:135
    throw e;
    ^

Error: [BABEL] /PATH/react-starter-kit2/tools/run.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".

If you want the same configuration as before:

{
  "plugins": [
    // Stage 2
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-function-sent",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-proposal-numeric-separator",
    "@babel/plugin-proposal-throw-expressions",

    // Stage 3
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta",
    ["@babel/plugin-proposal-class-properties", { "loose": false }],
    "@babel/plugin-proposal-json-strings"
  ]
}

If you're using the same configuration across many separate projects,
keep in mind that you can also create your own custom presets with
whichever plugins and presets you're looking to use.

module.exports = function() {
  return {
    plugins: [
      require("@babel/plugin-syntax-dynamic-import"),
      [require("@babel/plugin-proposal-decorators"), { "legacy": true }],
      [require("@babel/plugin-proposal-class-properties"), { "loose": false }],
    ],
    presets: [
      // ...
    ],
  };
};
 (While processing: "/PATH/react-starter-kit2/node_modules/@babel/preset-stage-2/lib/index.js")
    at _default (/PATH/react-starter-kit2/node_modules/@babel/preset-stage-2/lib/index.js:9:9)
    at loadDescriptor (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/full.js:235:63)
    at config.presets.reduce (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/full.js:77:21)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/full.js:74:38)
    at loadFullConfig (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/full.js:108:6)
    at loadOptions (/PATH/react-starter-kit2/node_modules/@babel/core/lib/config/index.js:27:36)
    at OptionManager.init (/PATH/react-starter-kit2/node_modules/@babel/core/lib/index.js:231:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /PATH/.npm/_logs/2018-12-04T20_46_12_617Z-debug.log

**Comment by Renaud009** [comment]
This PR fixed the issue while also updating depencies, ty.
