### ISSUE TITLE
Module parse failed: Unexpected token (21:16)

### ISSUE THREAD

**Issue by shwetakilledar** [kriasoft/react-starter-kit#1708]
I have added the required plugins in babel.config and webpack.config but getting following issue.

`
```
> web@0.0.0 start C:\Users\XYZ\Desktop\boilerplate\react-starter-kit
> babel-node tools/run start

[04:54:26] Starting 'start'...
[04:54:26] Starting 'clean'...
[04:54:26] Finished 'clean' after 25 ms
[04:54:26] Compiling 'client'...
[04:54:26] Compiling 'server'...
Time: 3100ms
Built at: 2019-01-26 04:54:30
    Asset     Size  Chunks             Chunk Names
server.js  203 KiB  server  [emitted]  server
Entrypoint server = server.js

ERROR in ./src/routes/index.js 21:16
### Module parse failed: Unexpected token (21:16)
You may need an appropriate loader to handle this file type.
|   children: [{
|     path: '',
>     load: () => import(
|     /* webpackChunkName: 'home' */
|     './home')
 @ ./src/router.js 10:0-30 11:35-41
 @ ./src/server.js
 @ multi @babel/polyfill ./src/server.js
[04:54:30] Failed to compile 'server' after 3106 ms
(node:2464) UnhandledPromiseRejectionWarning: Error: Compilation failed!
    at compiler.hooks.done.tap.stats (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\tools/start.js:48:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Watching.js:97:28)    at compiler.emitRecords.err (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Watching.js:72:19)
    at Compiler.emitRecords (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Compiler.js:449:39)
    at compiler.emitAssets.err (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Compiler.js:435:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
(node:2464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Time: 3743ms
Built at: 2019-01-26 04:54:30
              Asset      Size   Chunks             Chunk Names
asset-manifest.json  82 bytes           [emitted]
          client.js   123 KiB   client  [emitted]  client
   vendors.chunk.js  4.17 MiB  vendors  [emitted]  vendors
Entrypoint client = vendors.chunk.js client.js

ERROR in ./src/routes/index.js 22:13
Module parse failed: Unexpected token (22:13)
You may need an appropriate loader to handle this file type.
|     path: '',
|     load: function load() {
>       return import(
|       /* webpackChunkName: 'home' */
|       './home');
 @ ./src/router.js 10:0-30 11:35-41
 @ ./src/client.js
 @ multi @babel/polyfill ./tools/lib/webpackHotDevClient ./src/client.js
[04:54:30] Failed to compile 'client' after 3750 ms
Error: Compilation failed!
    at compiler.hooks.done.tap.stats (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\tools/start.js:48:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Watching.js:97:28)    at compiler.emitRecords.err (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Watching.js:72:19)
    at Compiler.emitRecords (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Compiler.js:449:39)
    at compiler.emitAssets.err (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\webpack\lib\Compiler.js:435:14)
    at _promise0.then._result0 (eval at create (C:\Users\XYZ\Desktop\boilerplate\react-starter-kit\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:13:1)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XYZ\AppData\Roaming\npm-cache\_logs\2019-01-26T09_54_30_809Z-debug.log
`
```

**Comment by snovosel** [comment]
can you post your babel.config

**Comment by shwetakilledar** [comment]
```
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
    '@babel/preset-flow',
    '@babel/preset-react',
  ],
  plugins: [
    // Stage 2
    ['relay', {"schema":"./schema.json"}],
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-throw-expressions',

    // Stage 3
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-syntax-import-meta',
    ['@babel/plugin-proposal-class-properties', { loose: false }],
    '@babel/plugin-proposal-json-strings',
  ]
```

**Comment by snovosel** [comment]
@shwetakilledar do you happen to have files in your solution that end in '.home' ? If so, this error may be a webpack issue.

**Comment by vincenthirtz** [comment]
I have the same problem and when i delete home route, the error appears to the next route and the next...

**Comment by UlasenkaUladzislau** [comment]
I have the same problem after removing my old package-lock.json

**Comment by UlasenkaUladzislau** [comment]
@vincenthirtz @shwetakilledar I have this problem with "eslint": "4.19.1", with eslint version 5+ it's working.

**Comment by ulani** [comment]
@shwetakilledar   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
