### ISSUE TITLE
Invariant violation when updating from previous version to react 16

### ISSUE THREAD

**Issue by orwell1984** [kriasoft/react-starter-kit#1712]
I am running application that is based off this project - code is at https://github.com/orwell1984/explorer/tree/i18n

After updating to React 16 I get error as follows:

```Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at invariant (/Users/owrell/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:15)
    at ReactDOMServerRenderer.render (/Users/owrell/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:7)
    at ReactDOMServerRenderer.read (/Users/owrell/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3131:29)
    at Object.renderToString (/Users/owrell/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:27)
    at render (/Users/owrell/explorer/build/client/webpack:/server.js:67:42)
    at Object._callee$ (/Users/owrell/explorer/build/client/webpack:/routes/index.js:46:12)
    at tryCatch (/Users/owrell/explorer/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/owrell/explorer/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/owrell/explorer/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/owrell/explorer/build/client/server.js:8847:103)
    at _next (/Users/owrell/explorer/build/client/server.js:8849:194)
```

There does not seem to be anything wrong with https://github.com/orwell1984/explorer/blob/master/client/src/routes/index.js#L46

Can you please advice how to fix this one? @piglovesyou

**Comment by piglovesyou** [comment]
Oh why to me 😮

**Comment by orwell1984** [comment]
@piglovesyou  I saw you answering on someone's issue ;) No pressure, obviously, it's entirely up to you if you have time to look into this.

**Comment by piglovesyou** [comment]
I compiled `4579cac04145cbe74215f1f62761e79018b826c3` of `git@github.com:orwell1984/explorer.git` and I'm seeing errors such as:

* `ReferenceError: cosnole is not defined`
* `Error: This API has been removed. If you're looking for this functionality in Babel 7, you should import the '@babel/helper-module-imports' module and use the functions exposed  from that module, such as 'addNamed' or 'addDefault'.`

which are not what you reported. Why don't you start fixing these errors first? And basically this issue is not of react-starter-kit, I believe.

**Comment by orwell1984** [comment]
`runServer` is not the way I run the project when seeing this. `npm run build` -> `npx pm2 start ecosystem.config.js` -> client.log when a request hits the page.

**Comment by orwell1984** [comment]
Here is a build failing with this example https://travis-ci.org/orwell1984/explorer/builds/494032199

**Comment by orwell1984** [comment]
For future reference - this issue was cause by outdated `isomorphic-style-loader` version, no idea how tho.
