### ISSUE TITLE
EPEERINVALID error on npm install

### ISSUE THREAD

**Issue by nathaniellee** [kriasoft/react-starter-kit#196]
I get the following anytime I try to npm install.

```
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-react@3.2.1 wants eslint@>=0.8.0 || ~1.0.0-rc-0
npm ERR! peerinvalid Peer eslint-loader@0.14.2 wants eslint@0.21 - 0.24 || ~1.0.0-rc-0
```

LOG

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.12.1
3 info using node@v0.12.6
4 verbose readDependencies loading dependencies from /Users/nlee/Projects/hilu-react-fullstack/package.json
5 verbose install where, deps [ '/Users/nlee/Projects/hilu-react-fullstack',
5 verbose install   [ 'babel',
5 verbose install     'classnames',
5 verbose install     'eventemitter3',
5 verbose install     'express',
5 verbose install     'fastclick',
5 verbose install     'fbjs',
5 verbose install     'flux',
5 verbose install     'front-matter',
5 verbose install     'jade',
5 verbose install     'lodash',
5 verbose install     'normalize.css',
5 verbose install     'react',
5 verbose install     'react-dom',
5 verbose install     'react-routing',
5 verbose install     'source-map-support',
5 verbose install     'superagent',
5 verbose install     'autoprefixer-core',
5 verbose install     'babel-eslint',
5 verbose install     'babel-loader',
5 verbose install     'browser-sync',
5 verbose install     'css-loader',
5 verbose install     'csscomb',
5 verbose install     'cssnext',
5 verbose install     'del',
5 verbose install     'eslint',
5 verbose install     'eslint-loader',
5 verbose install     'eslint-plugin-react',
5 verbose install     'git-push',
5 verbose install     'gulp',
5 verbose install     'gulp-changed',
5 verbose install     'gulp-if',
5 verbose install     'gulp-load-plugins',
5 verbose install     'gulp-rename',
5 verbose install     'gulp-size',
5 verbose install     'gulp-util',
5 verbose install     'jest-cli',
5 verbose install     'minimist',
5 verbose install     'mkdirp',
5 verbose install     'postcss',
5 verbose install     'postcss-loader',
5 verbose install     'postcss-nested',
5 verbose install     'psi',
5 verbose install     'run-sequence',
5 verbose install     'style-loader',
5 verbose install     'url-loader',
5 verbose install     'webpack' ] ]
6 verbose install where, peers [ '/Users/nlee/Projects/hilu-react-fullstack', [] ]
7 verbose installManyTop reading for lifecycle /Users/nlee/Projects/hilu-react-fullstack/package.json
8 info preinstall @
9 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/autoprefixer-core/package.json
10 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel/package.json
11 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-core/package.json
12 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-eslint/package.json
13 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-loader/package.json
14 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/browser-sync/package.json
15 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/classnames/package.json
16 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/css-loader/package.json
17 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/csscomb/package.json
18 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/cssnext/package.json
19 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/del/package.json
20 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eslint/package.json
21 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eslint-loader/package.json
22 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eslint-plugin-react/package.json
23 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eventemitter3/package.json
24 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/express/package.json
25 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/fastclick/package.json
26 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/fbjs/package.json
27 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/file-loader/package.json
28 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/flux/package.json
29 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/front-matter/package.json
30 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/git-push/package.json
31 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp/package.json
32 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-changed/package.json
33 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-if/package.json
34 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-load-plugins/package.json
35 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-rename/package.json
36 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-size/package.json
37 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-util/package.json
38 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/jade/package.json
39 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/jest-cli/package.json
40 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/lodash/package.json
41 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/minimist/package.json
42 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/mkdirp/package.json
43 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/normalize.css/package.json
44 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/postcss/package.json
45 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/postcss-loader/package.json
46 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/postcss-nested/package.json
47 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/psi/package.json
48 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/react/package.json
49 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/react-dom/package.json
50 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/react-routing/package.json
51 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/run-sequence/package.json
52 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/source-map-support/package.json
53 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/style-loader/package.json
54 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/superagent/package.json
55 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/url-loader/package.json
56 verbose installManyTop reading scoped package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/webpack/package.json
57 info package.json csscomb@3.1.8 No license field.
58 info package.json fastclick@1.0.6 No license field.
59 info package.json flux@2.0.3 license should be a valid SPDX license expression
60 info package.json git-push@0.1.1 No license field.
61 info package.json gulp-if@1.2.5 No license field.
62 info package.json gulp-rename@1.2.2 No license field.
63 verbose readDependencies loading dependencies from /Users/nlee/Projects/hilu-react-fullstack/package.json
64 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/autoprefixer-core/package.json
65 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel/package.json
66 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-core/package.json
67 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-eslint/package.json
68 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-loader/package.json
69 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/browser-sync/package.json
70 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/classnames/package.json
71 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/css-loader/package.json
72 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/csscomb/package.json
73 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/cssnext/package.json
74 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/del/package.json
75 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eslint/package.json
76 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eslint-loader/package.json
77 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eslint-plugin-react/package.json
78 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/eventemitter3/package.json
79 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/express/package.json
80 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/fastclick/package.json
81 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/fbjs/package.json
82 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/file-loader/package.json
83 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/flux/package.json
84 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/front-matter/package.json
85 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/git-push/package.json
86 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp/package.json
87 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-changed/package.json
88 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-if/package.json
89 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-load-plugins/package.json
90 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-rename/package.json
91 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-size/package.json
92 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/gulp-util/package.json
93 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/jade/package.json
94 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/jest-cli/package.json
95 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/lodash/package.json
96 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/minimist/package.json
97 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/mkdirp/package.json
98 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/normalize.css/package.json
99 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/postcss/package.json
100 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/postcss-loader/package.json
101 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/postcss-nested/package.json
102 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/psi/package.json
103 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/react/package.json
104 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/react-dom/package.json
105 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/react-routing/package.json
106 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/run-sequence/package.json
107 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/source-map-support/package.json
108 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/style-loader/package.json
109 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/superagent/package.json
110 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/url-loader/package.json
111 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/webpack/package.json
112 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/babel/package.json
113 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/babel-external-helpers/package.json
114 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/babel-node/package.json
115 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/babel-plugin/package.json
116 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/browser-sync/package.json
117 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/csscomb/package.json
118 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/cssnext/package.json
119 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/eslint/package.json
120 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/gulp/package.json
121 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/jade/package.json
122 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/jest/package.json
123 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/mkdirp/package.json
124 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/psi/package.json
125 verbose targetResolver reading package data from /Users/nlee/Projects/hilu-react-fullstack/node_modules/.bin/webpack/package.json
126 verbose already installed skipping react-routing@0.0.4 /Users/nlee/Projects/hilu-react-fullstack
127 verbose already installed skipping source-map-support@0.3.2 /Users/nlee/Projects/hilu-react-fullstack
128 verbose already installed skipping superagent@1.3.0 /Users/nlee/Projects/hilu-react-fullstack
129 verbose already installed skipping autoprefixer-core@^5.2.1 /Users/nlee/Projects/hilu-react-fullstack
130 verbose already installed skipping babel-eslint@^4.0.5 /Users/nlee/Projects/hilu-react-fullstack
131 verbose already installed skipping babel-loader@^5.3.2 /Users/nlee/Projects/hilu-react-fullstack
132 verbose already installed skipping browser-sync@^2.8.2 /Users/nlee/Projects/hilu-react-fullstack
133 verbose already installed skipping css-loader@^0.15.6 /Users/nlee/Projects/hilu-react-fullstack
134 verbose already installed skipping csscomb@^3.1.8 /Users/nlee/Projects/hilu-react-fullstack
135 verbose already installed skipping cssnext@^1.8.3 /Users/nlee/Projects/hilu-react-fullstack
136 verbose already installed skipping del@^1.2.0 /Users/nlee/Projects/hilu-react-fullstack
137 verbose already installed skipping eslint@^1.0.0 /Users/nlee/Projects/hilu-react-fullstack
138 verbose already installed skipping eslint-loader@^0.14.2 /Users/nlee/Projects/hilu-react-fullstack
139 verbose already installed skipping eslint-plugin-react@^3.2.0 /Users/nlee/Projects/hilu-react-fullstack
140 verbose already installed skipping git-push@^0.1.1 /Users/nlee/Projects/hilu-react-fullstack
141 verbose already installed skipping gulp@^3.9.0 /Users/nlee/Projects/hilu-react-fullstack
142 verbose already installed skipping gulp-changed@^1.3.0 /Users/nlee/Projects/hilu-react-fullstack
143 verbose already installed skipping gulp-if@^1.2.5 /Users/nlee/Projects/hilu-react-fullstack
144 verbose already installed skipping gulp-load-plugins@^1.0.0-rc.1 /Users/nlee/Projects/hilu-react-fullstack
145 verbose already installed skipping gulp-rename@^1.2.2 /Users/nlee/Projects/hilu-react-fullstack
146 verbose already installed skipping gulp-size@^1.2.3 /Users/nlee/Projects/hilu-react-fullstack
147 verbose already installed skipping gulp-util@^3.0.6 /Users/nlee/Projects/hilu-react-fullstack
148 verbose already installed skipping jest-cli@^0.4.18 /Users/nlee/Projects/hilu-react-fullstack
149 verbose already installed skipping minimist@^1.1.2 /Users/nlee/Projects/hilu-react-fullstack
150 verbose already installed skipping mkdirp@^0.5.1 /Users/nlee/Projects/hilu-react-fullstack
151 verbose already installed skipping postcss@^4.1.16 /Users/nlee/Projects/hilu-react-fullstack
152 verbose already installed skipping postcss-loader@^0.5.1 /Users/nlee/Projects/hilu-react-fullstack
153 verbose already installed skipping postcss-nested@^0.3.2 /Users/nlee/Projects/hilu-react-fullstack
154 verbose already installed skipping psi@^1.0.6 /Users/nlee/Projects/hilu-react-fullstack
155 verbose already installed skipping run-sequence@^1.1.2 /Users/nlee/Projects/hilu-react-fullstack
156 verbose already installed skipping style-loader@^0.12.3 /Users/nlee/Projects/hilu-react-fullstack
157 verbose already installed skipping url-loader@^0.5.6 /Users/nlee/Projects/hilu-react-fullstack
158 verbose already installed skipping webpack@^1.11.0 /Users/nlee/Projects/hilu-react-fullstack
159 verbose already installed skipping babel@5.8.21 /Users/nlee/Projects/hilu-react-fullstack
160 verbose already installed skipping classnames@2.1.3 /Users/nlee/Projects/hilu-react-fullstack
161 verbose already installed skipping eventemitter3@1.1.1 /Users/nlee/Projects/hilu-react-fullstack
162 verbose already installed skipping express@4.13.3 /Users/nlee/Projects/hilu-react-fullstack
163 verbose already installed skipping fastclick@1.0.6 /Users/nlee/Projects/hilu-react-fullstack
164 verbose already installed skipping fbjs@0.1.0-alpha.6 /Users/nlee/Projects/hilu-react-fullstack
165 verbose already installed skipping flux@2.0.3 /Users/nlee/Projects/hilu-react-fullstack
166 verbose already installed skipping front-matter@1.0.0 /Users/nlee/Projects/hilu-react-fullstack
167 verbose already installed skipping jade@1.11.0 /Users/nlee/Projects/hilu-react-fullstack
168 verbose already installed skipping lodash@3.10.1 /Users/nlee/Projects/hilu-react-fullstack
169 verbose already installed skipping normalize.css@3.0.3 /Users/nlee/Projects/hilu-react-fullstack
170 verbose already installed skipping react@0.14.0-beta3 /Users/nlee/Projects/hilu-react-fullstack
171 verbose already installed skipping react-dom@0.14.0-beta3 /Users/nlee/Projects/hilu-react-fullstack
172 silly install resolved []
173 info build /Users/nlee/Projects/hilu-react-fullstack
174 info linkStuff @
175 silly linkStuff @ has /Users/nlee/Projects as its parent node_modules
176 verbose linkBins @
177 verbose linkMans @
178 verbose rebuildBundles @
179 verbose rebuildBundles [ '.bin',
179 verbose rebuildBundles   'autoprefixer-core',
179 verbose rebuildBundles   'babel',
179 verbose rebuildBundles   'babel-core',
179 verbose rebuildBundles   'babel-eslint',
179 verbose rebuildBundles   'babel-loader',
179 verbose rebuildBundles   'browser-sync',
179 verbose rebuildBundles   'classnames',
179 verbose rebuildBundles   'css-loader',
179 verbose rebuildBundles   'csscomb',
179 verbose rebuildBundles   'cssnext',
179 verbose rebuildBundles   'del',
179 verbose rebuildBundles   'eslint',
179 verbose rebuildBundles   'eslint-loader',
179 verbose rebuildBundles   'eslint-plugin-react',
179 verbose rebuildBundles   'eventemitter3',
179 verbose rebuildBundles   'express',
179 verbose rebuildBundles   'fastclick',
179 verbose rebuildBundles   'fbjs',
179 verbose rebuildBundles   'file-loader',
179 verbose rebuildBundles   'flux',
179 verbose rebuildBundles   'front-matter',
179 verbose rebuildBundles   'git-push',
179 verbose rebuildBundles   'gulp',
179 verbose rebuildBundles   'gulp-changed',
179 verbose rebuildBundles   'gulp-if',
179 verbose rebuildBundles   'gulp-load-plugins',
179 verbose rebuildBundles   'gulp-rename',
179 verbose rebuildBundles   'gulp-size',
179 verbose rebuildBundles   'gulp-util',
179 verbose rebuildBundles   'jade',
179 verbose rebuildBundles   'jest-cli',
179 verbose rebuildBundles   'lodash',
179 verbose rebuildBundles   'minimist',
179 verbose rebuildBundles   'mkdirp',
179 verbose rebuildBundles   'normalize.css',
179 verbose rebuildBundles   'postcss',
179 verbose rebuildBundles   'postcss-loader',
179 verbose rebuildBundles   'postcss-nested',
179 verbose rebuildBundles   'psi',
179 verbose rebuildBundles   'react',
179 verbose rebuildBundles   'react-dom',
179 verbose rebuildBundles   'react-routing',
179 verbose rebuildBundles   'run-sequence',
179 verbose rebuildBundles   'source-map-support',
179 verbose rebuildBundles   'style-loader',
179 verbose rebuildBundles   'superagent',
179 verbose rebuildBundles   'url-loader',
179 verbose rebuildBundles   'webpack' ]
180 verbose rebuild bundle /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-core
181 info build /Users/nlee/Projects/hilu-react-fullstack/node_modules/babel-core
182 info preinstall babel-core@5.8.21
183 info linkStuff babel-core@5.8.21
184 silly linkStuff babel-core@5.8.21 has /Users/nlee/Projects/hilu-react-fullstack/node_modules as its parent node_modules
185 verbose linkBins babel-core@5.8.21
186 verbose linkMans babel-core@5.8.21
187 verbose rebuildBundles babel-core@5.8.21
188 verbose rebuildBundles [ '.bin',
188 verbose rebuildBundles   'babel-plugin-constant-folding',
188 verbose rebuildBundles   'babel-plugin-dead-code-elimination',
188 verbose rebuildBundles   'babel-plugin-eval',
188 verbose rebuildBundles   'babel-plugin-inline-environment-variables',
188 verbose rebuildBundles   'babel-plugin-jscript',
188 verbose rebuildBundles   'babel-plugin-member-expression-literals',
188 verbose rebuildBundles   'babel-plugin-property-literals',
188 verbose rebuildBundles   'babel-plugin-proto-to-assign',
188 verbose rebuildBundles   'babel-plugin-react-constant-elements',
188 verbose rebuildBundles   'babel-plugin-react-display-name',
188 verbose rebuildBundles   'babel-plugin-remove-console',
188 verbose rebuildBundles   'babel-plugin-remove-debugger',
188 verbose rebuildBundles   'babel-plugin-runtime',
188 verbose rebuildBundles   'babel-plugin-undeclared-variables-check',
188 verbose rebuildBundles   'babel-plugin-undefined-to-void',
188 verbose rebuildBundles   'babylon',
188 verbose rebuildBundles   'bluebird',
188 verbose rebuildBundles   'chalk',
188 verbose rebuildBundles   'convert-source-map',
188 verbose rebuildBundles   'core-js',
188 verbose rebuildBundles   'debug',
188 verbose rebuildBundles   'detect-indent',
188 verbose rebuildBundles   'esutils',
188 verbose rebuildBundles   'fs-readdir-recursive',
188 verbose rebuildBundles   'globals',
188 verbose rebuildBundles   'home-or-tmp',
188 verbose rebuildBundles   'is-integer',
188 verbose rebuildBundles   'js-tokens',
188 verbose rebuildBundles   'json5',
188 verbose rebuildBundles   'line-numbers',
188 verbose rebuildBundles   'minimatch',
188 verbose rebuildBundles   'output-file-sync',
188 verbose rebuildBundles   'path-exists',
188 verbose rebuildBundles   'path-is-absolute',
188 verbose rebuildBundles   'private',
188 verbose rebuildBundles   'regenerator',
188 verbose rebuildBundles   'regexpu',
188 verbose rebuildBundles   'repeating',
188 verbose rebuildBundles   'resolve',
188 verbose rebuildBundles   'shebang-regex',
188 verbose rebuildBundles   'slash',
188 verbose rebuildBundles   'source-map',
188 verbose rebuildBundles   'source-map-support',
188 verbose rebuildBundles   'to-fast-properties',
188 verbose rebuildBundles   'trim-right',
188 verbose rebuildBundles   'try-resolve' ]
189 info install babel-core@5.8.21
190 info postinstall babel-core@5.8.21
191 verbose rebuild bundle /Users/nlee/Projects/hilu-react-fullstack/node_modules/file-loader
192 info build /Users/nlee/Projects/hilu-react-fullstack/node_modules/file-loader
193 info preinstall file-loader@0.8.4
194 info linkStuff file-loader@0.8.4
195 silly linkStuff file-loader@0.8.4 has /Users/nlee/Projects/hilu-react-fullstack/node_modules as its parent node_modules
196 verbose linkBins file-loader@0.8.4
197 verbose linkMans file-loader@0.8.4
198 verbose rebuildBundles file-loader@0.8.4
199 verbose rebuildBundles [ 'loader-utils' ]
200 info install file-loader@0.8.4
201 info postinstall file-loader@0.8.4
202 info install @
203 info postinstall @
204 info prepublish @
205 verbose validateInstall loading /Users/nlee/Projects/hilu-react-fullstack/package.json for validation
206 verbose stack Error: The package eslint does not satisfy its siblings' peerDependencies requirements!
206 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:125:32
206 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:267:7
206 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
206 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
206 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
206 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
206 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
206 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
206 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
206 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
207 verbose cwd /Users/nlee/Projects/hilu-react-fullstack
208 error Darwin 14.1.0
209 error argv "node" "/usr/local/bin/npm" "install"
210 error node v0.12.6
211 error npm  v2.12.1
212 error code EPEERINVALID
213 error peerinvalid The package eslint does not satisfy its siblings' peerDependencies requirements!
213 error peerinvalid Peer eslint-plugin-react@3.2.1 wants eslint@>=0.8.0 || ~1.0.0-rc-0
213 error peerinvalid Peer eslint-loader@0.14.2 wants eslint@0.21 - 0.24 || ~1.0.0-rc-0
214 verbose exit [ 1, true ]
```
##

**Comment by RanzQ** [comment]
Setting `"eslint-loader": "^1.0.0"` to package.json fixed this for me.

**Comment by joshjung** [comment]
Thanks @RanzQ that fixed it for me as well.

**Comment by kaushik94** [comment]
I tried to set `"eslint": "1.0.0"` and it worked.

**Comment by RanzQ** [comment]
@kaushik94 I think its better to update the `eslint-loader` since without the caret `^` your `eslint` won't get updated to versions 1.x.x.

**Comment by ulani** [comment]
@nathaniellee   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
