### ISSUE TITLE
Error: Cannot find module '/Users/yuansc/project/react2/build/server.js'  when run  npm start

### ISSUE THREAD

**Issue by biebg** [kriasoft/react-starter-kit#202]
when I run npm start, I got such error, what should i do?

```
yuansc@~/project/react2:$ npm start --release

> react-starter-kit@0.0.0 start /Users/yuansc/project/react2
> gulp

[11:47:23] Using gulpfile ~/project/react2/gulpfile.js
[11:47:23] Starting 'build:watch'...
[11:47:23] Starting 'clean'...
[11:47:23] Finished 'clean' after 19 ms
[11:47:23] Starting 'build'...
[11:47:23] Starting 'vendor'...
[11:47:23] Starting 'assets'...
[11:47:23] Starting 'styles'...
[11:47:24] Starting 'bundle'...
[11:47:26] Finished 'bundle' after 1.7 s
[11:47:29] styles all files 135.72 kB
[11:47:29] Finished 'styles' after 5.84 s
[11:47:29] Finished 'vendor' after 5.99 s
[11:47:29] assets all files 28.97 kB
[11:47:29] Finished 'assets' after 5.99 s
[11:47:29] Finished 'build' after 5.99 s
[11:47:29] Finished 'build:watch' after 6.04 s
[11:47:29] Starting 'serve'...
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/yuansc/project/react2/build/server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


```
##

**Comment by koistya** [comment]
You may want to use the latest version from the `master` branch..

**Comment by andrei-sheina** [comment]
Same error. Node v 0.12.7 with npm 2.11.3

**Comment by ulani** [comment]
@biebg   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
