### ISSUE TITLE
isarray module missing

### ISSUE THREAD

**Issue by nanuclickity** [kriasoft/react-starter-kit#223]
isarray module is missing from package.json

**Comment by koistya** [comment]
`.isArray` is available via Babel/core-js, no need to use a dedicated module for that I believe.

**Comment by nanuclickity** [comment]
This is the output of a fresh pull just 10 mins ago

```bash
npm start

> @ start /Users/tushar/Github/react-starter-kit
> babel-node --eval "require('./tools/start')().catch(err => console.log(err.stack))"

build
clean
copy
bundle
Child
         Asset     Size  Chunks             Chunk Names
        app.js  1.07 MB       0  [emitted]  main
    app.js.map   1.2 MB       0  [emitted]  main
Child
            Asset    Size  Chunks             Chunk Names
        server.js  154 kB       0  [emitted]  main
    server.js.map  105 kB       0  [emitted]  main
serve
Error: Cannot find module 'isarray'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tushar/Github/react-starter-kit/build/webpack:/external "isarray":1:1)
    at __webpack_require__ (/Users/tushar/Github/react-starter-kit/build/webpack:/webpack/bootstrap 7de32b64a65b2de47b26:19:1)
    at Object.<anonymous> (/Users/tushar/Github/react-starter-kit/build/webpack:/~/path-to-regexp/index.js:1:1)
    at __webpack_require__ (/Users/tushar/Github/react-starter-kit/build/webpack:/webpack/bootstrap 7de32b64a65b2de47b26:19:1)
    at Object.<anonymous> (/Users/tushar/Github/react-starter-kit/build/webpack:/~/react-routing/src/Match.js:31:21)
    at Object.<anonymous> (/Users/tushar/Github/react-starter-kit/build/webpack:/~/react-routing/src/Route.js:22:21)
```

**Comment by koistya** [comment]
Try to remove `node_modules` and make a clean `npm install`. Maybe there is an issue with one of the npm modules used in the project.

**Comment by koistya** [comment]
`isarray` is not used anywhere in project's source files. But it is used in Webpack for example. Perhaps when you installed webpack it failed to install its `isarray` dependency.

**Comment by nanuclickity** [comment]
clean npm install worked. thanks.
