### ISSUE TITLE
Error running npm test

### ISSUE THREAD

**Issue by georgepapas** [kriasoft/react-starter-kit#262]
Cloning the repo or using the yeoman generator gives the following error when running npm test..
Am I missing something...

Cheers

```
node_modules/jest-cli/src/TestRunner.js:433
        const cacheA = testPerformanceCache && testPerformanceCache[a[0]];
        ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/code/node_modules/jest-cli/src/jest.js:13:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by georgepapas** [comment]
Looks like I was using node 0.12.7.  Upgraded to 4.0.0 and looks good now.
