### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by brw31415** [kriasoft/react-starter-kit#318]
I followed the steps listed here and get this error

4:~/workspace/MyApp (master) $ npm start

> @ start /home/ubuntu/workspace/MyApp
> babel-node tools/run start

/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:43
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /home/ubuntu/workspace/MyApp/tools/run.js: Unknown option: /home/ubuntu/workspace/MyApp/.babelrc.stage
    at Logger.error (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:250:18)
    at OptionManager.addConfig (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:209:10)
    at OptionManager.findConfigs (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:352:16)
    at OptionManager.init (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:12)
    at File.initOptions (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-core/lib/api/node.js:118:10)
    at compile (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:20)

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get their info via:
##

**Comment by wdmtech** [comment]
:+1:, Windows 7 user here

```

D:\Dev\react-fullstack>npm start

> @ start D:\Dev\react-fullstack
> babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"

[05:07:21] Starting 'start'...
[05:07:21] Starting 'build'...
[05:07:21] Starting 'clean'...
[05:07:21] Finished 'clean' after 32 ms
[05:07:21] Starting 'copy'...
build/package.json
[05:07:21] Finished 'copy' after 132 ms
[05:07:21] Starting 'bundle'...
Time: 4219ms
        Asset    Size  Chunks             Chunk Names
    server.js  148 kB       0  [emitted]  main
server.js.map  110 kB       0  [emitted]  main
Time: 4636ms
 Asset     Size  Chunks             Chunk Names
app.js  3.09 MB       0  [emitted]  main
[05:07:25] Finished 'bundle' after 4672 ms
[05:07:25] Finished 'build' after 4904 ms
[05:07:25] Starting 'serve'...
The server is running at http://localhost:5000
[05:07:26] Finished 'serve' after 967 ms
[05:07:26] Finished 'start' after 5899 ms
webpack built 9093165fb1744a076314 in 2729ms
Time: 2729ms
 Asset     Size  Chunks             Chunk Names
app.js  3.09 MB       0  [emitted]  main
webpack: bundle is now VALID.
[BS] Proxying: http://localhost:5000
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.132:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.132:3001
 --------------------------------------
[BS] Watching files...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickDomainCallback (node.js:394:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Will\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --eval "require('./tools/start')().catch(err => console.error(err.stack))"
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dev\react-fullstack\npm-debug.log
```

**Comment by Kepro** [comment]
@brw31415 what version you are using? babel 5.8.29 not version 6

**Comment by underbayan** [comment]
i also get the issue when i try to use your scaffold,my node v5.6.0  and npm v3.6.0 is already newest stable version ,i dont know how to fix it:
`> @ start /Users/laina/Desktop/reactkit
> babel-node tools/run start

/Users/laina/Desktop/reactkit/tools/run.js:31
export default run;
^^^^^^
SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/Users/laina/Desktop/reactkit/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/laina/Desktop/reactkit/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at /Users/laina/Desktop/reactkit/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/laina/Desktop/reactkit/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:413:34)

`

**Comment by koistya** [comment]
@underbayan do you have `.babelrc` file in the root of your source tree?

**Comment by phpgit** [comment]
Any one have any solution on this issue? I encounter the same
`
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\nobody\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--userconfig=C:\\Users\\nobody\\.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--cache=C:\\Users\\nobody\\.cnpm',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   '--node-gyp=C:\\Users\\nobody\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js',
1 verbose cli   'start' ]
2 info using npm@2.14.19
3 info using node@v4.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart @
6 info start @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec start script
9 verbose stack Error: @ start: `babel-node tools/run start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\nobody\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\nobody\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd D:\www\2016\mobilmech.com.au\react-starter-kit
12 error Windows_NT 6.1.7601
13 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nobody\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\nobody\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\nobody\\.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=C:\\Users\\nobody\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "start"
14 error node v4.4.1
15 error npm  v2.14.19
16 error code ELIFECYCLE
17 error @ start: `babel-node tools/run start`
17 error Exit status 1
18 error Failed at the @ start script 'babel-node tools/run start'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel-node tools/run start
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by ulani** [comment]
@brw31415  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
