### ISSUE TITLE
get an eslint error

### ISSUE THREAD

**Issue by simongfxu** [kriasoft/react-starter-kit#319]
I am following your instructions [here](https://github.com/kriasoft/react-starter-kit/blob/master/docs/how-to-configure-text-editors.md), but only get an error on Atom like this.

```html
Error: Cannot find module 'eslint-config-airbnb' Referenced from: /Users/xugaofan/developer/git/MyApp/.eslintrc
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: /Users/xugaofan/developer/git/MyApp/.eslintrc
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at readConfigFromFile (/Users/xugaofan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:155:44)
    at loadConfig (/Users/xugaofan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:176:22)
    at /Users/xugaofan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (/Users/xugaofan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:191:36)
    at getLocalConfig (/Users/xugaofan/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:321:23)
```

**Comment by Kepro** [comment]
try to run npm install in your directory

**Comment by simongfxu** [comment]
@Kepro Well, this problem has been resolved by update my atom plugins.
It looks like a atom plugin(lint-eslinter) error.

**Comment by Kepro** [comment]
then close it :)
