### ISSUE TITLE
Error: Cannot find module './assets.json'

### ISSUE THREAD

**Issue by sorahn** [kriasoft/react-starter-kit#357]
I just checked out this repo tonight, ran `npm install`, then `npm start`.

```
↪ npm start

> @ start /src/test-app
> babel-node tools/run start

[21:21:48] Starting 'start'...
[21:21:48] Starting 'clean'...
[21:21:48] Finished 'clean' after 22 ms
[21:21:48] Starting ''...
build/package.json
[21:21:48] Finished '' after 164 ms
Error: Cannot find module './assets.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.Object.defineProperty.value (/src/test-app/build/webpack:/external "./assets.json":1:1)
    at __webpack_require__ (/src/test-app/build/webpack:/webpack/bootstrap aa2d604e4e09d8ff8a8e:19:1)
    at Object.<anonymous> (/src/test-app/build/webpack:/src/server.js:9:37)
    at __webpack_require__ (/src/test-app/build/webpack:/webpack/bootstrap aa2d604e4e09d8ff8a8e:19:1)
    at module.exports._this2 (/src/test-app/build/webpack:/webpack/bootstrap aa2d604e4e09d8ff8a8e:39:1)
    at Object.<anonymous> (/src/test-app/build/webpack:/webpack/bootstrap aa2d604e4e09d8ff8a8e:39:1)
webpack built 333c850d705c8c769ddd in 6474ms
Child
    Time: 6474ms
                           Asset     Size  Chunks             Chunk Names
    main.js?333c850d705c8c769ddd  3.13 MB       0  [emitted]  main
Child
    Time: 5748ms
            Asset    Size  Chunks             Chunk Names
        server.js  194 kB       0  [emitted]  main
    server.js.map  173 kB       0  [emitted]  main
webpack: bundle is now VALID.
```

There were a couple errors for the `npm install` command, and I'm not sure if they're related.
```
npm WARN engine jest-cli@0.8.2: wanted: {"node":">= 4"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN prefer global babel@5.8.34 should be installed with -g
```

Here's what's in the build directory.
```
↪ ls build
assets.json   content       package.json  public        server.js     server.js.map
```

**Comment by koistya** [comment]
Can you please check that changing this line

```js
  bundler.compilers
      .find(x => x.options.target === 'node')
      .plugin('done', () => handleServerBundleComplete());
```

to this

```js
  bundler.compilers.plugin('done', () => handleServerBundleComplete());
```

(in `tools/server.js` at the bottom) does fix the issue?

**Comment by koistya** [comment]
I cannot reproduce it on my machine...

**Comment by koistya** [comment]
Or, perhaps, in `src/server.js` there should be `fs.readFile('assets.json')` instead of `require('assets.json')`.

**Comment by sorahn** [comment]
[Whelp](http://images1.fanpop.com/images/quiz/12215_1213577553669_434_308.jpg), updated my version of node, and we're off and running.  Sorry, I didn't see your response before I did that, but we're all good.  Thanks!

**Comment by koistya** [comment]
Ah, yeah.. starting from Node 5.x you can do `require('assets.json')` instead of

```js
const assets = await new Promise((resolve, reject) => {
  fs.readFile(path.join(__dirname, 'assets.json'), 'utf8', (err, data) => {
    if (err) {
      reject(err);
    } else {
      resolve(JSON.parse(data));
    }
  });
});
```

Should we add Node.js 12.0, 4.x compatibility?

**Comment by sorahn** [comment]
I think you should just leave it on 5.x.  This code is all from the future anyways!

**Comment by koistya** [comment]
I guess it would be better to use `fs.readFile` instead of `require()` from semantic point of view. So here is a fix - PR #358.

**Comment by jingweno** [comment]
I'm getting this too:

```
Error: Cannot find module './assets'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.Object.defineProperty.value (/Users/owen/src/react-starter-kit/build/webpack:/external "./assets":1:1)
    at __webpack_require__ (/Users/owen/src/react-starter-kit/build/webpack:/webpack/bootstrap db50031e94602b767cb8:19:1)
    at Object.<anonymous> (/Users/owen/src/react-starter-kit/build/webpack:/src/server.js:9:37)
    at __webpack_require__ (/Users/owen/src/react-starter-kit/build/webpack:/webpack/bootstrap db50031e94602b767cb8:19:1)
    at module.exports._this2 (/Users/owen/src/react-starter-kit/build/webpack:/webpack/bootstrap db50031e94602b767cb8:39:1)
    at Object.<anonymous> (/Users/owen/src/react-starter-kit/build/webpack:/webpack/bootstrap db50031e94602b767cb8:39:1)
```

```
$ node -v
v5.3.0
$ npm -v
3.5.3
```

**Comment by koistya** [comment]
@jingweno does this commit fix the issue? de4d682

**Comment by Geoide** [comment]
The same for me (as @jingweno). Any advance?

```
/ $ node -v
v5.3.0
/ $ npm -v
3.3.12
```

**Comment by jingweno** [comment]
https://github.com/kriasoft/react-starter-kit/commit/de4d6825012f7174d63923b482c197d282f52a30 fixed it for me.

**Comment by manodupont** [comment]
not for me.

**Comment by FakhruddinAbdi** [comment]
I'm getting this error too
```
Error: Cannot find module './assets'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/external "./assets":1:1)
    at __webpack_require__ (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:19:1)
    at Object.<anonymous> (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:39:1)
    at __webpack_require__ (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:19:1)
    at /Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:39:1
    at Object.<anonymous> (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:39:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
```

**Comment by heks** [comment]
still getting this error too

**Comment by Meerk8** [comment]
Also having this issue. I am running node ver 6.6.0. Believe it was not an issue under earlier version of Node.

**Comment by devonzuegel** [comment]
I am also having this issue.

**npm:** 3.10.3
**node:** 6.6.0

**Comment by langpavel** [comment]
This is not issue in our codebase.
