### ISSUE TITLE
Initial yeoman scaffold results in TypeError: undefined is not a function

### ISSUE THREAD

**Issue by brandon-arnold** [kriasoft/react-starter-kit#360]
Hi all,

The `react-fullstack` generator works fine on my other Windows 10 laptop, but I've just tried running `yo react-fullstack` on a Windows 7 computer and gotten an error. Following are versioning and error results:

``` bash
PS C:\projects\bacom> npm list -g npm yo generator-react-fullstack
C:\Users\212438903\AppData\Roaming\npm
├── generator-react-fullstack@0.1.13
├── npm@3.5.2
└── yo@1.5.0

PS C:\projects\bacom> yo react-fullstack
C:\Users\212438903\AppData\Roaming\npm\node_modules\generator-react-fullstack\node_modules\yeoman-generator\lib\base.js:
474
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\212438903\AppData\Roaming\npm\node_modules\generator-react-fullstack\node_modules\yeoman-generator\
lib\base.js:474:21)
    at Environment.run (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js
:331:20)
    at C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\re
solver.js:50:12)
    at init (C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
##

**Comment by brandon-arnold** [comment]
Upgrading to node 5+ and running ```npm uninstall -g```/```npm install -g``` on ```yo```,```npm```, and ```generator-react-fullstack``` has not fixed it. Again, Windows 7, my corporate laptop.

**Comment by ulani** [comment]
@brandon-arnold  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
