### ISSUE TITLE
Cannot find method on a store while testing with Jest

### ISSUE THREAD

**Issue by manhhavu** [kriasoft/react-starter-kit#39]
I'm trying to test the PageStore which is included by default in this project:

```javascript
jest.dontMock('../PageStore');
jest.dontMock('object-assign');

describe('PageStore', function() {

  var Dispatcher;
  var PageStore;

  var callback;

  beforeEach(function() {
    Dispatcher = require('../../core/Dispatcher');
    PageStore = require('../PageStore');
    callback = Dispatcher.register.mock.calls[0][0];
  });

  it('returns default page', function() {
    expect(PageStore.get()).toBe({
      title: 'React.js Starter Kit',
      description: 'A skeleton for an isomorphic web application (SPA) built with React.js and Flux',
      keywords: null
    });
  });
});
```

however, I always get this error: 
```
 FAIL  stores/__tests__/PageStore-test.js (0.313s)
● PageStore › it returns current page
  - TypeError: Object [object Object] has no method 'get'
        at Spec.<anonymous> (/Users/manhhavu/Developer/experiments/shopizie-kart/src/stores/__tests__/PageStore-test.js:25:22)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```
I doubt that there is something wrong with the ES6 compilation configured for Jest, because the constructor of Store never get called by Jest. Could you give me some clue to make it work?

**Comment by adjavaherian** [comment]
I was able to get a store working by using my real store with https://www.npmjs.com/package/fluxxor-test-utils.  Here's an example spec. 

```
/** @jsx React.DOM */
//tests/app/modules/autocompletemaxprice-test.js
jest.dontMock('../../../app/modules/AutocompleteMaxPrice.jsx');

var React, TestUtils, FluxxorTestUtils, FluxConstructor, realFlux, fakeFlux, MyComponent, Component;

describe('Testing Autocomplete Max Price', function() {

    beforeEach(function() {
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;
        FluxxorTestUtils = require('fluxxor-test-utils');
        FluxConstructor = require('../../../app/FluxConstructor.js');
        realFlux = FluxConstructor();
        fakeFlux = FluxxorTestUtils.fakeFlux(realFlux);
        fakeFlux.genMocksForStoresAndActions();
        // now all store and action methods are mocked for testing

        MyComponent = require('../../../app/modules/AutocompleteMaxPrice.jsx');
        Component = TestUtils.renderIntoDocument(<MyComponent flux={fakeFlux} />);

    });
    it('when created, component should have AutocompleteMaxPrice class', function() {
        var div = TestUtils.findRenderedDOMComponentWithClass(
            Component, 'AutocompleteMaxPrice');
    });
    it('when mounted and focused, should call onTargetFocus', function() {

        Component.onTargetFocus = jest.genMockFunction();
        TestUtils.Simulate.focus(Component.refs.inputField.getDOMNode());
        expect(Component.onTargetFocus).toBeCalled();
    });
});
```
In our case, our stores are in the FluxConstructor.  Unfortunately, there is a bug in the Simulate class which doesn't call the mocked version of Component.onTargetFocus.  See Also, https://github.com/facebook/jest/issues/207

**Comment by koistya** [comment]
I'm going to close this issue for now. Feel free to reopen if needed.
