### ISSUE TITLE
Getting error after upgrade 'Error: Cannot find module 'assets-webpack-plugin''

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#420]
`npm start`
```

> @ start /Users/vishal/Workspace/joey
> babel-node tools/run start

module.js:328
    throw err;
    ^

Error: Cannot find module 'assets-webpack-plugin'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/vishal/Workspace/joey/tools/webpack.config.js:27:28)
    at Module._compile (module.js:398:26)
    at loader (/Users/vishal/Workspace/joey/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/vishal/Workspace/joey/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vishal/Workspace/joey/npm-debug.log
```
`cat /Users/vishal/Workspace/joey/npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/vishal/Workspace/joey/node_modules/.bin:/Users/vishal/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle @~start: CWD: /Users/vishal/Workspace/joey
11 silly lifecycle @~start: Args: [ '-c', 'babel-node tools/run start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid @
16 verbose cwd /Users/vishal/Workspace/joey
17 error Darwin 15.2.0
18 error argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error @ start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script 'babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run start
23 error You can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any help?

**Comment by koistya** [comment]
Hm, that's strange.. `assets-webpack-plugin` should be installed, since it's referenced in [package.json#L29](https://github.com/kriasoft/react-starter-kit/blob/master/package.json#L29)

**Comment by koistya** [comment]
Maybe you can try to update `npm`, remove `node_modules` folder and run `npm install` again..

```sh
$ npm install -g npm@latest
$ npm install
```

**Comment by vishalvijay** [comment]
@koistya 
Getting the same error even after updating npm.

This is happening only in my project which is based on react-starter-kit. I'm not getting this error on latest clone of react-starter-kit

**Comment by koistya** [comment]
@vishalvijay is `assets-webpack-plugin` listed in your `package.json` file? As a workaround you can try to install it separately `npm install assets-webpack-plugin`.

**Comment by vishalvijay** [comment]
@koistya Really sorry, in the pervious upgrade I some how missed `"assets-webpack-plugin": "^3.2.0",` in package.json.

After adding that line in package file resolved the issue. But before it was working fine for me.

Thank you

**Comment by gkmbinh** [comment]
@koistya 
`$ npm install -g npm@latest`

it work as well with me. thanks alot.
