### ISSUE TITLE
NPM commands - build and start -  throws the error code ELIFECYCLE

### ISSUE THREAD

**Issue by web-jenezis** [kriasoft/react-starter-kit#457]
Hi guys,

Just started with the react-starter-kit and met the problem in start :)
When I trying to run the `npm start` or `npm run build` I get the error:
```
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! @ build: `babel-node tools/run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'babel-node tools/run build'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path npm-debug.log.e95a8f4cfd1d5ee7786167cdcac54577
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename
```
And there is the NPM log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 silly lifecycle @~prebuild: no script for prebuild, continuing
7 info lifecycle @~build: @
8 verbose lifecycle @~build: unsafe-perm in lifecycle true
9 verbose lifecycle @~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/public/jenezis/node_modules/.bin:~/.composer/vendor/bin:/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/home/vagrant/.rbenv/plugins/ruby-build/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/.composer/vendor/bin:/home/vagrant/git-scripts:/usr/local/sbin:/usr/sbin:/sbin
10 verbose lifecycle @~build: CWD: /var/www/public/jenezis
11 silly lifecycle @~build: Args: [ '-c', 'babel-node tools/run build' ]
12 silly lifecycle @~build: Returned: code: 1  signal: null
13 info lifecycle @~build: Failed to exec build script
14 verbose stack Error: @ build: `babel-node tools/run build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid @
16 verbose cwd /var/www/public/jenezis
17 error Linux 3.13.0-55-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v5.0.0
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error @ build: `babel-node tools/run build`
22 error Exit status 1
23 error Failed at the @ build script 'babel-node tools/run build'.
23 error This is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run build
23 error You can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by web-jenezis** [comment]
I found the problem. I have been installed the `babel` package instead `babel-cli`. Next commands are solve the issue:
```
$ sudo npm uninstall -g babel
sudo npm install -g babel-cli
```
