### ISSUE TITLE
npm start - ends with fail

### ISSUE THREAD

**Issue by web-jenezis** [kriasoft/react-starter-kit#460]
I tried to start the react-starter-kit but without success. I used the command `npm start` and got the result:

```
> @ start /var/www/public/jenezis
> babel-node tools/run start

[20:50:43] Starting 'start'...
[20:50:43] Starting 'clean'...
[20:50:43] Finished 'clean' after 299 ms
[20:50:43] Starting 'bound copy'...
build/package.json
[20:50:43] Finished 'bound copy' after 277 ms
webpack built 670c0a7bb73c47ce91e7 in 26917ms
Child
    Time: 26917ms
                           Asset     Size  Chunks             Chunk Names
    main.js?670c0a7bb73c47ce91e7  3.39 MB       0  [emitted]  main
Child
    Time: 24661ms
            Asset    Size  Chunks             Chunk Names
        server.js  216 kB       0  [emitted]  main
    server.js.map  219 kB       0  [emitted]  main
webpack: bundle is now VALID.
[20:51:24] The server is running at http://localhost:5000/
[BS] Proxying: http://localhost:5000
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.2.15:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 ----------------------------------
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:339:9)
    at module.exports (/var/www/public/jenezis/node_modules/opn/index.js:79:24)
    at Object.utils.open (/var/www/public/jenezis/node_modules/browser-sync/lib/utils.js:173:23)
    at Object.utils.openBrowser (/var/www/public/jenezis/node_modules/browser-sync/lib/utils.js:163:23)
    at EventEmitter.events.service:running (/var/www/public/jenezis/node_modules/browser-sync/lib/internal-events.js:45:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at /var/www/public/jenezis/node_modules/browser-sync/lib/browser-sync.js:260:19
    at /var/www/public/jenezis/node_modules/async-each-series/index.js:15:40
    at executeTask (/var/www/public/jenezis/node_modules/browser-sync/lib/browser-sync.js:170:13)
    at Object.module.exports.initUserPlugins [as fn] (/var/www/public/jenezis/node_modules/browser-sync/lib/async.js:396:9)
    at /var/www/public/jenezis/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/var/www/public/jenezis/node_modules/async-each-series/index.js:8:5)
    at /var/www/public/jenezis/node_modules/async-each-series/index.js:16:16

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path npm-debug.log.07b53e92eb8dd2816c4abdcf7ccdbe18
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.07b53e92eb8dd2816c4abdcf7ccdbe18' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/public/jenezis/npm-debug.log
```
##

**Comment by koistya** [comment]
It failes to execute `node build/server.js` command in a child process... do you have `/build/server.js` file?

**Comment by web-jenezis** [comment]
@koistya just checked - yes, it's in build directory. The `npm run build` works fine. Not really sure why it fails, because `node build/server.js` starts the server and it accessable from browser http://joxi.ru/L21j5vvTa435AX

**Comment by koistya** [comment]
Mm.. maybe that's BrowserSync  specific issue on Linux.. Have you checked BrowserSync repo for this issue?

**Comment by web-jenezis** [comment]
@koistya Not yet, will checl BrowserSync, I'm using vagrant scotch-box for development, do you think ittrying to start browser in the vagrant box?

**Comment by koistya** [comment]
Yep, could be https://github.com/BrowserSync/browser-sync/search?utf8=%E2%9C%93&q=vagrant&type=Issues

**Comment by web-jenezis** [comment]
Ok, will check the issue. I will update the issue, if it will be solved.

**Comment by web-jenezis** [comment]
I'm didn't found a problem at BrowserSync repo, but I found the peace of code, which occurs the error. It's lines 87-97 in the tools/start.js (code related to the Browsersync):
```
    let handleServerBundleComplete = () => {
      runServer((err, host) => {
        if (!err) {
          const bs = Browsersync.create();
          bs.init({
            proxy: {
              target: host,
              middleware: [wpMiddleware, ...hotMiddlewares],
            },

            // no need to watch '*.js' here, webpack will take care of it for us,
            // including full page reloads if HMR won't work
            files: ['build/content/**/*.*'],
          }, resolve);
          handleServerBundleComplete = runServer;
        }
      });
    };
```

**Comment by koistya** [comment]
@web-jenezis can you check that the `host` variable contain? It should be http://localhost:5000/ - the address on which `node /build/server.js` app is running.

**Comment by Bogdaan** [comment]
@web-jenezis check directory rights (user/owner of node_modules, src, build) and current user.

```
# ls -la .
# netstat -putan or lsof  | grep 5000
# netstat -putan or lsof  | grep 3000
# whoami
```

**Comment by ulani** [comment]
@web-jenezis   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
