### ISSUE TITLE
npm start - fails 

### ISSUE THREAD

**Issue by fawadniazi** [kriasoft/react-starter-kit#504]
Hi,

I'm getting this error on running npm start 

> @ start /Users/zz/MyApp
> babel-node tools/run start

/Users/zz/MyApp/tools/start.js:42
            plugins: [...(x.query ? x.query.plugins : []), ['react-transform', {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/zz/MyApp/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zz/MyApp/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (run.js:27:18)
    at Module._compile (module.js:409:26)

**Comment by arkeros** [comment]
@fawadniazi I also had the same error. Just update node to v5.

**Comment by fawadniazi** [comment]
@arkeros Thanks!, will give it a try.

**Comment by fawadniazi** [comment]
@arkeros node v5 works for me
