### ISSUE TITLE
[AWS][EC2] Error: Cannot find module 'core-js/library/fn/get-iterator

### ISSUE THREAD

**Issue by az-ericso** [kriasoft/react-starter-kit#505]
I am getting this error after deploying the content in the "build" folder to AWS Elastic Beanstalk. 

``` sh
Error: Cannot find module 'core-js/library/fn/get-iterator'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.exports.__esModule (/var/app/current/webpack:/external "core-js/library/fn/get-iterator":1:1)
    at __webpack_require__ (/var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:19:1)
    at Object.<anonymous> (/var/app/current/~/babel-runtime/core-js/get-iterator.js:1:19)
    at __webpack_require__ (/var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:19:1)
    at Object.module.exports.exports.__esModule (/var/app/current/server.js:1555:23)
    at __webpack_require__ (/var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:19:1)
    at Object.<anonymous> (/var/app/current/webpack:/routes.js:11:1)
    at __webpack_require__ (/var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:19:1)
    at Object.<anonymous> (/var/app/current/webpack:/server.js:22:1)
    at __webpack_require__ (/var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:19:1)
    at /var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:39:1
    at Object.<anonymous> (/var/app/current/webpack:/webpack/bootstrap 8dc144ed7f4b43610864:39:1)
```

**Comment by hansiemithun** [comment]
Any updates on this error? Even i am also getting the same error

**Comment by topwebmaster** [comment]
Im too

**Comment by Qboooogle** [comment]
I am getting the same error now.What should I do?

**Comment by szl-926929** [comment]
i'm too

**Comment by langpavel** [comment]
Can this still be an issue? I believe you doing something wrong. Did you build your app and install dependencies on server?

**Comment by jitendrakhedar** [comment]
I am facing the same error on starting the appium server. Any update?

**Comment by smapig** [comment]
I'm facing similar problem. I run `yarn build --release` on build server that is running on Amazon Linux AMI 2018.03.0 (64 bit), than I zip content of `build` folder into one archive and deploy it into EBS instance that is hosting at platform `Node.js running on 64bit Amazon Linux/4.7.0`. After deploy successful, my environment health transitioned to Severe, I'm tracking logs and receive error:

`-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
    at call (/var/app/current/webpack/bootstrap:25:1)
Error: Cannot find module 'babel-runtime/core-js/json/stringify'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.require (/var/app/current/external "babel-runtime/core-js/json/stringify":1:1)
    at call (/var/app/current/webpack/bootstrap:25:1)
    at Object.__webpack_require__ (/var/app/current/node_modules/isomorphic-style-loader/lib/insertCss.js:3:1)
    at call (/var/app/current/webpack/bootstrap:25:1)
    at Object.__webpack_require__ (/var/app/current/webpack:/src/routes/error/ErrorPage.css?b874:3:1)
    at call (/var/app/current/webpack/bootstrap:25:1)
`

**Comment by IfyNdu** [comment]
@smapig did you eventually resolve your issue? if so what steps did you take?

**Comment by smapig** [comment]
@IfyNdu Sorry for this belated response. I've got figure out solution. I added `.ebextension` directory contains yarn config file with content below.

```
files:
  # Runs right before `npm install` in '.../50npm.sh'
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/41_install_yarn.sh" :
    mode: "000775"
    owner: root
    group: users
    content: |
      #!/bin/bash

      app="$(/opt/elasticbeanstalk/bin/get-config container -k app_staging_dir)";

      # install node
      curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -;

      # install yarn
      curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo;
      yum -y install yarn;
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh":
    mode: "000755"
    owner: root
    group: users
    content: |
      #!/usr/bin/env bash
      #
      # Prevent installing or rebuilding like Elastic Beanstalk tries to do by
      # default.           
      # Note that this *overwrites* Elastic Beanstalk's default 50npm.sh script
      # (https://gist.github.com/wearhere/de51bb799f5099cec0ed28b9d0eb3663).
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/51_install_packages.sh" :
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/bin/bash
      app="$(/opt/elasticbeanstalk/bin/get-config container -k app_staging_dir)";
      cd "${app}";
      yarn install --production=false;
      yarn build --release;
```

On elastic beanstalk application, I configured node command is `node build/server`. And everything work like expect.

**Comment by ulani** [comment]
@az-ericso   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
