### ISSUE TITLE
Having issues using CSS

### ISSUE THREAD

**Issue by Ehesp** [kriasoft/react-starter-kit#510]
I've read the other issues submitted here, but I can't get CSS to load.

In an component, I do something like:

```
import s from 'rc-dropdown/assets/index.css';
...
export default withStyles(Dropdown, s);
```

However I get the error: `SyntaxError: Unexpected token ILLEGAL`

I've tried modifying the webpack config to both:

```
      {
        test: /\.css$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
          `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`
        ]
      },
```
and
```
{
        test: /\.scss$|.css$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: DEBUG,

            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',

            // CSS Nano http://cssnano.co/options/
            minimize: !DEBUG,
          })}`,
          'postcss-loader?parser=postcss-scss',
          'sass-loader?sourceMap',
        ],
      },
```

Still getting the same error - what am I supposed to do?

**Comment by Bogdaan** [comment]
Check you css file (rc-dropdown/assets/index.css) for HTTP/https imports.

And change to:
```
{
        test: /\.s?css$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: DEBUG,
            localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
            // CSS Nano http://cssnano.co/options/
            minimize: !DEBUG,
          })}`,
          'postcss-loader?parser=postcss-scss',
          'sass-loader?sourceMap',
        ],
      },
```

link #499
link #423

**Comment by Ehesp** [comment]
Thanks

I changed it to the above, however I still get the same error. The css file starts off like so:

```
@font-face {
  font-family: 'anticon';
  src: url('//at.alicdn.com/t/font_1434092639_4910953.eot');
  /* IE9*/
  src: url('//at.alicdn.com/t/font_1434092639_4910953.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('//at.alicdn.com/t/font_1434092639_4910953.woff') format('woff'), /* chrome、firefox */ url('//at.alicdn.com/t/font_1434092639_4910953.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/ url('//at.alicdn.com/t/font_1434092639_4910953.svg#iconfont') format('svg');
  /* iOS 4.1- */
}
.rc-dropdown {
  position: absolute;
}
```

If I remove the first `@font-face`, I then get the error: `SyntaxError: Unexpected token .`

**Comment by Ehesp** [comment]
It works fine if I do:

```
import s from '!!isomorphic-style-loader!css-loader!rc-dropdown/assets/index.css';
```

However, not if I use the loader directly.

**Comment by frenzzy** [comment]
maybe you need to include this path..
```js
{
  test: /\.s?css$/,
  include: [
    path.resolve(__dirname, '../node_modules/rc-dropdown/assets'),
    path.resolve(__dirname, '../src'),
  ],
  loaders: [...],
}
```

**Comment by Ehesp** [comment]
Nope, still didn't work!

**Comment by frenzzy** [comment]
Can you show the full text of the error with stack?

**Comment by Ehesp** [comment]
Sure:

File which uses the `index.css`:
```
import React, { Component, PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import RCDropdown from 'rc-dropdown';
import Filter from 'lodash/filter';
//import s from '!!isomorphic-style-loader!css-loader!rc-dropdown/assets/index.css';
import s from 'rc-dropdown/assets/index.css';

class Dropdown extends Component {

    static propTypes = {
        children: PropTypes.node.isRequired
    };

    render() {
        const { children, ...props } = this.props;

        return (
            <RCDropdown
                {...props}
            >
                {children}
            </RCDropdown>
        );
    }
}

export default withStyles(Dropdown, s);
```

Webpack Config Loader:

```
{
        test: /\.s?css$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: DEBUG,

            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',

            // CSS Nano http://cssnano.co/options/
            minimize: !DEBUG,
          })}`,
          'postcss-loader?parser=postcss-scss',
          'sass-loader?sourceMap',
        ],
      },
```

Error:

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/elliothesp/Documents/Code/new-app/build/webpack:/external "rc-dropdown/assets/index.css":1:1)
    at __webpack_require__ (/Users/elliothesp/Documents/Code/new-app/build/webpack:/webpack/bootstrap f812a2ff7711f385a97d:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/elliothesp/Documents/Code/new-app/build/webpack:/src/components/misc/Dropdown/Dropdown.js:6:1)
    at __webpack_require__ (/Users/elliothesp/Documents/Code/new-app/build/webpack:/webpack/bootstrap f812a2ff7711f385a97d:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/elliothesp/Documents/Code/new-app/build/webpack:/src/components/UserMenu/UserMenu.js:15:1)
    at __webpack_require__ (/Users/elliothesp/Documents/Code/new-app/build/webpack:/webpack/bootstrap f812a2ff7711f385a97d:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/elliothesp/Documents/Code/new-app/build/webpack:/src/components/App/App.js:16:1)
    at __webpack_require__ (/Users/elliothesp/Documents/Code/new-app/build/webpack:/webpack/bootstrap f812a2ff7711f385a97d:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/elliothesp/Documents/Code/new-app/build/webpack:/src/routes.js:13:1)
```

**Comment by frenzzy** [comment]
oh.. it seems need to mark this lib as non external [here](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L221-L230)

**Comment by Ehesp** [comment]
Okay cheers - not too keen on that approach since I've got quite a few external components. Will stick with the inline approach, thanks!

**Comment by elaijuh** [comment]
I got the same problem, I am using another rc component lib which need me to import css. I have defined  css-loader for it in webpack config but seems doesn't work.

**Comment by SerjoPepper** [comment]
Not work for me too
