### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by aleksandar-b** [kriasoft/react-starter-kit#516]
```
master ~/MyAppReact> npm start

> @ start /home/darko/MyAppReact
> babel-node tools/run start

/home/darko/MyAppReact/tools/start.js:42
            plugins: [...(x.query ? x.query.plugins : []), ['react-transform', {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/home/darko/MyAppReact/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/darko/MyAppReact/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (run.js:27:18)
    at Module._compile (module.js:435:26)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/darko/MyAppReact/npm-debug.log
exit 1

```

I am running Linux Mint

**Comment by frenzzy** [comment]
You need to upgrade [node.js to version 5.x](https://nodejs.org/en/) or [change this line](https://github.com/kriasoft/react-starter-kit/blob/master/package.json#L95) to `es2015`

**Comment by samosale** [comment]
it is really hard to update node on linux

**Comment by frenzzy** [comment]
just use [nvm](https://github.com/creationix/nvm)

**Comment by nickeblewis** [comment]
Yup NVM works for me and I am happy with that,

**Comment by samosale** [comment]
it doesn't work for me

**Comment by nickeblewis** [comment]
What happens if you try:

$ nvm install v5
$nvm use v5.9.0

**Comment by samosale** [comment]
```
v5.9.0 is already installed.
nvm is not compatible with the npm config "prefix" option: currently set to "/home/darko/.npm-packages"
Run `npm config delete prefix` or `nvm use --delete-prefix v5.9.0` to unset it.
Creating default alias: default -> v5 (-> v5.9.0
```)

**Comment by ulani** [comment]
@aleksandar-b   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
