### ISSUE TITLE
`npm run test` fails on Location.js

### ISSUE THREAD

**Issue by gianpaj** [kriasoft/react-starter-kit#522]
`npm run test` runs `npm run lint && jest`

Error:

```
$ npm run test
...
Using Jest CLI v0.9.2, jasmine2, babel-jest
 FAIL  components/App/__tests__/App-test.js
● Runtime Error
TypeError: (0 , _useQueries2.default)(...) is not a function
    at Object.<anonymous> (/Users/gianfranco/temp/MyApp/src/core/Location.js:14:177)
    at Object.<anonymous> (/Users/gianfranco/temp/MyApp/src/components/Link/Link.js:11:41)
    at Object.<anonymous> (/Users/gianfranco/temp/MyApp/src/components/Header/Header.js:13:37)
    at Object.<anonymous> (/Users/gianfranco/temp/MyApp/src/components/App/App.js:13:39)
    at Object.<anonymous> (/Users/gianfranco/temp/MyApp/src/components/App/__tests__/App-test.js:3:36)
```

[/src/core/Location.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/core/Location.js)

``` js
import useQueries from 'history/lib/useQueries';

const location = useQueries(process.env.BROWSER ? createHistory : createMemoryHistory)();
```

**Comment by Bogdaan** [comment]
See 
https://github.com/kriasoft/react-starter-kit/blob/860a403f2483f111f7748ba36aa088af82b5daa6/src/core/Location.js

**Comment by mattroid** [comment]
added history to unmockedModulePathPatterns and it works now. Not sure that is a good idea though.

**Comment by ulani** [comment]
@gianpaj   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
