### ISSUE TITLE
cannot run latest  version

### ISSUE THREAD

**Issue by Kepro** [kriasoft/react-starter-kit#556]
````
ERROR in ./src/client.js
    Module build failed: ReferenceError: [BABEL] /home/kepro/Projects/react-starter-kit/src/client.js: Unknown option: direct.presets
        at Logger.error (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
        at OptionManager.mergeOptions (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
        at OptionManager.init (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
        at File.initOptions (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:147:75)
        at new File (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:137:22)
        at Pipeline.transform (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
        at transpile (/home/kepro/Projects/react-starter-kit/node_modules/babel-loader/index.js:14:22)
        at /home/kepro/Projects/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:145:18
        at ReadFileContext.callback (/home/kepro/Projects/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:28:23)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
     @ multi main
Child
    Time: 269ms
    
    ERROR in ./src/server.js
    Module build failed: ReferenceError: [BABEL] /home/kepro/Projects/react-starter-kit/src/server.js: Unknown option: direct.presets
        at Logger.error (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
        at OptionManager.mergeOptions (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
        at OptionManager.init (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
        at File.initOptions (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:147:75)
        at new File (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:137:22)
        at Pipeline.transform (/home/kepro/Projects/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
        at transpile (/home/kepro/Projects/react-starter-kit/node_modules/babel-loader/index.js:14:22)
        at /home/kepro/Projects/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:145:18
        at ReadFileContext.callback (/home/kepro/Projects/react-starter-kit/node_modules/babel-loader/lib/fs-cache.js:28:23)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
webpack: bundle is now VALID.
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/kepro/Projects/react-starter-kit/build/server.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
````

**Comment by Kepro** [comment]
after delete node_modules and installit again start working
