### ISSUE TITLE
Out-of-the-box test fail running `npm test`

### ISSUE THREAD

**Issue by garajo** [kriasoft/react-starter-kit#562]
Thanks for this starter kit.

I followed the Getting Started instructions, https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md

Everything is working fine, until I get to `npm test`

```
$ npm test

> @ test /home/gajo/local/dev/node/MyApp
> npm run lint && jest


> @ lint /home/gajo/local/dev/node/MyApp
> npm run eslint && npm run jscs && npm run stylelint


> @ eslint /home/gajo/local/dev/node/MyApp
> eslint src tools


> @ jscs /home/gajo/local/dev/node/MyApp
> jscs src tools --verbose


> @ stylelint /home/gajo/local/dev/node/MyApp
> stylelint "src/**/*.scss" --syntax scss


Using Jest CLI v0.10.2, jasmine2, babel-jest
 FAIL  components/App/__tests__/App-test.js
● Runtime Error
Error: ENOENT: no such file or directory, stat './AppSCSSStub'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at Object.<anonymous> (/home/gajo/local/dev/node/MyApp/src/components/App/App.js:12:38)
npm ERR! Test failed.  See above for more details.
```

ubuntu 15.10
node version: v5.8.0
npm version: 3.7.3

**Comment by langpavel** [comment]
I'm experiencing same issue

**Comment by simeg** [comment]
Try upgrading node.js to version 6+.

**Comment by garajo** [comment]
Yes, that was the problem. Works with 6+
