### ISSUE TITLE
Did react starter kit support require.esure ? 

### ISSUE THREAD

**Issue by GENGSHUANGs** [kriasoft/react-starter-kit#563]
To split code

**Comment by GENGSHUANGs** [comment]
WARNING in ./src/client.js
    Critical dependencies:
    105:2-9 require function is used in a way in which dependencies cannot be statically extracted
     @ ./src/client.js 105:2-9
    
    WARNING in ./src/public/browserconfig.xml
    Module parse failed: /Users/ball/site-home/react-starter-kit/src/public/browserconfig.xml Line 1: Unexpected token <
    You may need an appropriate loader to handle this file type.
    | <?xml version="1.0" encoding="utf-8"?>
    | 
    | <browserconfig>
     @ ./src ^\.\/.*$
    
    WARNING in ./src/public/crossdomain.xml
    Module parse failed: /Users/ball/site-home/react-starter-kit/src/public/crossdomain.xml Line 1: Unexpected token <
    You may need an appropriate loader to handle this file type.
    | <?xml version="1.0"?>
    | <!DOCTYPE cross-domain-policy SYSTEM "http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
    | <cross-domain-policy>
     @ ./src ^\.\/.*$
    
    WARNING in ./src/public/favicon.ico
    Module parse failed: /Users/ball/site-home/react-starter-kit/src/public/favicon.ico Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./src ^\.\/.*$
    
    WARNING in ./src/content/about.jade
    Module build failed: SyntaxError: Assigning to rvalue (5:0)
        at Parser.pp.raise (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:943:13)
        at Parser.pp.checkLVal (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1226:12)
        at Parser.pp.parseMaybeUnary (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:192:22)
        at Parser.pp.parseExprOps (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:151:19)
        at Parser.pp.parseMaybeConditional (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:133:19)
        at Parser.pp.parseMaybeAssign (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:110:19)
        at Parser.pp.parseExpression (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:86:19)
        at Parser.pp.parseStatement (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1750:23)
        at Parser.pp.parseTopLevel (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1666:21)
        at Parser.parse (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1636:17)
        at Object.parse (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:905:44)
        at reallyParse (/Users/ball/site-home/react-starter-kit/node_modules/acorn-globals/index.js:30:18)
        at findGlobals (/Users/ball/site-home/react-starter-kit/node_modules/acorn-globals/index.js:45:11)
        at addWith (/Users/ball/site-home/react-starter-kit/node_modules/with/index.js:45:14)
        at parse (/Users/ball/site-home/react-starter-kit/node_modules/jade/lib/index.js:149:9)
        at Object.exports.compileClientWithDependenciesTracked (/Users/ball/site-home/react-starter-kit/node_modules/jade/lib/index.js:256:16)
     @ ./src ^\.\/.*$
    
    WARNING in ./src/content/index.jade
    Module build failed: SyntaxError: Assigning to rvalue (5:0)
        at Parser.pp.raise (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:943:13)
        at Parser.pp.checkLVal (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1226:12)
        at Parser.pp.parseMaybeUnary (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:192:22)
        at Parser.pp.parseExprOps (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:151:19)
        at Parser.pp.parseMaybeConditional (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:133:19)
        at Parser.pp.parseMaybeAssign (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:110:19)
        at Parser.pp.parseExpression (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:86:19)
        at Parser.pp.parseStatement (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1750:23)
        at Parser.pp.parseTopLevel (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1666:21)
        at Parser.parse (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1636:17)
        at Object.parse (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:905:44)
        at reallyParse (/Users/ball/site-home/react-starter-kit/node_modules/acorn-globals/index.js:30:18)
        at findGlobals (/Users/ball/site-home/react-starter-kit/node_modules/acorn-globals/index.js:45:11)
        at addWith (/Users/ball/site-home/react-starter-kit/node_modules/with/index.js:45:14)
        at parse (/Users/ball/site-home/react-starter-kit/node_modules/jade/lib/index.js:149:9)
        at Object.exports.compileClientWithDependenciesTracked (/Users/ball/site-home/react-starter-kit/node_modules/jade/lib/index.js:256:16)
     @ ./src ^\.\/.*$
    
    WARNING in ./src/content/privacy.jade
    Module build failed: SyntaxError: Assigning to rvalue (5:0)
        at Parser.pp.raise (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:943:13)
        at Parser.pp.checkLVal (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1226:12)
        at Parser.pp.parseMaybeUnary (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:192:22)
        at Parser.pp.parseExprOps (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:151:19)
        at Parser.pp.parseMaybeConditional (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:133:19)
        at Parser.pp.parseMaybeAssign (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:110:19)
        at Parser.pp.parseExpression (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:86:19)
        at Parser.pp.parseStatement (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1750:23)
        at Parser.pp.parseTopLevel (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1666:21)
        at Parser.parse (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:1636:17)
        at Object.parse (/Users/ball/site-home/react-starter-kit/node_modules/acorn/dist/acorn.js:905:44)
        at reallyParse (/Users/ball/site-home/react-starter-kit/node_modules/acorn-globals/index.js:30:18)
        at findGlobals (/Users/ball/site-home/react-starter-kit/node_modules/acorn-globals/index.js:45:11)
        at addWith (/Users/ball/site-home/react-starter-kit/node_modules/with/index.js:45:14)
        at parse (/Users/ball/site-home/react-starter-kit/node_modules/jade/lib/index.js:149:9)
        at Object.exports.compileClientWithDependenciesTracked (/Users/ball/site-home/react-starter-kit/node_modules/jade/lib/index.js:256:16)
     @ ./src ^\.\/.*$
    
    WARNING in ./~/sequelize/lib/sequelize.js
    Critical dependencies:
    681:60-73 the request of a dependency is an expression
     @ ./~/sequelize/lib/sequelize.js 681:60-73
    
    WARNING in ./~/sequelize/lib/dialects/mssql/connection-manager.js
    Critical dependencies:
    17:15-71 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/mssql/connection-manager.js 17:15-71
    
    WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
    Critical dependencies:
    18:17-60 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/mysql/connection-manager.js 18:17-60
    
    WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
    Critical dependencies:
    20:14-57 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/postgres/connection-manager.js 20:14-57
    
    WARNING in ./~/sequelize/lib/dialects/sqlite/connection-manager.js
    Critical dependencies:
    22:15-71 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/sqlite/connection-manager.js 22:15-71
    
    WARNING in ./~/express/lib/view.js
    Critical dependencies:
    78:29-56 the request of a dependency is an expression
     @ ./~/express/lib/view.js 78:29-56
    
    WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
    Module not found: Error: Cannot resolve module 'mysql' in /Users/ball/site-home/react-starter-kit/node_modules/sequelize/lib/dialects/mysql
     @ ./~/sequelize/lib/dialects/mysql/connection-manager.js 20:17-33
    
    WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
    Module not found: Error: Cannot resolve module 'pg' in /Users/ball/site-home/react-starter-kit/node_modules/sequelize/lib/dialects/postgres
     @ ./~/sequelize/lib/dialects/postgres/connection-manager.js 22:14-27
    
    WARNING in ./~/with/~/acorn/dist/walk.js
    Critical dependencies:
    1:503-510 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/with/~/acorn/dist/walk.js 1:503-510
    
    WARNING in ./~/acorn/dist/walk.js
    Critical dependencies:
    1:503-510 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/acorn/dist/walk.js 1:503-510
    
    WARNING in ./~/acorn/dist/acorn.js
    Critical dependencies:
    1:478-485 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/acorn/dist/acorn.js 1:478-485
    
    WARNING in ./~/with/~/acorn/dist/acorn.js
    Critical dependencies:
    1:478-485 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/with/~/acorn/dist/acorn.js 1:478-485
    
    WARNING in ./~/encoding/lib/iconv-loader.js
    Critical dependencies:
    9:12-34 the request of a dependency is an expression
     @ ./~/encoding/lib/iconv-loader.js 9:12-34
    
    ERROR in ./src/server.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ./assets in /Users/ball/site-home/react-starter-kit/src
     @ ./src/server.js 67:14-33
    
    ERROR in ./~/enzyme/build/react-compat.js
    Module not found: Error: Cannot resolve module 'react/addons' in /Users/ball/site-home/react-starter-kit/node_modules/enzyme/build
     @ ./~/enzyme/build/react-compat.js 37:16-39
    
    ERROR in ./~/enzyme/build/react-compat.js
    Module not found: Error: Cannot resolve module 'react/lib/ReactContext' in /Users/ball/site-home/react-starter-kit/node_modules/enzyme/build
     @ ./~/enzyme/build/react-compat.js 38:23-56
    
    ERROR in ./~/enzyme/build/react-compat.js
    Module not found: Error: Cannot resolve module 'react/lib/ExecutionEnvironment' in /Users/ball/site-home/react-starter-kit/node_modules/enzyme/build
     @ ./~/enzyme/build/react-compat.js 68:4-45
    
    ERROR in ./~/sequelize/lib/dialects/postgres/hstore.js
    Module not found: Error: Cannot resolve module 'pg-hstore' in /Users/ball/site-home/react-starter-kit/node_modules/sequelize/lib/dialects/postgres
     @ ./~/sequelize/lib/dialects/postgres/hstore.js 3:13-33

**Comment by langpavel** [comment]
Hey, I see esure instead of e**n**sure in your code. Is typo in your code too?

**Comment by GENGSHUANGs** [comment]
My mistake !! ^_^ @langpavel

**Comment by langpavel** [comment]
@GENGSHUANGs I suppose it's working now, isn't it? :-)
