### ISSUE TITLE
After Bundle is Valid then SequelizeDatabaseError: SQLITE_IOERR: disk I/O error appears

### ISSUE THREAD

**Issue by ramonmata** [kriasoft/react-starter-kit#575]
Can't use the latest starter kit on Windows 10 machine

- Windows_NT 10.0.10586 (64-bit)
- node v5.10.1
- npm  v3.8.2

Already tried to install sqlite3 from source with the command below, but no luck
`npm install sqlite3 --build-from-source`

Can you help?
best regards!

**Full Error**
```
N:\react\ReactStarterKit (master)
λ npm start

> @ start N:\react\ReactStarterKit
> babel-node tools/run start

[14:16:22] Starting 'start'...
[14:16:22] Starting 'clean'...
[14:16:22] Finished 'clean' after 40 ms
[14:16:22] Starting 'bound copy'...
[14:16:22] Finished 'bound copy' after 227 ms
webpack built 75ee503275112d592484 in 22780ms
Child
    Time: 22780ms
                           Asset     Size  Chunks             Chunk Names
    main.js?75ee503275112d592484  4.16 MB       0  [emitted]  main
Child
    Time: 19670ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  218 kB       0  [emitted]  main
    ../../server.js.map  237 kB       0  [emitted]  main
webpack: bundle is now VALID.
SequelizeDatabaseError: SQLITE_IOERR: disk I/O error
    at [object Object].Query.formatError (N:\react\ReactStarterKit\node_modules\sequelize\lib\dialects\sqlite\query.js:348:14)
    at Statement.afterExecute (N:\react\ReactStarterKit\node_modules\sequelize\lib\dialects\sqlite\query.js:112:29)
    at Statement.replacement (N:\react\ReactStarterKit\node_modules\sqlite3\lib\trace.js:20:31)
    at Statement.replacement (N:\react\ReactStarterKit\node_modules\sqlite3\lib\trace.js:20:31)
From previous event:
    at executeSql (N:\react\ReactStarterKit\node_modules\sequelize\lib\dialects\sqlite\query.js:103:19)
    at Database.<anonymous> (N:\react\ReactStarterKit\node_modules\sequelize\lib\dialects\sqlite\query.js:262:18)
    at N:\react\ReactStarterKit\node_modules\sequelize\lib\dialects\sqlite\query.js:98:19
From previous event:
    at [object Object].Query.run (N:\react\ReactStarterKit\node_modules\sequelize\lib\dialects\sqlite\query.js:96:13)
    at N:\react\ReactStarterKit\node_modules\sequelize\lib\sequelize.js:845:20
    at N:\react\ReactStarterKit\node_modules\retry-as-promised\index.js:38:21
From previous event:
    at retryAsPromised (N:\react\ReactStarterKit\node_modules\retry-as-promised\index.js:27:10)
    at N:\react\ReactStarterKit\node_modules\sequelize\lib\sequelize.js:844:12
From previous event:
    at Promise.then (N:\react\ReactStarterKit\node_modules\sequelize\lib\promise.js:21:17)
    at [object Object].Model.sync (N:\react\ReactStarterKit\node_modules\sequelize\lib\model.js:1008:6)
    at N:\react\ReactStarterKit\node_modules\sequelize\lib\sequelize.js:1010:20
From previous event:
    at Function.each (N:\react\ReactStarterKit\node_modules\sequelize\lib\promise.js:21:17)
    at N:\react\ReactStarterKit\node_modules\sequelize\lib\sequelize.js:1009:20
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Promise.then (N:\react\ReactStarterKit\node_modules\sequelize\lib\promise.js:21:17)
    at [object Object].Sequelize.sync (N:\react\ReactStarterKit\node_modules\sequelize\lib\sequelize.js:996:6)
    at Object.sync (N:\react\ReactStarterKit\build\webpack:\data\models\index.js:38:10)
    at Object.<anonymous> (N:\react\ReactStarterKit\build\webpack:\server.js:140:8)
    at __webpack_require__ (N:\react\ReactStarterKit\build\webpack:\webpack\bootstrap e26cc244621dc35eca5f:19:1)
    at N:\react\ReactStarterKit\build\webpack:\webpack\bootstrap e26cc244621dc35eca5f:39:1
    at Object.<anonymous> (N:\react\ReactStarterKit\build\webpack:\webpack\bootstrap e26cc244621dc35eca5f:39:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
[14:17:02] The server is running at http://localhost:3000/
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch null UNKNOWN
    at exports._errnoException (util.js:890:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ramon.mata\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     N:\react\ReactStarterKit\npm-debug.log

N:\react\ReactStarterKit (master)
```

**Comment by ramonmata** [comment]
Ok, seems that this problem is not related to ReactStarterKit, but related to sqlite3

I was able to use the **ReactStarterKit** from my local c:\ drive, but not from a mounted drive on Windows

regards
