### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by pierrenel** [kriasoft/react-starter-kit#586]
Followed the instructions, I'm getting:

```
$ npm start

> @ start /Users/pierre/Code/MyApp
> babel-node tools/run start

/Users/pierre/Code/MyApp/tools/start.js:37
            plugins: [...(x.query ? x.query.plugins : []), ['react-transform', {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/Users/pierre/Code/MyApp/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pierre/Code/MyApp/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (run.js:31:18)
    at Module._compile (module.js:435:26)
```

**Comment by koistya** [comment]
@pierrenel can you check please if there is `node_modules/babel-cli` package installed locally in your project?

**Comment by koistya** [comment]
It seems like Babel doesn't pickup settings from [`package.json#L101-114`](https://github.com/kriasoft/react-starter-kit/blob/b24d0146b871eaa7e03cd7d4725dc8a3a29b1d9a/package.json#L101-L114). Do you have `.babelrc` file in the root of your project, if so, it may override settings from `package.json`

**Comment by jaylaw81** [comment]
I have the same issue. This was occurring after a direct clone / install from the repository.

**Comment by frenzzy** [comment]
@jaylaw81 just update [node.js](https://nodejs.org/en/) to v5 or change [this line](https://github.com/kriasoft/react-starter-kit/blob/b24d0146b871eaa7e03cd7d4725dc8a3a29b1d9a/package.json#L104) from `node5` to `es2015`

**Comment by koistya** [comment]
What @frenzzy said :) Feel free to reopen if it doesn't fix the issue.

**Comment by MadeInMoon** [comment]
@frenzzy you save me! many thanks.
