### ISSUE TITLE
sequelize dependency error 'Please install sqlite3 package manually'

### ISSUE THREAD

**Issue by lostlime** [kriasoft/react-starter-kit#587]
Got this error.
```
/Users/corto/mega/MyApp/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24
    throw new Error('Please install sqlite3 package manually');
          ^
Error: Please install sqlite3 package manually
    at new ConnectionManager (/Users/corto/mega/MyApp/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:11)
    at new SqliteDialect (/Users/corto/mega/MyApp/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/Users/corto/mega/MyApp/node_modules/sequelize/lib/sequelize.js:233:18)
    at Object.<anonymous> (/Users/corto/mega/MyApp/build/webpack:/data/sequelize.js:13:19)
    at __webpack_require__ (/Users/corto/mega/MyApp/build/webpack:/webpack/bootstrap 6d1086b2a4d5e521e79e:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/corto/mega/MyApp/build/webpack:/data/models/index.js:10:1)
    at __webpack_require__ (/Users/corto/mega/MyApp/build/webpack:/webpack/bootstrap 6d1086b2a4d5e521e79e:19:1)
    at Object.<anonymous> (/Users/corto/mega/MyApp/build/webpack:/core/passport.js:18:1)
    at __webpack_require__ (/Users/corto/mega/MyApp/build/webpack:/webpack/bootstrap 6d1086b2a4d5e521e79e:19:1)
    at Object.<anonymous> (/Users/corto/mega/MyApp/build/webpack:/server.js:21:1)
    at __webpack_require__ (/Users/corto/mega/MyApp/build/webpack:/webpack/bootstrap 6d1086b2a4d5e521e79e:19:1)
    at /Users/corto/mega/MyApp/build/webpack:/webpack/bootstrap 6d1086b2a4d5e521e79e:39:1
    at Object.<anonymous> (/Users/corto/mega/MyApp/build/webpack:/webpack/bootstrap 6d1086b2a4d5e521e79e:39:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```
OSX 10.11 x64
No matter - node v4 or v5 still got this error

**Comment by koistya** [comment]
@lostlime do you have [this dependency](https://github.com/kriasoft/react-starter-kit/blob/b24d014/package.json#L38) installed locally?

**Comment by lostlime** [comment]
Thanks! worked now

**Comment by jt3k** [comment]
please reopen this issue

I see this problem after installing node v.6 

When I downgrade to v node.5 problem fixed

**Comment by langpavel** [comment]
Today I see issue with node6 with different package using native dependency. Is this can be source of all the bad? Not sure if something common with node-gyp

**Comment by langpavel** [comment]
Citation from [nodejs.org blog for v6.0.0](https://nodejs.org/en/blog/release/v6.0.0/)
> The release notes below are annotated with the main breaking changes that warrant the jump to v6. Note that because this new version of Node.js is shipping with a new version of V8, you will need to recompile any native addons you have already installed or you will receive a runtime error when trying to load them. Use npm rebuild or simply remove your node_modules directory and npm install from scratch.

**Comment by Adam-Burke** [comment]
I have this issue and have tried rebuilding. Also I have the package installed.

**Comment by langpavel** [comment]
@Adam-Burke Do you have all prerequisites installed? Like `node-gyp`?

**Comment by bhushankumarl** [comment]
@koistya 
Not working even after installing locally, I am using Node 4.4 v

**Comment by langpavel** [comment]
Use `node >= 5`

**Comment by bhushankumarl** [comment]
After firing this command :
npm rebuild

No, It's working fine.

**Comment by craigcolesspindrift** [comment]
only worked after firing `$ npm rebuild` for me, also got this when trying to install on node v6
`npm ERR! peerinvalid The package react@0.14.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer graphiql@0.5.0 wants react@^0.14.0
npm ERR! peerinvalid Peer react-dom@0.14.7 wants react@^0.14.7
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer redbox-react@1.3.2 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer enzyme@2.4.1 wants react@0.13.x || 0.14.x || ^15.0.0-0`

**Comment by SebastianGuerreroCardenas** [comment]
I need help, I havebeen stuck looking at this issue. I am running on Electron, node 6. and i have tried all the rebuilds and none seem to work.

**Comment by daltondiaz** [comment]
@craigcolesspindrift Thank you, worked after rebuild like you said!

**Comment by stephanMettler** [comment]
This may happen after changing your node version.

After changing node version you may have to rebuild some of your local  and *global modules !

**Comment by Nahasean94** [comment]
Tried rebuilding npm but dint help. I want to use sqlite3 with sequelize in electron, using node version 6.10.2. Please help.

**Comment by langpavel** [comment]
First, copy all outside (make a full backup)
Then run:
 - `git reset --hard`
 - `git clean -dfX`
 - `git clean -dfx`
 - `rm ~/.babel.json`
You should be clean of all possible side effects

**Comment by Nahasean94** [comment]
@langpavel i had not even made a git repo for this project. I just created a new electron project, then installed the sequelize and sqlite3 modules and tried to run the app, and the error appeared

**Comment by Nahasean94** [comment]
I used this blog's directions and it worked for me [https://web.archive.org/web/20160417032623/http://verysimple.com/2015/05/30/using-node_sqlite3-with-electron](url)

**Comment by langpavel** [comment]
@Nahasean94 Is this working for you? There is no real need for sqlite in react-starter-kit nor sequelize. I fact I hate these dependencies because they are suggesting wrong way of doing database binding... :smiling_imp:

**Comment by Nahasean94** [comment]
Yea this worked for me

**Comment by bradmalloy** [comment]
Looking around, none of the above worked for me.  What did work was installing both `sqlite3` and `sqlite` and switching to Node 5.12.0.

**Comment by sazzeb** [comment]
I hate to be a bearer of bad news but it is not working for mr

**Comment by kevingilbert100** [comment]
This should be re-opened

**Comment by odykyi** [comment]
Use ```npm rebuild```

**Comment by byrontuckett** [comment]
This worked for me using electron-rebuild.

./node_modules/.bin/electron-rebuild -w sqlite3

**Comment by marianolg** [comment]
@byrontuckett's solution is the right one for projects using sequelize with electron

**Comment by langpavel** [comment]
@byrontuckett @marianolg Are you using RSK as base bor standalone electron–based app? Interesting! I'm sure you are using same code in web app too!

**Comment by byrontuckett** [comment]
@langpavel Not using the RSK.  Just a vanilla electron canvas, then pulled in Sequelize to work with MSSQL.

**Comment by hbgdPro** [comment]
Properly installing python worked in my case. [Windows]

**Comment by swetansh** [comment]
@hbgdPro installed python on my windows but still not working.

**Comment by hbgdPro** [comment]
@swetansh Install windows-build-tools

**Comment by swetansh** [comment]
@hbgdPro Thanks . It worked but I have to install windows-build-tools.
👍

**Comment by Nightspeedy** [comment]
Have the same issue, none of the above works for me, my OS is Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-36-generic x86_64)

Anyone able to help?
```
        throw new Error('Please install sqlite3 package manually');
        ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/home/Kokoku Nashi/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
    at new SqliteDialect (/home/Kokoku Nashi/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/Kokoku Nashi/node_modules/sequelize/lib/sequelize.js:239:20)
    at Object.<anonymous> (/home/Kokoku Nashi/index.js:20:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by ErgoTobi** [comment]
I have the same issue but with postgres... I tried everything. The connection works in a single .js file but when building the app with electron the error appears :

`Uncaught Error: Please install pg package manually
    at ConnectionManager._loadDialectModule (connection-manager.js:81)
    at new ConnectionManager (connection-manager.js:18)
    at new PostgresDialect (index.js:14)
    at new Sequelize (sequelize.js:241)
    at Module../src/app/data.service.ts (data.service.ts:11)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/components/home/home.component.ts (main.js:6958)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app-routing.module.ts (main.js:6374)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:78)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:78)
    at Object.0 (polyfills.ts:84)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.js:1`

`const Sequelize = require('sequelize');
const connection = new Sequelize('postgres', 'postgres', 'password', {
    host: 'localhost',
    dialect: 'postgres',
    pool: {
        max: 9,
        min: 0,
        idle: 10000
    }
});`

**Comment by jt3k** [comment]
@Nightspeedy  make sure you are using the fresh node version 

the fresh node has version 8 9 10 11

**Comment by kauffmanes** [comment]
I am using the latest version of node and I am getting this as well. I can get it to work if I just start my node project regularly (node index.js) but I'm trying to integrate with Docker and this issue has come back.

**Comment by Yago-Tavares** [comment]
Same problem 

The sqlite3 is installed in my ec2 instance
 `$ sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668` 

But when I try run `npm start` return this:

`ERROR: Please install sqlite3 package manually`

**Comment by piglovesyou** [comment]
@Yago-Tavares Would you tell me one of these works for you?
1. `npm rebuild sqlite3 --build-from-source` and `yarn start` again
2. `npm rebuild` and `yarn start` again
3. `rm -rf node_modules; yarn cache clean; yarn install` and `yarn start` again

**Comment by eignil** [comment]
Sames to be the problem of webpack. Sequelize load the dialect with "return require(moduleName);". The moduleName here is a variable, but this is not working with webpack. 
In node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:
      const sql = require('sqlite3')  //This is working
      console.log(sql)
      console.log(moduleName)
      const sql1 = require(moduleName)  //This is not working.
      console.log(sql1)
