### ISSUE TITLE
Error: Cannot find module './assets'

### ISSUE THREAD

**Issue by FakhruddinAbdi** [kriasoft/react-starter-kit#599]
RSK don't create assest.js in the build directory and therefore it's giving this error:
```
Error: Cannot find module './assets'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/external "./assets":1:1)
    at __webpack_require__ (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:19:1)
    at Object.<anonymous> (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:39:1)
    at __webpack_require__ (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:19:1)
    at /Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:39:1
    at Object.<anonymous> (/Users/fakhruddinabdi/WebstormProjects/zeyton/build/webpack:/webpack/bootstrap e4b21e6664c8c9d0b071:39:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
```

I was working on a project for about 5 month without problem 
But today, due to some change, i have faced this error 

some recently changes: 
1- installing jwt-decode package 
2- refactoring some component name
3- some change on the components 

it didn't resolve even by checking out the previous git working commit

NODE : 5.6
NPM 3.6

**Comment by langpavel** [comment]
@FakhruddinAbdi Why you close this without any note? :-)

**Comment by mdarby** [comment]
Suddenly seeing this as well. Digging.

**Comment by frenzzy** [comment]
@mdarby look at the previous error, looks like client-side code was not built successfully

**Comment by teonji** [comment]
did someone find some fix for this issues?
this happen at least once every day :(

**Comment by langpavel** [comment]
@teonji Syntax error, invalid import, any fatal error can prevent `assets` from being built...

**Comment by teonji** [comment]
yep, i can understand, but i can't figure out why sometimes happen instead of every time.
i mean, when this happen, every time i just run same command again and that's work..
i just avoid to do this in production, you can immagine.. :)

**Comment by langpavel** [comment]
@teonji there is no build step in production, `assets.js` is static file so this cannot happen in production ;-)

**Comment by teonji** [comment]
yes sorry, u r right..
but it is not nice to receive this during dev.
did u find some trick to avoid it?
i think that sometimes the build finish before assets's build..do u know an option to sync this?

**Comment by langpavel** [comment]
> did u find some trick to avoid it?

Hmm. I'm not experiencing this too often, may be because I don't save files until all code is linted successfully in my editor.
