### ISSUE TITLE
Both `gulp` and `gulp build` fail (in npm v1.4.28)

### ISSUE THREAD

**Issue by zerkms** [kriasoft/react-starter-kit#67]
vagrant@vagrant-ubuntu-trusty-64:~/src/react-starter-kit$ gulp
    [21:49:29] Using gulpfile ~/src/react-starter-kit/gulpfile.js
    [21:49:29] Starting 'serve'...
    [21:49:29] Starting 'clean'...
    [21:49:29] Finished 'clean' after 16 ms
    [21:49:29] Starting 'build'...
    [21:49:29] Starting 'vendor'...
    [21:49:29] Starting 'assets'...
    [21:49:29] Starting 'styles'...
    [21:49:29] 'styles' errored after 7.35 ms
    [21:49:29] Error: Cannot find module 'readable-stream/transform'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/home/vagrant/src/react-starter-kit/node_modules/gulp-plumber/node_modules/through2/through2.js:1:79)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
    [21:49:29] 'build' errored after 78 ms
    [21:49:29] Error: [object Object]
        at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
        at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
        at Gulp.emit (events.js:117:20)
        at Gulp.Orchestrator._emitTaskDone (/home/vagrant/src/react-starter-kit/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
        at /home/vagrant/src/react-starter-kit/node_modules/gulp/node_modules/orchestrator/index.js:275:23
        at finish (/home/vagrant/src/react-starter-kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
        at cb (/home/vagrant/src/react-starter-kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
        at finish (/home/vagrant/src/react-starter-kit/node_modules/run-sequence/index.js:48:5)
        at Gulp.onError (/home/vagrant/src/react-starter-kit/node_modules/run-sequence/index.js:55:4)
        at Gulp.emit (events.js:117:20)
    [21:49:30] nodemon v1.3.6
    [21:49:30] nodemon to restart at any time, enter `rs`
    [21:49:30] nodemon watching: /home/vagrant/src/react-starter-kit/build/server.js

    [21:49:30] nodemon starting `node build/server.js`
    [21:49:30] Finished 'serve' after 219 ms
    [21:49:30] Finished 'vendor' after 187 ms
    [21:49:30] 'assets' all files 133.07 kB
    [21:49:30] Finished 'assets' after 198 ms

    module.js:340
        throw err;
              ^
    Error: Cannot find module '/home/vagrant/src/react-starter-kit/build/server.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3
    [21:49:30] nodemon crashed
    [21:49:30] nodemon app crashed - waiting for file changes before starting...

It's `npm v1.4.28` and `nodejs v0.10.33` installed.

Other environment details: just a clean instance of `ubuntu trusty` with just `nodejs` and `npm` installed

Upgrading `npm` to `v2.5.0` fixed it though

**Comment by koistya** [comment]
https://github.com/kriasoft/react-starter-kit/commit/a4120caab47ddf5d11ce6aa42d237566ecdfebe9 <- Does it fix the issue?

**Comment by zerkms** [comment]
It's a bit tricky to `node install` on `v1.4` due to https://github.com/npm/npm/issues/6309 issue, but seems like this exact change does fix it. Thanks.
