### ISSUE TITLE
*major* App not starting for feature/redux branch , Ubuntu 14

### ISSUE THREAD

**Issue by sap9433** [kriasoft/react-starter-kit#699]
Git cloned , npm installed , ran server , it started and failed with following error

```
 ~/Desktop/react-starter-kit  ➦ 02393af  npm run start

> @ start /home/saptarshichatterjee/Desktop/react-starter-kit
> babel-node tools/run start

[11:23:52] Starting 'start'...
[11:23:52] Starting 'clean'...
[11:23:52] Finished 'clean' after 62 ms
[11:23:52] Starting 'bound copy'...a
[11:23:52] Finished 'bound copy' after 140 ms
webpack built 35dc329f8973c4eb4c26 in 4644ms
Child
    Time: 4644ms
                           Asset     Size  Chunks             Chunk Names
    main.js?35dc329f8973c4eb4c26  4.39 MB       0  [emitted]  main
Child
    Time: 4089ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  230 kB       0  [emitted]  main
    ../../server.js.map  249 kB       0  [emitted]  main
webpack: bundle is now VALID.
[11:23:58] The server is running at http://localhost:3000/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch build/content ENOSPC
    at exports._errnoException (util.js:953:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at createFsWatchInstance (/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:117:15)

npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin/node" "/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin/npm" "run" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saptarshichatterjee/Desktop/react-starter-kit/npm-debug.log
```

Here is npm-debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin/node',
1 verbose cli   '/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /home/saptarshichatterjee/.nvm/versions/node/v6.2.0/lib/node_modules/npm/bin/node-gyp-bin:/home/saptarshichatterjee/Desktop/react-starter-kit/node_modules/.bin:/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin:/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle @~start: CWD: /home/saptarshichatterjee/Desktop/react-starter-kit
11 silly lifecycle @~start: Args: [ '-c', 'babel-node tools/run start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd /home/saptarshichatterjee/Desktop/react-starter-kit
17 error Linux 3.19.0-59-generic
18 error argv "/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin/node" "/home/saptarshichatterjee/.nvm/versions/node/v6.2.0/bin/npm" "run" "start"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error @ start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script 'babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by phpgit** [comment]
the same issue here, windows 7

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart @
6 info start @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec start script
9 verbose stack Error: @ start: `babel-node tools/run start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd D:\www\2016\mobilmech.com.au\react_starter_csbook\react_starter_csbook
12 error Windows_NT 6.1.7601
13 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.1
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error @ start: `babel-node tools/run start`
17 error Exit status 1
18 error Failed at the @ start script 'babel-node tools/run start'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     babel-node tools/run start
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by tobiasmuehl** [comment]
I believe this is a problem where some files are locked by the filesystem.
Refer to [this StackOverflow](http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc), maybe `npm dedupe` will fix it?

**Comment by simonseddon** [comment]
Had the same problem. Upgrading node from 4.x to 6.x (latest stable) fixed it, for me. After doing so, you may also have to remove node_modules: `rm -rf node_modules` and start from the top: `npm install`. Doing this got `npm start` to work, for me.

**Comment by sap9433** [comment]
1. echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

2.  goto `/etc/security/limits.conf` and at this line in the end `ur-Use-rName hard nofile 999999`
