### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by shawn-dsz** [kriasoft/react-starter-kit#704]
I've done ```npm i```

but I'm getting the following error when ```npm start``` 
 ```
:~/react-starter-kit$ npm start 

> @ start /home/shawn/react-starter-kit
> babel-node tools/run start

/home/shawn/react-starter-kit/tools/start.js:37
            plugins: [...(x.query ? x.query.plugins : []), ['react-transform', {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/home/shawn/react-starter-kit/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/shawn/react-starter-kit/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (run.js:31:18)
    at Module._compile (module.js:409:26)

```

**Comment by tpina** [comment]
You need to be running Node.js v5.0 or newer

**Comment by biegleux** [comment]
add es2015 babel preset in [package.json](https://github.com/kriasoft/react-starter-kit/blob/master/package.json#L112)

**Comment by dopeboy** [comment]
Thanks @tpina - following your advice fixed the problem.

**Comment by immuzov** [comment]
Check this: https://github.com/kriasoft/react-starter-kit/issues/586#issuecomment-211369093

**Comment by langpavel** [comment]
Feel free to reopen if this persist
