### ISSUE TITLE
npm run fail

### ISSUE THREAD

**Issue by apopa116** [kriasoft/react-starter-kit#751]
```
$ npm ls 
npm ERR! extraneous: lib /home/apopa/Repos/MyApp/node_modules/postcss-import/node_modules/pkg-resolve/node_modules/jspm/node_modules/lib
npm ERR! error in /home/apopa/Repos/MyApp/node_modules/postcss-import/node_modules/pkg-resolve/node_modules/jspm/node_modules/lib: ENOENT: no such file or directory, open '/home/apopa/Repos/MyApp/node_modules/postcss-import/node_modules/pkg-resolve/node_modules/jspm/node_modules/lib/package.json'

$ npm i
npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN enoent ENOENT: no such file or directory, open '/home/apopa/Repos/MyApp/node_modules/postcss-import/node_modules/pkg-resolve/node_modules/jspm/node_modules/lib/package.json'

$ npm start
webpack: bundle is now VALID.

/home/apopa/Repos/MyApp/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
            ^
Error: Please install sqlite3 package manually
    at new ConnectionManager (/home/apopa/Repos/MyApp/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/home/apopa/Repos/MyApp/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/home/apopa/Repos/MyApp/node_modules/sequelize/lib/sequelize.js:233:18)
    at Object.<anonymous> (/home/apopa/Repos/MyApp/build/webpack:/data/sequelize.js:13:19)
    at __webpack_require__ (/home/apopa/Repos/MyApp/build/webpack:/webpack/bootstrap f3b8ace48d394feedac3:19:1)
    at Object.module.exports.Object.defineProperty.value (/home/apopa/Repos/MyApp/build/webpack:/data/models/index.js:10:1)
    at __webpack_require__ (/home/apopa/Repos/MyApp/build/webpack:/webpack/bootstrap f3b8ace48d394feedac3:19:1)
    at Object.<anonymous> (/home/apopa/Repos/MyApp/build/webpack:/core/passport.js:18:1)
    at __webpack_require__ (/home/apopa/Repos/MyApp/build/webpack:/webpack/bootstrap f3b8ace48d394feedac3:19:1)
    at Object.<anonymous> (/home/apopa/Repos/MyApp/build/webpack:/server.js:25:1)
    at __webpack_require__ (/home/apopa/Repos/MyApp/build/webpack:/webpack/bootstrap f3b8ace48d394feedac3:19:1)
    at /home/apopa/Repos/MyApp/build/webpack:/webpack/bootstrap f3b8ace48d394feedac3:39:1
    at Object.<anonymous> (/home/apopa/Repos/MyApp/build/webpack:/webpack/bootstrap f3b8ace48d394feedac3:39:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
/home/apopa/Repos/MyApp/tools/runServer.js:75
        throw new Error('Server terminated unexpectedly with code: ' + code + ' signal: ' + signal);
        ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.<anonymous> (runServer.js:53:15)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/apopa/Repos/MyApp/npm-debug.log
```

Followed @jahmaiosullivan instructions from #741 but without luck.
Any ideas?

**Comment by apopa116** [comment]
Had node v4 when I built the packages, then updated to v6. Had to `npm rebuild`. 
Fixed.
