### ISSUE TITLE
The package react does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by totouraMan** [kriasoft/react-starter-kit#757]
Trying with no succeed. Please help. After following the instructions I cant run the server.
**What is wrong?**

```
347 verbose validateInstall loading /Users/mobilesail/Documents/reactDiego/MyApp/package.json for validation
348 verbose stack Error: The package react does not satisfy its siblings' peerDependencies requirements!
348 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:125:32
348 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:267:7
348 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
348 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
348 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
348 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
348 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
348 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
348 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
348 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
349 verbose cwd /Users/mobilesail/Documents/reactDiego/MyApp
350 error Darwin 14.5.0
351 error argv "node" "/usr/local/bin/npm" "install"
352 error node v0.12.5
353 error npm  v2.11.2
354 error code EPEERINVALID
355 error peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
355 error peerinvalid Peer graphiql@0.7.2 wants react@^15.0.1
355 error peerinvalid Peer react-dom@15.1.0 wants react@^15.1.0
355 error peerinvalid Peer react-addons-test-utils@15.2.1 wants react@^15.2.1
355 error peerinvalid Peer redbox-react@1.2.10 wants react@^0.14.0 || ^15.0.0
355 error peerinvalid Peer enzyme@2.4.1 wants react@0.13.x || 0.14.x || ^15.0.0-0
356 verbose exit [ 1, true ]
```

**Comment by marcstober** [comment]
I had this issue too. At first I thought I could solve it by changing a dependency but the I ran into some other issues and upgrade Node from v.4.7 to v.6 and started over, and the problem went away. I know that the way peer dependencies are handled changed somehow in newer Node version so maybe that was the issue.

**Comment by bblue** [comment]
Updating to Node v6 fixed the issue for me as well

**Comment by lokeshreddy135** [comment]
i'm having the same issue with node 6.3.1.  
`├── UNMET PEER DEPENDENCY eslint@2.13.1
└─┬ UNMET PEER DEPENDENCY react@0.14.7
  └─┬ envify@3.4.1
    └─┬ jstransform@11.0.3
      └─┬ commoner@0.10.4
        └── glob@5.0.15

npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.
npm WARN react-addons-test-utils@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm ERR! code 1`

**Comment by langpavel** [comment]
Current version of RSK is using react and react-dom packages at version 15.3.1.
