### ISSUE TITLE
Error with LESS files for Material based UI (Essence)

### ISSUE THREAD

**Issue by drobertson123** [kriasoft/react-starter-kit#762]
I am using parts of essence-core in my web app. It uses LESS files for its style sheets. When I use`npm start` I receive this error;

ERROR in D:/Documents/dev/Test Site/~/essence-core/lib/highlighter/highlighter.less
    Module parse failed: D:\Documents\dev\Test Site\node_modules\essence-core\lib\highlighter\highlighter.less Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected character '@' (1:0)

I have installed less-loader, but I am stumped on the proper way to configure the system to handle the LESS files.

Any help would be appreciated.

BTW - Great work on this kit.

**Comment by drobertson123** [comment]
I have managed to get the LESS loader configured but I am still getting an error;

`webpack: bundle is now VALID.
D:\Documents\dev\Test Site\node_modules\essence-core\lib\block\block.less:2
@import '../less/mixins.less';
^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Documents\dev\Test Site\node_modules\essence-core\lib\block\block.js:15:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
D:\Documents\dev\Test Site\tools\runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
        ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (tools\runServer.js:53:15)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`

**Comment by drobertson123** [comment]
I created a fresh project that specifically isolates this issue in the hope someone may be able to help me.

@koistya asked for the webpack.config.js file. That can be found here;

http://codepen.io/drobertson123/pen/JKvVrJ

and the entire project as it stood when the errors showed up can be downloaded as a RAR file here;

https://drive.google.com/file/d/0B7AY-Oy8jP_WUkFfeEJCRFlycHM/view?usp=sharing

This project has the LESS modifications to the webpack.config.js file, similar to the SASS instructions. It also has react-essence added to the project. Inside Header.js I added a few <Block> items from essence to create the error.

npm start should give you a view of the error.

**Comment by vince-fly** [comment]
@drobertson123 , i have the same issuses,mixin function "SyntaxError",but @variable is ok.

**Comment by ulani** [comment]
@drobertson123   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
