### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by srinivaasang1** [kriasoft/react-starter-kit#783]
am getting this error.

import 'babel-polyfill';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

package.json
-------------------
"dependencies": {
    "babel-core": "^6.11.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-runtime": "6.9.2",
    "bluebird": "3.4.0",
    "body-parser": "1.15.1",
    "browser-sync": "^2.13.0",
    "classnames": "2.2.5",
    "cookie-parser": "1.4.3",
    "core-js": "2.4.0",
    "eventemitter3": "1.2.0",
    "express": "4.13.4",
    "express-graphql": "0.5.3",
    "express-jwt": "3.4.0",
    "fastclick": "1.0.6",
......}

"babel": {
    "presets": [
      "react",
      "node5",
      "stage-0",
      "es2015"
    ],
    "env": {
      "test": {
        "plugins": [
          "rewire"
        ]
      }
    }
  },

**Comment by langpavel** [comment]
Do you using babel-node? Have you well configured Babel?
