### ISSUE TITLE
when i run npm start , error

### ISSUE THREAD

**Issue by kittBoy** [kriasoft/react-starter-kit#810]
```
D:\test\p\react-starter-kit-master\react-starter-kit-master>npm start

> @ start D:\test\p\react-starter-kit-master\react-starter-kit-master
> babel-node tools/run start

[15:32:03] Starting 'start'...
[15:32:03] Starting 'clean'...
[15:32:03] Finished 'clean' after 145 ms
[15:32:03] Starting 'bound copy'...
[15:32:03] Finished 'bound copy' after 137 ms
webpack built f1dc8a6af61e6e0d93a7 in 4852ms
Child
    Time: 4852ms

    ERROR in ./~/.css-loader@0.23.1?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/.postcss-loader@0.9.1?pack=default!./~/.c
ss-loader@0.23.1/lib/css-base.js
    D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.css-loader@0.23.1\lib\css-base.js:7:2: Unknown word
    module.exports = function() {
        var list = [];
     ^


    ERROR in ./~/.css-loader@0.23.1?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/.postcss-loader@0.9.1?pack=default!./~/.c
ss-loader@0.23.1/lib/css-base.js
    Module build failed: TypeError: Cannot read property 'toString' of undefined
        at new Input (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\input.js:58:23)
        at parse (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\parse.js:21:17)
        at new LazyResult (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\lazy-result.js:80:24)
        at Processor.process (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\processor.js:200:12)
        at processCss (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.css-loader@0.23.1\lib\processCss.js:188:11)
        at Object.module.exports (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.css-loader@0.23.1\lib\loader.js:24:2)
     @ ./~/.css-loader@0.23.1/lib/css-base.js 2:18-221 18:6-26:8 19:18-221
Child
    Time: 4248ms
            Asset    Size  Chunks             Chunk Names
        server.js  198 kB       0  [emitted]  main
    server.js.map  214 kB       0  [emitted]  main

    ERROR in ./~/.css-loader@0.23.1?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/.postcss-loader@0.9.1?pack=default!./~/.c
ss-loader@0.23.1/lib/css-base.js
    D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.css-loader@0.23.1\lib\css-base.js:7:2: Unknown word
    module.exports = function() {
        var list = [];
     ^


    ERROR in ./~/.css-loader@0.23.1?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/.postcss-loader@0.9.1?pack=default!./~/.c
ss-loader@0.23.1/lib/css-base.js
    Module build failed: TypeError: Cannot read property 'toString' of undefined
        at new Input (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\input.js:58:23)
        at parse (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\parse.js:21:17)
        at new LazyResult (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\lazy-result.js:80:24)
        at Processor.process (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.postcss@5.1.2\lib\processor.js:200:12)
        at processCss (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.css-loader@0.23.1\lib\processCss.js:188:11)
        at Object.module.exports (D:\test\p\react-starter-kit-master\react-starter-kit-master\node_modules\.css-loader@0.23.1\lib\loader.js:24:2)
     @ ./~/.css-loader@0.23.1/lib/css-base.js 2:18-221
webpack: bundle is now VALID.
```

**Comment by langpavel** [comment]
- [ ] Use node 6, (RSK needs node 5 at min)
- [ ] Be sure you have all prerequisities installed, follow [node-gyp installation instructions](https://github.com/nodejs/node-gyp#installation)
- [ ] Drop `node_modules`, install it again

Let us know if this help. If not, please reopen
