### ISSUE TITLE
Multiple entries errors

### ISSUE THREAD

**Issue by azz0r** [kriasoft/react-starter-kit#811]
Hello,

I'm trying to compile extra bundles but I get issues with the below error

```
[10:14:21] Finished 'bound copy' after 364 ms
TypeError: request.replace is not a function
    at node_modules/webpack/lib/NormalModuleFactory.js:72:27
    at node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at node_modules/webpack/lib/Compilation.js:214:11
    at node_modules/webpack/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (node_modules/webpack/lib/Compilation.js:185:8)
    at Compilation.processModuleDependencies (node_modules/webpack/lib/Compilation.js:170:7)
    at Compilation.moduleReady (node_modules/webpack/lib/Compilation.js:412:9)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:408:16)
    at node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (node_modules/webpack/lib/Compilation.js:122:12)
```

webpack config:

``` javascript
  entry: {
    server: './server.js',
    excess: './excess.js'
  },
```

``` javascript
  entry: {
    client: './client.js',
    excess: './excess.js'
  },
```

webpack: 1.13.2

Has anyone got a working example of multiple entry points in React Starter Kit?

**Comment by tamerelsayed** [comment]
I've the same issue had to use only `./client.js` to make it work with `npm run start`

**Comment by frenzzy** [comment]
Just update [tools/start.js](https://github.com/kriasoft/react-starter-kit/blob/39dfad685c6e8cf221ece74ab7df71412efad291/tools/start.js#L33) too, for example if you need HMR only for `client` entry, you can change the line to:
```js
config.entry.client = [
  'react-hot-loader/patch',
  'webpack-hot-middleware/client',
  config.entry.client
]
```

**Comment by koistya** [comment]
I think we need to change `entry: 'client.js'` in `webpack.config.js` to:

```js
entry: [
  'client.js',
]
```

And `config.entry.client = [...]` in `tools/start.js` to:

```js
config.entry = ['react-hot-loader/patch', 'webpack-hot-middleware/client', ...config.entry];
```

**Comment by jshjohnson** [comment]
The solution @frenzzy suggested didn't work for me. I've managed to get slightly further by doing the following instead:

```js
if (Array.isArray(config.entry)) {
  config.entry.unshift('webpack-hot-middleware/client');
} else if (Array.isArray(config.entry.app)) {
  config.entry.app.unshift('webpack-hot-middleware/client');
} else {
  config.entry = ['webpack-hot-middleware/client'];
}
```

This solves the error and allows Webpack to successfully build the appropriate files, but the server never starts.

This never fires:

```js
bundler.plugin('done', () => handleServerBundleComplete());
```

Any ideas?

**Comment by frenzzy** [comment]
@jshjohnson switch to using the master branch, there are `start` script patching are not required and vendors already moved to a separate chunk. Also there are easy to add more entry points:
```js
entry: {
  /* ... */
  yourEntry: './path/to/entry.js'
}
```

**Comment by jshjohnson** [comment]
@frenzzy Thanks for your response. I updated my `start`script to the one in master but have the same issue. Webpack builds fine but the server never starts.
