### ISSUE TITLE
Error: listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by musdy** [kriasoft/react-starter-kit#817]
[16:15:30] The server is running at http://localhost:3000/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000

I continuously get this error. Even though nothing else is running on port 3000.
I am running Node v 6.4.0 and NPM v 3.10.3

Any idea on how to get this to work?

**Comment by langpavel** [comment]
@musdy Looks like something may listen on IPv6 port, are you sure that anything is there?
Reopen if you discover that I'm wrong and this is really RSK on node issue

**Comment by eysi09** [comment]
I'm seeing the same issue, running Node v 6.9.1 and NPM v 3.10.8 after a fresh git clone from master.

**Comment by medv** [comment]
Run `lsof -i :3000` to see what process is using port 3000 and kill it before running `npm start`.

**Comment by eysi09** [comment]
I did that and I have no processes using port 3000. Seems to be an issue with browser-sync, in particular `at module.exports.plugin (/PATH/TO/PROJECT/node_modules/browser-sync/lib/server/index.js:36:25`.

As I said above, my project should be up to date with the current master branch and I haven't made any local changes.

**Comment by langpavel** [comment]
This error comes directly from `node` core and it means it cannot start listening on this port. Check other applications, security programs etc.

Also check your own tweaks if you didn't try start server twice in code...

**Comment by jweboy** [comment]
```js
if (!module.parent) { // add this judgment
  // 监听3000端口
  app.listen(3000, () => {
    console.log('listen on 3000')
  })
}
```

**Comment by MissCupcake9** [comment]
i got this error recently 

$ node server.js
[0.165]: 5000 x 5000 room initalized.  Max food: 250, max nest food: 17.112765133926963.
[2.987]: Preparing definition export.
[2.993]: Mockups written to /app/src/server/../client/json/mockups.json!
[2.994]: Building client version hash, reading from /app/src/server/../client/js/app.js and /app/src/server/lib/definitions.js...
[3.052]: Placing 37 obstacles!
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at Server.listen (net.js:1409:5)
    at websockets (/app/src/server/server.js:5356:16)
    at Object.<anonymous> (/app/src/server/server.js:5365:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)

i fixed it by putting // and undo it but now it didnt work after ity has restart

**Comment by langpavel** [comment]
Something is using port 3000 (Check if you stop previous instance, check if you are not trying instantiate server twice).
Only you are responsible for your machine

**Comment by CHAMOD** [comment]
You should check whether your 3000 port is currently used. it then you should kill than process.
