### ISSUE TITLE
Error "Cannot resolve module" when import a external css file contains `url(image.png)`

### ISSUE THREAD

**Issue by manhhailua** [kriasoft/react-starter-kit#825]
I'm using React-Starter-Kit and trying to integrate with AdminLTE. When I imported a css from AdminLTE I got this error.

RSK always searches for the image as a module from the component folder, in this case `/home/nginx/domains/vps.manhhailua.com/public/src/routes/login`.

```
webpack built a436c24672c3c331acc3 in 7118ms
Child
    Time: 7118ms

    ERROR in ./~/css-loader?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/postcss-loader?pack=default!./src/routes/login/Login.css
    Module not found: Error: Cannot resolve module 'blue.png' in /home/nginx/domains/vps.manhhailua.com/public/src/routes/login
     @ ./~/css-loader?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/postcss-loader?pack=default!./src/routes/login/Login.css 6:1349-1368

    ERROR in ./~/css-loader?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/postcss-loader?pack=default!./src/routes/login/Login.css
    Module not found: Error: Cannot resolve module 'blue@2x.png' in /home/nginx/domains/vps.manhhailua.com/public/src/routes/login
     @ ./~/css-loader?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/postcss-loader?pack=default!./src/routes/login/Login.css 6:2797-2819
Child
    Time: 6019ms
            Asset    Size  Chunks             Chunk Names
        server.js  197 kB       0  [emitted]  main
    server.js.map  192 kB       0  [emitted]  main

    ERROR in ./~/css-loader?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/postcss-loader?pack=default!./src/routes/login/Login.css
    Module not found: Error: Cannot resolve module 'blue@2x.png' in /home/nginx/domains/vps.manhhailua.com/public/src/routes/login
     @ ./~/css-loader?{"sourceMap":true,"modules":true,"localIdentName":"[name]_[local]_[hash:base64:3]","minimize":false}!./~/postcss-loader?pack=default!./src/routes/login/Login.css 6:2797-2819
webpack: bundle is now VALID.
Error: Cannot find module 'blue.png'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/external "blue.png":1:1)
    at __webpack_require__ (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/webpack/bootstrap d18f3b7e0ce5c43519c3:19:1)
    at Object.<anonymous> (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/routes/login/Login.css:6:1324)
    at __webpack_require__ (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/webpack/bootstrap d18f3b7e0ce5c43519c3:19:1)
    at Object.<anonymous> (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/routes/login/Login.css?8ea8:2:1)
    at __webpack_require__ (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/webpack/bootstrap d18f3b7e0ce5c43519c3:19:1)
    at Object.<anonymous> (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/routes/login/Login.js:15:1)
    at __webpack_require__ (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/webpack/bootstrap d18f3b7e0ce5c43519c3:19:1)
    at Object.module.exports.Object.defineProperty.value (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/routes/login/index.js:11:1)
    at __webpack_require__ (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/webpack/bootstrap d18f3b7e0ce5c43519c3:19:1)
    at Object.module.exports.Object.defineProperty.value (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/routes/index.js:16:1)
    at __webpack_require__ (/home/nginx/domains/vps.manhhailua.com/public/build/webpack:/webpack/bootstrap d18f3b7e0ce5c43519c3:19:1)
/home/nginx/domains/vps.manhhailua.com/public/tools/runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
        ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (/home/nginx/domains/vps.manhhailua.com/public/tools/runServer.js:53:15)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

npm ERR! Linux 3.10.0-327.28.2.el7.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.3.1/bin/node" "/root/.nvm/versions/node/v6.3.1/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nginx/domains/vps.manhhailua.com/public/npm-debug.log
```

**Comment by alex-shamshurin** [comment]
Url paths are normally resolved by css-loader, but when we use sass or stylus or less  loader before, it yields another file with complied result and those url(...) are not valid anymore. I do not know right way how to fix it. I just add a webpack resolver fallback option  to 'image' folder and I keep all images in that folder, so it resolves with webpack normally.

**Comment by manhhailua** [comment]
I'm now use package `postcss-partial-import` instead of `postcss-import`. The `@import` statement will be put directly into the `Html`.
Note: Ensure css file existed in `public` folder

**Comment by yanglilong127** [comment]
in webpack.config.js add resolve.alias,and  require('')
