### ISSUE TITLE
Missing modules when installing from repository.

### ISSUE THREAD

**Issue by VictorVanShima** [kriasoft/react-starter-kit#846]
Attempted to install commit be660f6d5a413078a83bdd2ce8f946b2dfef0147 by following the steps at https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md . Machine is a Fedora 23 with few NPM modules already installed.

_My apologies for possible unnecessary content. I am very new to ReactJS and the NPM universe in general._

While doing `npm install` I got multiple missing module errors. The one below is a single example.

```
...
npm http GET https://registry.npmjs.org/pinkie-promise

module.js:340
    throw err;
          ^
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/shima/Projects/BalancaPianos-Website/website/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm ERR! Error: ENOENT, lstat '/home/shima/tmp/npm-22459-DsAH_qti/1473523801930-0.15078002610243857/package/shim.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.6.4-201.fc23.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/shima/Projects/BalancaPianos-Website/website
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! path /home/shima/tmp/npm-22459-DsAH_qti/1473523801930-0.15078002610243857/package/shim.js
npm ERR! fstream_path /home/shima/tmp/npm-22459-DsAH_qti/1473523801930-0.15078002610243857/package/shim.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http 304 https://registry.npmjs.org/pinkie-promise
...
```

Installed the missing modules with:

```
npm install nopt
npm install npmlog
npm install semver
npm install rimraf
```

After adding of of these modules it installed these last modules below. So maybe the missing dependencies are related to them.

```
postcss-import@8.1.2 node_modules/postcss-import
├── object-assign@4.1.0
├── postcss-value-parser@3.3.0
├── resolve@1.1.7
├── read-cache@1.0.0 (pify@2.3.0)
└── pkg-resolve@0.1.14 (jspm@0.17.0-beta.28)

sqlite3@3.1.4 node_modules/sqlite3
└── nan@2.3.5
```

**Comment by ulani** [comment]
@VictorVanShima   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
