### ISSUE TITLE
Spread Operator in webpack.config.js causes Unexpected Token Error

### ISSUE THREAD

**Issue by nathanpiazza** [kriasoft/react-starter-kit#866]
I have been happily hacking on an React Starter kit for a few days now, without any build problems. 

But as soon as I deployed the application to Azure, I started running into all kinds of problems. I finally figured out how to customize the deployment scripts that Kudu uses to invoke Starter Kits' build target (the included deploy.js file only works if you want to push to Azure from your local, not automate deployments from Github as I'm doing). But I ran into the problem that when running "run build -- --release" on Azure (and ONLY on Azure), I get the following error:

D:\home\site\wwwroot\tools\webpack.config.js:68
        plugins: ['transform-runtime', ...(DEBUG ? [] : ['transform-react-remove-prop-types', 'transform-react-constant-elements', 'transform-react-inline-elements'])]
                                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (D:\home\site\wwwroot\node_modules\babel-register\lib\node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js](D:homesitewwwrootnode_modulesbabel-registerlibnode.js:156:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:/home/site/wwwroot/tools/bundle.js:11:1)
    at Module._compile (module.js:435:26)
    at loader (D:\home\site\wwwroot\node_modules\babel-register\lib\node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js](D:homesitewwwrootnode_modulesbabel-registerlibnode.js:156:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
An error has occurred during web site deployment.
    at Module.require (module.js:366:17)
npm build failed
    at require (module.js:385:17)

I've tried adding the stage3 babel preset, but that doesn't seem to work. And I'm still stumped as to why this would work on my local (Mac) environment, but not on Azure. npm install runs fine, with the exact same package.json. And as far as I can tell, both environments are using the exact same versions of node and babel-node. So what could be the problem here? Why would it work on one environment and not the other?

**Comment by nathanpiazza** [comment]
So I solved my own problem. I just needed to add the "es2015" preset to the package.json babel config section. It was present in the webpack config itself (in the babel loader block), but it wasn't being used to interpret webpack.config.js. For that it needed to be in the .babelrc (or in my case, since I'm not using a .babelrc in Azure, in package.json).

**Comment by mkliu** [comment]
@nathanpiazza can you please share the custom deployment you've done? i want to do the same thing too.

**Comment by frenzzy** [comment]
@mkliu just install node v6.5 or above

**Comment by edouard-lopez** [comment]
Add similar error my config `package.json` was overriden by the `.babelrc` file.

### Solution

Remove the `.babelrc`

**Comment by ulani** [comment]
@nathanpiazza   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
