### ISSUE TITLE
run start errors in windows envronment

### ISSUE THREAD

**Issue by savemuse** [kriasoft/react-starter-kit#868]
could you give me advise me why I have this error ?
node -v //  v6.6.0
npm - v //  v3.10.3

> babel-node tools/run start

[20:15:45] Starting 'start'...
[20:15:45] Starting 'clean'...
[20:16:01] Finished 'clean' after 15578 ms
[20:16:01] Starting 'bound copy'...
[20:16:01] Finished 'bound copy' after 183 ms
webpack built 8ede3c2b87b58d3d7951 in 7289ms
Child
    Time: 7289ms
                               Asset     Size  Chunks             Chunk Names
        main.js?8ede3c2b87b58d3d7951  1.64 MB       0  [emitted]  main
    main.js.map?8ede3c2b87b58d3d7951  1.95 MB       0  [emitted]  main
Child
    Time: 5220ms
            Asset    Size  Chunks             Chunk Names
        server.js  202 kB       0  [emitted]  main
    server.js.map  225 kB       0  [emitted]  main
webpack: bundle is now VALID.
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventEmitter.listen (D:\test\MyApp\node_modules\express\lib\application.j
s:617:24)
    at D:\test\MyApp\build\webpack:\server.js:138:7
    at tryCatcher (D:\test\MyApp\node_modules\bluebird\js\release\util.js:16:23)

```
at Promise._settlePromiseFromHandler (D:\test\MyApp\node_modules\bluebird\js
```

\release\promise.js:510:31)
    at Promise._settlePromise (D:\test\MyApp\node_modules\bluebird\js\release\pr
omise.js:567:18)
    at Promise._settlePromise0 (D:\test\MyApp\node_modules\bluebird\js\release\p
romise.js:612:10)
    at Promise._settlePromises (D:\test\MyApp\node_modules\bluebird\js\release\p
romise.js:691:18)
    at Async._drainQueue (D:\test\MyApp\node_modules\bluebird\js\release\async.j
s:138:16)
    at Async._drainQueues (D:\test\MyApp\node_modules\bluebird\js\release\async.
js:148:10)
    at Immediate.Async.drainQueues (D:\test\MyApp\node_modules\bluebird\js\relea
se\async.js:17:14)
    at runCallback (timers.js:574:20)
D:\test\MyApp\tools\runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${ code } sig
nal: ${ signal }`);
        ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (D:/test/MyApp/tools/runServer.js:53:15)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\MyApp\npm-debug.log

**Comment by garfieldnate** [comment]
Same problem as #759?

**Comment by ucay** [comment]
> Same problem as #759?

I think it's because port 3000 already in use.
`Error: listen EADDRINUSE :::3000`

You can change the server's listen port, or kill service that using port 3000

**Comment by ulani** [comment]
@savemuse   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
