### ISSUE TITLE
Gulp build error with assets step - AssertionError: path must be a string

### ISSUE THREAD

**Issue by ponytrouble** [kriasoft/react-starter-kit#88]
Trying to get started using this seed project.  After setting a NODE_PATH properly and installing missing npm modules, I'm encountering build problems.  

Is this some version issue?  `AssertionError: path must be a string` doesn't seem to point to anything?  Many thanks for pointers.  

```javascript
C:\www\www repos\react-starter-kit>gulp build
[18:11:53] Using gulpfile C:\www\www repos\react-starter-kit\gulpfile.js
[18:11:53] Starting 'clean'...
[18:11:53] Finished 'clean' after 9.86 ms
[18:11:53] Starting 'build'...
[18:11:53] Starting 'vendor'...
[18:11:53] Starting 'assets'...
[18:11:53] 'assets' errored after 6.49 ms
[18:11:53] AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at requireFn (C:\www\www repos\react-starter-kit\node_modules\gulp-load-plugins\index.js:37:14)
    at Object.defineProperty.get (C:\www\www repos\react-starter-kit\node_modules\gulp-load-plugins\index.js:59:18)
    at Gulp.gulp.task.src.styles (C:\www\www repos\react-starter-kit\gulpfile.js:61:13)
    at module.exports (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:27
3:3)
    at Gulp.Orchestrator._runStep (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:21
4:10)
    at Gulp.Orchestrator.start (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:134:8
)
    at runNextSet (C:\www\www repos\react-starter-kit\node_modules\run-sequence\index.js:74:16)
[18:11:53] 'build' errored after 47 ms
[18:11:53] Error: [object Object]
    at formatError (C:\Program Files (x86)\nodejs\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\index.
js:264:8)
    at C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\www\www repos\react-starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (C:\www\www repos\react-starter-kit\node_modules\run-sequence\index.js:48:5)
    at Gulp.onError (C:\www\www repos\react-starter-kit\node_modules\run-sequence\index.js:55:4)
    at Gulp.emit (events.js:117:20)
[18:11:53] Finished 'vendor' after 67 ms
```

**Comment by ponytrouble** [comment]
I am spotting some horribly nested folders, eg `node_modules` here: 

`C:\www\www repos\react-starter-kit\node_modules\gulp-load-plugins\node_modules\multimatch\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match`

**Comment by ponytrouble** [comment]
Got through it installing various dependent node-modules, such as node-gyp, node python, python + the python environment variable, etc.  Thanks.

**Comment by duranmla** [comment]
How did you solve it @sodacrackers ?
