### ISSUE TITLE
Problem while testing.

### ISSUE THREAD

**Issue by iraycd** [kriasoft/react-starter-kit#942]
```
> @ test /Users/iraycd/Documents/Workspace/react-starter-kit
> mocha "src/**/*.test.js" --require babel-register --require test/setup.js

/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /Users/iraycd/Documents/Workspace/react-starter-kit/src/components/App.js: Missing class properties transform.
  41 | class App extends React.Component {
  42 | 
> 43 |   static propTypes = {
     |   ^
  44 |     context: PropTypes.shape(ContextType).isRequired,
  45 |     children: PropTypes.element.isRequired,
  46 |   };
    at File.buildCodeFrameError (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:431:15)
    at NodePath.buildCodeFrameError (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/index.js:140:26)
    at undefined.pushBody (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:262:20)
    at undefined.buildBody (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:229:10)
    at undefined.run (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:143:10)
    at PluginPass.ClassExpression (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:48:60)
    at newFn (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitQueue (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:156:21)
    at TraversalContext.visitMultiple (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:558:35)
    at /Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:574:16)
    at Pipeline.transform (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-core/lib/api/node.js:138:10)
    at compile (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/iraycd/Documents/Workspace/react-starter-kit/src/components/Layout/Layout.test.js:18:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/iraycd/Documents/Workspace/react-starter-kit/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.

```

**Comment by frenzzy** [comment]
Which node.js version do you use? Did you see [requirements](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#requirements)?

**Comment by iraycd** [comment]
I am using `v6.9.1`

**Comment by frenzzy** [comment]
Maybe you have `.babelrc` file in the root folder which overrides [package.json/babel](https://github.com/kriasoft/react-starter-kit/blob/db08f54fb907b047d6ed163419fd00a60a456582/package.json#L108-L130) rules?
Just pulled latest master with node 6.9.1 and fresh install dependencies, tests works well.

**Comment by ulani** [comment]
@iraycd   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
