### ISSUE TITLE
resolve extensions  '.web.js'  suffix  not working

### ISSUE THREAD

**Issue by IDrinkMoreWater** [kriasoft/react-starter-kit#946]
**Webpack config：**
```
  resolve: {
    root: path.resolve(__dirname, '../src'),
    modulesDirectories: ['node_modules',path.resolve(__dirname, '../node_modules') ],
    extensions: ['', '.webpack.js', '.web.js', '.js', '.jsx', '.json'],
  },
```

**Register   Import：**
```
import React, { PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import Layout from '../../components/Layout';
import Button from 'antd-mobile/lib/button';
```

**Console error log：**
```
Error: Cannot find module 'react-native'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\IDEAFrontWorksapce\egodrug-front-end\trunk\egodrug-weixin-shop\node_modules\antd-mobile\lib\button\index.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\IDEAFrontWorksapce\egodrug-front-end\trunk\egodrug-weixin-shop\build\webpack:\external "antd-mobile\lib\button":1:1)
    at __webpack_require__ (E:\IDEAFrontWorksapce\egodrug-front-end\trunk\egodrug-weixin-shop\build\webpack:\webpack\bootstrap bc3b2b4191b4e1817349:19:1)
    at Object.<anonymous> (E:\IDEAFrontWorksapce\egodrug-front-end\trunk\egodrug-weixin-shop\build\webpack:\routes\register\Register.js:13:1)
    at __webpack_require__ (E:\IDEAFrontWorksapce\egodrug-front-end\trunk\egodrug-weixin-shop\build\webpack:\webpack\bootstrap bc3b2b4191b4e1817349:19:1)
E:\IDEAFrontWorksapce\egodrug-front-end\trunk\egodrug-weixin-shop\tools\runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (E:/IDEAFrontWorksapce/egodrug-front-end/trunk/egodrug-weixin-shop/tools/runServer.js:54:17)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Problem**
```
in the ' antd-mobile\lib\button' folder ,exist  index.web.js file and  index.js  file, index.js  will require reat-native.

expected :  index.web.js  higher order than index.js   ,  'antd-mobile\lib\button\index.web.js' will loaded
reality : 'antd-mobile\lib\button\index.web.js' not loaded，but 'antd-mobile\lib\button\index.js' is loaded.

if change 
  import Button from 'antd-mobile/lib/button'; 
to
  import Button from '../../../node_modules/antd-mobile/lib/button';
'antd-mobile\lib\button\index.web.js' will loaded，

```

**Comment by ulani** [comment]
@IDrinkMoreWater   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
