### ISSUE TITLE
how to debug: Server terminated unexpectedly with code: 1 signal: null

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#954]
Hi,
what is the best way to debug "Server terminated unexpectedly with code: 1 signal: null"?

I'm a bit lost. I've imported [react-wavesurfer](https://github.com/mspae/react-wavesurfer) and it throws me the whole minified code of [wavesurfer.js](https://github.com/katspaugh/wavesurfer.js) along with the error _Server terminated unexpectedly with code: 1 signal: null_ in the console when running "npm run start" right after _webpack  built_.

The npm debug file has no helpful information either:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maxmitschke/Work/wtc-react/node_modules/.bin:/usr/local/bin:/Users/maxmitschke/.rvm/gems/ruby-2.3.0/bin:/Users/maxmitschke/.rvm/gems/ruby-2.3.0@global/bin:/Users/maxmitschke/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/maxmitschke/.rvm/bin
10 verbose lifecycle @~start: CWD: /Users/maxmitschke/Work/wtc-react
11 silly lifecycle @~start: Args: [ '-c', 'babel-node tools/run start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Users/maxmitschke/Work/wtc-react
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error @ start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script 'babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ulani** [comment]
@mxmtsk   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
