### ISSUE TITLE
Error: Server terminated unexpectedly with code: 1 signal: null

### ISSUE THREAD

**Issue by kudlajz** [kriasoft/react-starter-kit#956]
Hi,

I've used your kit before (and it was working), but yesterday, I've cloned the `feature/react-intl` branch, I've done `npm i` and when I run `npm start` I get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kudlajz/Work/catchoutfit/node_modules/.bin:/usr/local/bin:~/.npm/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle @~start: CWD: /Users/kudlajz/Work/catchoutfit
11 silly lifecycle @~start: Args: [ '-c', 'babel-node tools/run start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `babel-node tools/run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd /Users/kudlajz/Work/catchoutfit
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.12.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error @ start: `babel-node tools/run start`
22 error Exit status 1
23 error Failed at the @ start script 'babel-node tools/run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node tools/run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm running macOS Sierra.
I haven't made any changes to the source code prior to running the script.

Thank you for your help.

**Comment by kudlajz** [comment]
Problem persist when using Ubuntu 16.04 (both npm and node have the same version).

**Comment by aeldaly** [comment]
Why did you close it? Did you manage to find a solution? I'm facing the exact problem

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/aeldaly/.nvm/versions/node/v6.9.1/bin/node" "/Users/aeldaly/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
```

**Comment by kudlajz** [comment]
@aeldaly I haven't noticed that they changed node version requirements.. I've upgraded node to version 6 and all is working again.
