### ISSUE TITLE
Error when use models in routes

### ISSUE THREAD

**Issue by tk1cntt** [kriasoft/react-starter-kit#976]
1. Clone project https://github.com/kriasoft/react-starter-kit.git
2. Open file routes/home/index.js
3. Add line `import { User, UserLogin, UserClaim, UserProfile } from '../../data/models';`
4. Start project

Have been error.

```
tran:react-starter-kit tuan$ yarn
yarn install v0.16.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning browser-sync > localtunnel > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 52.34s.
tran:react-starter-kit tuan$ atom .
tran:react-starter-kit tuan$ yarn start
yarn start v0.16.1
$ babel-node tools/run start 
[13:53:50] Starting 'start'...
[13:53:50] Starting 'clean'...
[13:53:51] Finished 'clean' after 682 ms
[13:53:51] Starting 'copy'...
[13:53:51] Finished 'copy' after 167 ms
webpack built 34fe5e2824876804e470 in 18832ms
Child
    Time: 18832ms
    
    WARNING in ./~/sequelize/lib/sequelize.js
    Critical dependencies:
    686:60-73 the request of a dependency is an expression
     @ ./~/sequelize/lib/sequelize.js 686:60-73
    
    WARNING in ./~/sequelize/lib/dialects/mssql/connection-manager.js
    Critical dependencies:
    18:15-71 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/mssql/connection-manager.js 18:15-71
    
    WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
    Critical dependencies:
    18:17-60 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/mysql/connection-manager.js 18:17-60
    
    WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
    Critical dependencies:
    20:14-57 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/postgres/connection-manager.js 20:14-57
    
    WARNING in ./~/sequelize/lib/dialects/sqlite/connection-manager.js
    Critical dependencies:
    22:15-71 the request of a dependency is an expression
     @ ./~/sequelize/lib/dialects/sqlite/connection-manager.js 22:15-71
    
    WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
    Module not found: Error: Cannot resolve module 'mysql' in /Users/tuan/projects/gcloud-server/websites/react-starter-kit/node_modules/sequelize/lib/dialects/mysql
     @ ./~/sequelize/lib/dialects/mysql/connection-manager.js 20:17-33
    
    WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
    Module not found: Error: Cannot resolve module 'pg' in /Users/tuan/projects/gcloud-server/websites/react-starter-kit/node_modules/sequelize/lib/dialects/postgres
     @ ./~/sequelize/lib/dialects/postgres/connection-manager.js 22:14-27
    
    ERROR in ./~/sequelize/lib/dialects/postgres/hstore.js
    Module not found: Error: Cannot resolve module 'pg-hstore' in /Users/tuan/projects/gcloud-server/websites/react-starter-kit/node_modules/sequelize/lib/dialects/postgres
     @ ./~/sequelize/lib/dialects/postgres/hstore.js 3:13-33
Child
    Time: 12927ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  271 kB       0  [emitted]  main
    ../../server.js.map  242 kB       0  [emitted]  main
webpack: bundle is now VALID.
Error: Cannot find module './assets'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tuan/projects/gcloud-server/websites/react-starter-kit/build/webpack:/external "./assets":1:1)
    at __webpack_require__ (/Users/tuan/projects/gcloud-server/websites/react-starter-kit/build/webpack:/webpack/bootstrap 0ee76b4f98f75ce71531:19:1)
    at Object.<anonymous> (/Users/tuan/projects/gcloud-server/websites/react-starter-kit/build/webpack:/server.js:30:1)
    at __webpack_require__ (/Users/tuan/projects/gcloud-server/websites/react-starter-kit/build/webpack:/webpack/bootstrap 0ee76b4f98f75ce71531:19:1)
    at /Users/tuan/projects/gcloud-server/websites/react-starter-kit/build/webpack:/webpack/bootstrap 0ee76b4f98f75ce71531:39:1
    at Object.<anonymous> (/Users/tuan/projects/gcloud-server/websites/react-starter-kit/build/server.js:45:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
/Users/tuan/projects/gcloud-server/websites/react-starter-kit/tools/runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (/Users/tuan/projects/gcloud-server/websites/react-starter-kit/tools/runServer.js:54:17)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
error Command failed with exit code 1.
```

**Comment by archansel** [comment]
I posted similar question few days ago and closed it after found out what went wrong

As @frenzzy mention before, you must use it on server side code, e.g. in server.js 

You can make endpoint that can manipulate your model (create retrieve update or delete) and then access it from client side using fetch

**Comment by tk1cntt** [comment]
@frenzzy  I using models in routes/home/index.js.

**Comment by ulani** [comment]
@tk1cntt   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
